<?php
/**
 * Implements hook_menu().
 */
function lyopen_menu() {
  $items = array();
  $items['lyopen/get/%/%'] = array(
    'page callback' => 'lyopen_get',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function lyopen_get($index=604,$max=7){
  module_load_include('php', 'mp_liangyou', 'liangyou_audio_list');
  $radios = liangyou_audio_list_byindex();
//   生活智慧
//   【609】微播出炉
//   【612】书香园地
//   【614】今夜心未眠
//   【608】绝妙当家
//   【610】生活无国界
//   【611】零点零距离
//   【619】拥抱每一天
// 婚恋家庭
//   【604】恋爱季节
//   【605】幸福满家园
//   【606】亲情不断电
//   【607】欢乐卡恰碰

//   【616】长夜的牵引
//   【631】经动人心
  $allow_index = array('604','605','606','607','608','609','610','611','612','614','616','619','631');

  if(!in_array($index, $allow_index)) drupal_access_denied();//not allow!

  $radio = $radios[$index];
  $upyun_bucket_name = 'lywxaudio';
  $cdnlink = $upyun_bucket_name.'.b0.upaiyun.com';
  $offset=0;
  // $max = 7;
  $js_radios = array();
  $code = $radio['code'];

  $file_key = drupal_realpath('public://cron/txly2/'.$code.'.json');
  if(file_exists($file_key))
    $descs = json_decode(file_get_contents($file_key),true);
  while ($offset <= 30) {
    $date = date('ymd',time()-$offset*86400);
    $path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
    $musicurl = 'http://'.$cdnlink.$path.upyun_get_token($path,864000);
    $temp = @get_headers($musicurl);
    if(count($js_radios)>=$max) break;
    $js_radio =array();
    if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
      $js_radio['title'] = $radio['title'];
      if(isset($descs['20'.$date])){
        $js_radio['desc'] = $descs['20'.$date];
      }
      $js_radio['date'] = $date;
      $js_radio['category'] = $radio['category'];
      $js_radio['mp3'] = $musicurl;
      $js_radios[]= $js_radio;
      // break;
    }
    $offset++;
  }
  // dpm($js_radios);
  // return 'nothing';
  // $playlist = json_encode($js_radios);
  gapushagent('event',array(
   'category'        => 'lyopen',
   'action'          => $index,
   'label'           => $radio['title'],
  ));
  header('Content-Type: application/json');
  print json_encode($js_radios);
  drupal_exit();
}
///////begin for ly meta!
//need ECK  /admin/structure/entity-type/metadata/lymeta/fields
// ly_code field_ly_code Text  Text field
// ly_desc field_ly_desc Text  Text field
// ly_date field_ly_date Integer Text field
/**
 * [get_lymeta description]
 * @param  string $code [description]
 * @param  [type] $date [description]
 * @return [type]       [description]
 */
function get_lymeta($code='ee',$date=NULL){
  if(!$date) $date = date('Ymd');
  $query = db_select('field_data_field_ly_desc', 'd');
  $query->join('field_data_field_ly_code', 'c', 'c.entity_id = d.entity_id');
  $query->join('field_data_field_ly_date', 'e', 'e.entity_id = d.entity_id');
  $query->fields('d', array('field_ly_desc_value'));
  $query->condition('c.field_ly_code_value',$code);
  $query->condition('e.field_ly_date_value',$date);
  $desc = $query->execute()->fetchField();
  return $desc;
}
/**
 * [save_lymeta description]
 * @param  [type] $code [description]
 * @param  [type] $desc [description]
 * @param  [type] $date [description]
 * @return [int] entityID       [description]
 */
function save_lymeta($code,$desc,$date=NULL){
  if(!$date) $date = date('Ymd');
  //check if exsits ,don't save!
  if(!get_lymeta($code,$date)){
    $entity = entity_create('metadata', array('type' =>'lymeta'));
    $entity->field_ly_code = array(LANGUAGE_NONE => array(0 => array('value' =>  $code)));
    $entity->field_ly_desc = array(LANGUAGE_NONE => array(0 => array('value' =>  $desc)));
    $entity->field_ly_date = array(LANGUAGE_NONE => array(0 => array('value' =>  $date)));
    $entity->save();
    return $entity->id;
  }
}
  // $now = time();
  // $i = 0;
  // while ($i <= 100) {
  //   $index = date('Ymd',$now-$i*86400);
  //   $file_key = drupal_realpath('public://cron/txly2/'.$index.'.json') ;
  //   if(file_exists($file_key)) {
  //     $data = json_decode(file_get_contents($file_key),true);
  //     foreach ($data as $key => $radio) {
  //       save_lymeta($radio['code'],$radio['desc'],(int)$radio['date']);
  //     }
  //   }
  //   $i++;
  // }
///end of ly meta!
