<?php
/**
 * 良友圣经学院
 */
function get_ly_mav(){
  return array(
    'a1'=>array(
      'prefex'  => 'mavst0',
      'count'=>24,
      'title'=>'主日学教学法',
      'level'=>'1',//本科课程
      'pdf' => '1',//本科课程/主日学教学法/主日学教学法.pdf=level+title+pdf
    ),
    'a2'=>array(
      'prefex'  => 'mavop0',
      'count'=>30,
      'title'=>'先知书I',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a3'=>array(
      'prefex'  => 'mavor0',
      'count'=>30,
      'title'=>'先知书II',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a4'=>array(
      'prefex'  => 'mavrt0',
      'count'=>30,
      'title'=>'启示录',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a5'=>array(
      'prefex'  => 'mavfe0',
      'count'=>24,
      'title'=>'团契生活',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a6'=>array(
      'prefex'  => 'mavpn1',
      'count'=>24,
      'title'=>'圣灵论',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a7'=>array(
      'prefex'  => 'mavtb0',
      'count'=>24,
      'title'=>'圣经教师训练',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a8'=>array(
      'prefex'  => 'mavbi0',
      'count'=>24,
      'title'=>'圣经背景',
      'level'=>'1',
      'pdf' => '1'
    ),
    'a9'=>array(
      'prefex'  => 'mavcw0',
      'count'=>24,
      'title'=>'基督工人操守',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b1'=>array(
      'prefex'  => 'mavcs0',
      'count'=>24,
      'title'=>'基督教与科学',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b2'=>array(
      'prefex'  => 'mavcd0',
      'count'=>30,
      'title'=>'基督教教义',
      'level'=>'1',
      'pdf' => '2'
    ),
    'b3'=>array(
      'prefex'  => 'mavmc0',
      'count'=>30,
      'title'=>'婚姻辅导',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b4'=>array(
      'prefex'  => 'mavoe1',
      'count'=>6,
      'title'=>'学习锦囊',
      'level'=>'1',
      'pdf' => '0'//To change name!!-1本科课程/学习锦囊/第十一届课程概览.pdf
    ),
    'b5'=>array(
      'prefex'  => 'mavhx0',
      'count'=>30,
      'title'=>'异端与极端',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b6'=>array(
      'prefex'  => 'mavch0',
      'count'=>30,
      'title'=>'教会历史',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b7'=>array(
      'prefex'  => 'mavcm0',
      'count'=>24,
      'title'=>'教会复兴运动',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b8'=>array(
      'prefex'  => 'mavca0',
      'count'=>24,
      'title'=>'教会行政',
      'level'=>'1',
      'pdf' => '1'
    ),
    'b9'=>array(
      'prefex'  => 'mavnt0',
      'count'=>30,
      'title'=>'新约综览',
      'level'=>'1',
      'pdf' => '2'
    ),    //本科课程/新约综览/新约综览考题.doc //本科课程/新约综览/新约综览考题.pdf
    'c1'=>array(
      'prefex'  => 'mavot0',
      'count'=>30,
      'title'=>'旧约综览',
      'level'=>'1',
      'pdf' => '2'
    ),
    'c2'=>array(
      'prefex'  => 'mavge0',
      'count'=>30,
      'title'=>'普通书信',
      'level'=>'1',
      'pdf' => '1'
    ),
    'c3'=>array(
      'prefex'  => 'mavom0',
      'count'=>18,
      'title'=>'本土差传',
      'level'=>'1',
      'pdf' => '1'
    ),
    'c4'=>array(
      'prefex'  => 'mavsw0',
      'count'=>24,
      'title'=>'神迹奇事',
      'level'=>'1',
      'pdf' => '1'
    ),
    'c5'=>array(
      'prefex'  => 'mavrs0',
      'count'=>30,
      'title'=>'罗马书',
      'level'=>'1',
      'pdf' => '1'
    ),
    'c6'=>array(
      'prefex'  => 'mavhe0',
      'count'=>24,
      'title'=>'解经与研经',
      'level'=>1,
      'pdf' => 2,
    ),
    'c7'=>array(
      'prefex'  => 'mavpb0',
      'count'=>30,
      'title'=>'诗歌智慧书I',
      'level'=>1,
      'pdf' => 1,
    ),
    'c8'=>array(
      'prefex'  => 'mavpk0',
      'count'=>30,
      'title'=>'诗歌智慧书II',
      'level'=>1,
      'pdf' => 1,
    ),
    'c9'=>array(
      'prefex'  => 'mavlu0',
      'count'=>30,
      'title'=>'路加福音',
      'level'=>1,
      'pdf' => 1,
    ),
    'd1'=>array(
      'prefex'  => 'mavym0',
      'count'=>24,
      'title'=>'青少年事工',
      'level'=>1,
      'pdf' => 1,
    ),
        // 本科课程/2015毕业周特辑/mavsp328.mp3
        // 本科课程/2015毕业周特辑/mavsp329.mp3
        // 本科课程/2015毕业周特辑/mavsp330.mp3
        // 本科课程/2015毕业周特辑/mavsp331.mp3
        // 本科课程/2015毕业周特辑/mavsp332.mp3
        // 本科课程/2015毕业周特辑/mavsp333.mp3
        // 本科课程/33周年院庆培灵会/mavsp334.mp3
        // 本科课程/33周年院庆培灵会/mavsp335.mp3
        // 本科课程/33周年院庆培灵会/mavsp336.mp3
        // 本科课程/33周年院庆培灵会/mavsp337.mp3
        // 本科课程/33周年院庆培灵会/mavsp338.mp3
        // 本科课程/33周年院庆培灵会/mavsp339.mp3
        // 本科课程/本科2015开学周特辑/mavsp340.mp3
        // 本科课程/本科2015开学周特辑/mavsp341.mp3
        // 本科课程/本科2015开学周特辑/mavsp342.mp3
        // 本科课程/本科2015开学周特辑/mavsp343.mp3
        // 本科课程/本科2015开学周特辑/mavsp344.mp3
        // 本科课程/本科2015开学周特辑/mavsp345.mp3
    //level=2 进深课程
    'e1'=>array(
      'prefex'  => 'mavee0',
      'count'=>24,
      'title'=>'以弗所书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e2'=>array(
      'prefex'  => 'mavis0',
      'count'=>30,
      'title'=>'以赛亚书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e3'=>array(
      'prefex'  => 'mavda0',
      'count'=>24,
      'title'=>'但以理书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e4'=>array(
      'prefex'  => 'mavgs1',
      'count'=>24,
      'title'=>'创世记',
      'level'=>2,
      'pdf' => 1,
    ),
    'e5'=>array(
      'prefex'  => 'mavga0',
      'count'=>24,
      'title'=>'加拉太书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e6'=>array(
      'prefex'  => 'mavdr0',
      'count'=>18,
      'title'=>'启示论',
      'level'=>2,
      'pdf' => 1,
    ),
    'e7'=>array(
      'prefex'  => 'mavic0',
      'count'=>24,
      'title'=>'哥林多前书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e8'=>array(
      'prefex'  => 'mavio0',
      'count'=>24,
      'title'=>'哥林多后书',
      'level'=>2,
      'pdf' => 1,
    ),
    'e9'=>array(
      'prefex'  => 'mavbl0',
      'count'=>24,
      'title'=>'圣经文学导论',
      'level'=>2,
      'pdf' => 1,
    ),
    'f1'=>array(
      'prefex'  => 'mavbt0',
      'count'=>24,
      'title'=>'圣经神学',
      'level'=>2,
      'pdf' => 1,
    ),
    'f2'=>array(
      'prefex'  => 'mavcy1',
      'count'=>24,
      'title'=>'基督论',
      'level'=>2,
      'pdf' => 1,
    ),
    'f3'=>array(
      'prefex'  => 'mavso1',
      'count'=>24,
      'title'=>'崇拜学',
      'level'=>2,
      'pdf' => 1,
    ),
    'f4'=>array(
      'prefex'  => 'mavmg0',
      'count'=>24,
      'title'=>'差传神学',
      'level'=>2,
      'pdf' => 1,
    ),
    'f5'=>array(
      'prefex'  => 'mavhb1',
      'count'=>24,
      'title'=>'希伯来书',
      'level'=>2,
      'pdf' => 1,
    ),
    'f6'=>array(
      'prefex'  => 'mavsn0',
      'count'=>24,
      'title'=>'救恩论',
      'level'=>2,
      'pdf' => 1,
    ),
    'f7'=>array(
      'prefex'  => 'mavey0',
      'count'=>24,
      'title'=>'教会论',
      'level'=>2,
      'pdf' => 1,
    ),
    'f8'=>array(
      'prefex'  => 'mavps1',
      'count'=>24,
      'title'=>'教牧书信',
      'level'=>2,
      'pdf' => 1,
    ),
    'f9'=>array(
      'prefex'  => 'mavpt0',
      'count'=>24,
      'title'=>'教牧学',
      'level'=>2,
      'pdf' => 1,
    ),
    'g1'=>array(
      'prefex'  => 'mavpc0',
      'count'=>24,
      'title'=>'教牧辅导',
      'level'=>2,
      'pdf' => 1,
    ),   //进深课程/教牧辅导/婚前辅导手册.pdf
    'g2'=>array(
      'prefex'  => 'mavng1',
      'count'=>24,
      'title'=>'新约神学',
      'level'=>2,
      'pdf' => 1,
    ),
    'g3'=>array(
      'prefex'  => 'mavog0',
      'count'=>24,
      'title'=>'旧约神学',
      'level'=>2,
      'pdf' => 1,
    ),
    'g3'=>array(
      'prefex'  => 'mavet0',
      'count'=>24,
      'title'=>'末世论',
      'level'=>2,
      'pdf' => 1,
    ),
    'g4'=>array(
      'prefex'  => 'mavhh0',
      'count'=>24,
      'title'=>'进深讲道学',
      'level'=>2,
      'pdf' => 1,
    ),
    'g5'=>array(
      'prefex'  => 'maveh1',
      'count'=>24,
      'title'=>'释经与讲道',
      'level'=>2,
      'pdf' => 1,
    ),
    'g6'=>array(
      'prefex'  => 'mavla0',
      'count'=>24,
      'title'=>'领袖训练I',
      'level'=>2,
      'pdf' => 1,
    ),
    'g7'=>array(
      'prefex'  => 'mavlb0',
      'count'=>24,
      'title'=>'领袖训练II',
      'level'=>2,
      'pdf' => 1,
    ),
  );
}

function get_lysd(){
  return array(
    '真我大看台'=>array(
      'title'=>'01-真我大看台',
      'begin'=>1,
      'end'=>21,
    ),
    '迎战压力'=>array(
      'title'=>'02-迎战压力',
      'begin'=>22,
      'end'=>30,
    ),
    '飞越忧郁的漩涡'=>array(
      'title'=>'03-飞越忧郁的漩涡',
      'begin'=>31,
      'end'=>31,
    ),
    '精神健康'=>array(
      'title'=>'04-精神健康',
      'begin'=>32,
      'end'=>45,
    ),
    '活出彩虹'=>array(
      'title'=>'05-活出彩虹',
      'begin'=>46,
      'end'=>55,
    ),
    '如何面对死亡'=>array(
      'title'=>'06-如何面对死亡',
      'begin'=>56,
      'end'=>61,
    ),
    '职场生涯纵横谈'=>array(
      'title'=>'07-职场生涯纵横谈',
      'begin'=>62,
      'end'=>71,
    ),
    '职场智慧'=>array(
      'title'=>'08-职场智慧',
      'begin'=>72,
      'end'=>91,
    ),
    '青年成长二部曲'=>array(
      'title'=>'09-青年成长二部曲',
      'begin'=>92,
      'end'=>101,
    ),
    '恋爱之道'=>array(
      'title'=>'10-恋爱之道',
      'begin'=>102,
      'end'=>106,
    ),
    '智慧有情人'=>array(
      'title'=>'11-智慧有情人',
      'begin'=>107,
      'end'=>115,
    ),
    '成功婚姻'=>array(
      'title'=>'12-成功婚姻',
      'begin'=>116,
      'end'=>125,
    ),
    '做个棒父母'=>array(
      'title'=>'13-做个棒父母',
      'begin'=>126,
      'end'=>131,
    ),
    '千头万绪家中来'=>array(
      'title'=>'14-千头万绪家中来',
      'begin'=>132,
      'end'=>140,
    ),
    '幸福三部曲'=>array(
      'title'=>'15-幸福三部曲',
      'begin'=>141,
      'end'=>178,
    ),// http://ly729.b0.upaiyun.com/lysd/001.mp3
    '让爱住你家'=>array(
      'title'=>'16-让爱住你家',
      'begin'=>179,
      'end'=>179,
    ),
  );
}

function get_ly_jckc(){
  return $jckc = array(//基础课程
    '1'  =>  array(
      'title' =>  '事奉装备',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavpr0',
      'order' =>'1',
    ),
    '2'  =>  array(
      'title' =>  '信仰与生活',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavfl0',
      'order' =>'2',
    ),
    '3'  =>  array(
      'title' =>  '基本研经法',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavbm0',
      'order' =>'3',
    ),
    '4'  =>  array(
      'title' =>  '基要真理',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavfb0',
      'order' =>'4',
    ),
    '5'  =>  array(
      'title' =>  '婚姻与家庭',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavmf1',
      'order' =>'5',
    ),
    '6'  =>  array(
      'title' =>  '新约浅说',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavkn0',
      'order' =>'6',
    ),
    '7'  =>  array(
      'title' =>  '旧约浅说',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavko0',
      'order' =>'7',
    ),
    '8'  =>  array(
      'title' =>  '耶稣生平',
      'pdf' => 1,
      'max' => 24,
      'legth' =>3,
      'prefex'  => 'mavls0',
      'order' =>'8',
    ),
  );
}
