<?php
/**
 * Implements hook_menu().
 */
function mp_liangyou_menu() {
  $items['get_upyun_token/%'] = array(
    'title' => '',
    'page callback' => 'get_upyun_token',
    'page arguments' => array(1,2),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
   );
  $items['cc_liangyou'] = array(
    'page callback' => '_mp_liangyou_cc',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
   );
  return $items;
}
function _mp_liangyou_cc(){
	// drupal_flush_all_caches();
  cache_clear_all('*', 'cache', TRUE);
	header('Content-type: application/json');
	print '[{"hi":"clean"}]';
}
function get_upyun_token($code,$offset=0){
	$cdnlink = 'http://lywxaudio.yongbuzhixi.com';
	require_once('liangyou_audio_list.php');
  $audios = liangyou_audio_list2();
  $lyaudio = $audios[$code];
	$title = $lyaudio['title'];
	// $offset=7;
	$date = date('ymd',time()-$offset*86400);
	$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
	$musicurl = $cdnlink.$path.upyun_get_token($path,86400);
	// return $musicurl;
	header('Content-type: application/json');
	// print '[{"hi":"clean"}]';
	print drupal_json_encode(array($musicurl));
}
/**
 * hook_rescources_info
 */
function mp_liangyou_rescources_info(){
	$rescources[] = array(
    'name' => 'ly2',
    'desc' =>	'良友电台【600】',
  );
	$rescources[] = array(
    'name' => '523',
    'desc' =>	'在天父怀中【523】',
  );
	$rescources[] = array(
    'name' => '400',
    'desc' =>	'圣经广播网【400】',
  );
	$rescources[] = array(
    'name' => '1225',
    'desc' =>	'耶稣全貌【1225】',
  );
	// $rescources[] = array(
 //    'name' => 'swty',
 //    'desc' =>	'世外桃源【ty】',
 //  );
  return $rescources;
}

/**
 * hook_wxrescources
 * TODO:	cache_clear_all('mp_liangyou', 'cache', TRUE); once a day!
 */
function mp_liangyou_wxresources($resources, $account, $keyword, $weObj){
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
	if(!(isset($enabled_resources['ly2']) && $enabled_resources['ly2'])){
		return $resources;
	}
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_liangyou_wxresources_'.$account->uid.$keyword)) {
      $my_data = $cache->data;
    }else {
      $my_data = _mp_liangyou_wxresources($resources, $account, $keyword, $weObj);
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  return $my_data;
}

function _mp_liangyou_wxresources($resources, $account, $keyword, $weObj){
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  {
  	if($keyword == 'ly'||$keyword == '良友'){
  		$file_key = drupal_realpath('public://cron/txly2/'.date('Ymd').'.json');
  		$data = json_decode(file_get_contents($file_key),true);
  		$news = array();
      $str = '';
  		foreach ($data as $key => $radio) {
  			if($radio['index'] =='604') continue;
  			$str .= '【'.$radio['index'].'】'.$radio['title'].'=>'.$radio['desc']."\n";
  		}
  		$img = array(
            'Title'=> '【今日良友节目概览】',
            'Description'=> $str."\n永不止息，需要有你\n回复【】内编号即可收听[加油]！",
            'PicUrl'=> 'http://mmbiz.qpic.cn/mmbiz/0fV5QBhibUJjvmqqUbJaL3ZPqIBKxPKpkq4SvjmagLGia5X6SDhTDKLY49qhWqE7ibyb6N1QUelvHv0ZnL5V7HWicA/640?wx_fmt=jpeg&tp=webp&wxfrom=5.jpg',
            'Url'=> 'http://ly.yongbuzhixi.com',
          );
      $news[] = $img;
		 	$resources['key_'.$keyword]= array(
        'type'  =>  'news',
        'cache' =>  43200,
        'obj'   =>  $news,
        );
			return $resources;
  	}
  	if($keyword == 'zb'||$keyword == '直播'){
	   	$resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'cache' =>  43200,
				'obj'		=> array(
  				'title'	=> '【zb】良友直播',
  				'desc'	=>	'点击►收听 耐心等待数秒钟 公众号:永不止息',
  				'musicurl'	=> 'http://ly729.out.airtime.pro:8000/ly729_a?'.time().'061.mp3',
  				'hgmusicurl'	=>	'http://ly729.out.airtime.pro:8000/ly729_a?'.time().'061.mp3',
				),
			);
      return $resources;
  	}
		// 600-652 stream ly
		require_once('liangyou_audio_list.php');
		$cdnlink = 'http://lywxaudio.yongbuzhixi.com';
	  if(isset($enabled_resources['ly2']) && $enabled_resources['ly2']){
			if($keyword == 600){
			 	$resources['key_'.$keyword] = array(
					'type'	=>	'text',
					'cache' =>  0,
					'obj'		=> array(
						'text'	=> ly_stream_menu(),
					)
				);
				return $resources;
			}
			$orikeyword = $keyword;
		  $audios = liangyou_audio_list2();
		  $lyaudio = array();
		  $lyaudio_code = FALSE;
		  if($orikeyword=='bv') $keyword='mw';
		  foreach ($audios as $code => $audio) {
		  	//ee cc gv hg + 空中辅导 ＝》603  603=603
		  	if(strpos($keyword, $code) !==false || strpos($keyword, $audio['title']) !==false || $audio['index']==$keyword){
		  		$keyword = $audio['index'];//cc =>603
		  		$lyaudio = $audio;
		  		$lyaudio_code = $code;
		  		break;
		  	}
		  }
		  if(is_numeric($keyword) && ($keyword>600 && $keyword<=656) ) {
				$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' 每日更新';
		  	if($keyword>=641 && $keyword<=645){
		  		$title = $lyaudio['title'];
					$code = $lyaudio_code;
		  		$html = file_get_contents('http://txly2.net/'.$code);
		  		preg_match_all("/{file:'[^(')]+/", $html, $urls);
		  		preg_match_all("/',title:'[^(')]+/", $html, $titles);
		  		$index = 0;
		  		if(isset($urls[0][$index])){
		  			$musicurl = 'http://txly2.net'.str_replace("{file:'", '', $urls[0][$index]);
		  			return $resources['key_'.$keyword]= array(
							'type'	=>	'music',
							'cache'	=> 43200,
							'obj'		=> array(
								'title'	=> str_replace("',title:'", '', $titles[0][$index]).'♫'.$title,
								'desc'	=>	$desc,
								'musicurl'	=>	$musicurl,
								'hgmusicurl'	=>	$musicurl,
							),
						);
		  		}
					return $resources['key_'.$keyword]= array(
						'type'	=>	'text',
						'obj'		=> array(
							'text'	=> "ao出错啦，告诉小永吧回复反馈内容给永不止息即可。，良友圣经学院节目641-645改版中，请回复【#100】功能！",
						)
					);
		  	}
				if(date('N')>5&&$keyword=='612') {//【612】书香园地＝》【614】今夜心未眠
					$keyword = '614';
				}
				if(date('N')>5&&$keyword=='604') {//【604】炼爱季节＝》【605】幸福满家园
					$keyword = '605';
				}
				if(date('N')>5&&$keyword=='606') {//【606】亲情不断电＝》【605】幸福满家园
					$keyword = '605';
				}
				if(date('N')>5&&$keyword=='623') {//【623】齐来颂扬＝》【615】彩虹桥
					$keyword = '615';
				}
				if(date('N')<=5&&$keyword=='605') {//【605】幸福满家园=>【606】亲情不断电
					$keyword = '606';
				}

				if($keyword=='603'){
					$title = $lyaudio['title'];
					$code = $lyaudio_code;
					$offset=0;
					$date = date('ymd',time()-$offset*86400);
					$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
					$musicurl = $cdnlink.$path;//.upyun_get_token($path);
					// $temp = @get_headers($musicurl);
					// if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
					// $title = $title;
						$resources['key_'.$orikeyword]= array(
							'type'	=>	'music',
							// 'gakey'		=>	$keyword,
				      'gadata'   =>  array(
				         'category'        => 'liangyou',
				         'action'          => $title,
				         'label'           => 'wxservice_'.$account->uid,
				         'value'           => $keyword,
				      ),
							'path'	=>	$path,
							'cache' =>  43203,
							'custommessage'=>"2016年6月20日至30日，晚上7时至8时，《空中辅导》播出“第四届空中夫妻营”特辑。透过老师的教导，以及参加者的生命见证，让我们的家庭成就神的心意，同心荣耀神！由于播放特辑，空中辅导将会暂停直播，敬请留意。\n热线电话：13229966322 开放时段：星期二至四 19:00-20:00； 星期三 9:30-11:00 \n留言给周师母，请直接发送留言内容@163发给本号即可\n留言板：http://wx.yongbuzhixi.com/node/163 [拥抱][拳头]。\n辅导短信：13068410512\n点击关注留言公众号：http://dwz.cn/52ybzx",//20160424
							'obj'		=> array(
								'title'	=>  '【'.$keyword.'】'.$title.'♪',
								'desc'	=> $desc,
								'musicurl'	=>	$musicurl,
								'hgmusicurl'	=>	$musicurl,
							),
						);
						return $resources;
					// }
				}
				//USE UPYUN
				{
					if($lyaudio_code){
						$title = $lyaudio['title'];
						$code = $lyaudio_code;
						$offset=0;
						while ($offset <= 7) {
							$date = date('ymd',time()-$offset*86400);
							$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
							$musicurl = $cdnlink.$path;
							$upyunurl = $cdnlink.$path.upyun_get_token($path);
							$temp = @get_headers($upyunurl);
							if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
								$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").($offset?$date:' 每日更新');

								$file_key = drupal_realpath('public://cron/txly2/'.$code.'.json');
								if(file_exists($file_key))
									$descs = json_decode(file_get_contents($file_key),true);
								if(isset($descs['20'.$date])){
					        $custommessage = $descs['20'.$date];
					      }
								$resources['key_'.$orikeyword]= array(
									'type'	=>	'music',
									// 'gakey'		=>	$keyword,
						      'gadata'   =>  array(
						         'category'        => 'liangyou',
						         'action'          => $title,
						         'label'           => 'wxservice_'.$account->uid,
						         'value'           => $keyword,
						      ),
									'path'	=> $path,
									'cache'	=> 43201,
									'obj'		=> array(
										'title'	=>  '【'.$keyword.'】'.$title.'♪',
										'desc'	=> $desc,
										'musicurl'	=>	$musicurl,
										'hgmusicurl'	=>	$musicurl,
									),
								);
								if(isset($custommessage)){
									$resources['key_'.$orikeyword]['custommessage'] = '【'.$keyword.'】'.$title.'-'.$date."\n".$custommessage;
								}
								return $resources;
							}
							$offset++;
						}
					}
				}
		    //UPYUN END
		  }
	  }
	  //523
	  if(isset($enabled_resources['523']) && $enabled_resources['523'])
	 	if($keyword == '523'){
      $title = '在天父怀中';
      $str = date('md');
      //http://audio1.liangyou.net/files/media/ly_daily/2013Daily_130114.mp3
      // $musicurl = 'http://inhim.qiniudn.com/2013Daily_13'.$str.'.mp3';
      $musicurl = 'http://www.wxbible.net/wxapi/data/wxbible/audios/%E6%AF%8F%E6%97%A5%E7%81%B5%E4%BF%AE/%E5%9C%A8%E5%A4%A9%E7%88%B6%E6%80%80%E4%B8%AD/'.$str.'.mp3';
      $desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新 ".date('md');
      $url = $musicurl;
      $resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'cache'	=> 43200,
				'obj'		=> array(
					'title'	=> $title.'♫',
					'desc'	=>	$desc,
					'musicurl'	=>	$url,
					'hgmusicurl'	=>	$url,
				),
			);
			return $resources;
	 	}



    //圣经广播网 400-435
    if(isset($enabled_resources['400']) && $enabled_resources['400'])
    if(is_numeric($keyword) && ($keyword>=400 && $keyword<=435) ) {
    	// watchdog('mp_liangyou', '400', array(), WATCHDOG_NOTICE, 'link');
			return mp_bbn_response($keyword,$account, $weObj);
    }

 		if(isset($enabled_resources['1225']) && $enabled_resources['1225']){
	    //122501 http://www.ysqm.org/stream/ch-
	    if(substr($keyword, 0,4) == '1225' && strlen($keyword) ==6 ) {
	      require_once('ysqm.inc');
	      $str = substr($keyword, 4,6);
	      $str = str_pad($str%22,2,"0",STR_PAD_LEFT);
	      $ysqm = get_ysqm();
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';
	      $title = $ysqm[(int)$str];
	      $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 圣诞特辑《耶稣全貌》';
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'cache'	=> 43200,
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
				return $resources;
	    }
	    //122501 http://www.ysqm.org/stream/ch-
	    if($keyword == '1225') {
	      $str = str_pad(date('d')%22,2,"0",STR_PAD_LEFT);
	      require_once('ysqm.inc');
	      $ysqm = get_ysqm();
	      $title = $ysqm[(int)$str];
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';
	      $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 《耶稣全貌》';
	      $hgmusicurl = $musicurl;
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'cache'	=> 43200,
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
				return $resources;
	    }
 		}

 		// if(isset($enabled_resources['swty']) && $enabled_resources['swty']){
 		// 	if(substr($keyword, 0,2) == 'ty' || substr($keyword, 0,4) == 'swty' || $keyword == '世外桃源') {
	 	// 		require_once('swty.inc');
	 	// 		$resources['key_'.$keyword] = wx_swty_resource_response($keyword);
	 	// 	}
 		// }
 		// TO DO: DELETE!
 		require_once('liangyou.inc');
		//a1 b1 c1 d1 e1 f1-f9
		//begin lysd sd1-sd999
		$orikeyword = $keyword;
		$check_keyword = substr($keyword, 0,2);
		$index = substr($keyword, 2,3);
		if($check_keyword == 'sd'){
			$lysd = get_lysd();
			if($keyword == 'sd'){
				$mavmenu = "----良友礼品卡----\n";
				foreach ($lysd as $key => $value) {
					$mavmenu .= $key.' sd'.$value['begin'].'-sd'.$value['end']."\n";
				}
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'cache'	=> 0,
					'obj'		=> array(
					'text'	=> $mavmenu,
					)
				);
				return $resources;
			}
			if(is_numeric($index)){
				foreach ($lysd as $key => $value) {
					if($index>=$value['begin'] && $index<=$value['end']){
						$link = $value['title'].'/'.str_pad($index, 3,'0',STR_PAD_LEFT).'.mp3';

						// $etime = time()+3600; // 授权十分钟后过期
						// $key = 'ly729';   // token 防盗链密钥
						$path = '/lysd/'.$link; // 图片相对路径
						// $sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;
						//http://audio.yongbuzhixi.com/lysd/001.mp3
						$link = 'http://audio.yongbuzhixi.com/lysd/'.urlencode($link);//.'?_upt='.$sign;

						$resources['key_'.$orikeyword]= array(
							'type'	=>	'music',
							'cache'	=> 0,
							'path'	=> $path,
							'obj'		=> array(
								'title'	=> $value['title'],
								'desc'	=>	"良友礼品卡 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 点击►收听",
								'musicurl'	=>	$link,
								'hgmusicurl'	=>	$link,
							),
						);
						return $resources;break;
					}
				}
			}
		}

	}
	return $resources;
}

/**
 * $change_keyword = return key!
 */
function mp_bbn_response($keyword,$account,$weObj) {
  $text = "弟兄姊妹，平安，【400】开头的圣经广播网节目系统维护中，谢谢代祷！\n永不止息，需要有你[握手]\n请回复【600】收听其他节目，";
	$resources = array();$resources['key_'.$keyword]= array(
		'type'	=>	'text',
		'cache' =>  0,
		'gadata'   =>  array(
       'category'        => '400',
       'action'          => $keyword,
       'label'           => 'wxservice_'.$account->uid,
    ),
		'obj'		=> array(
			'text'	=> $text,
		),
	);
	return $resources;
	$change_keyword = $keyword;
	require_once('bbn.inc');
 	if($keyword == '400'){
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'text',
			'cache' =>  0,
			'obj'		=> array(
				'text'	=> bbn_audio_menu(),
			)
		);
 	}else{
		$bbn = mp_get_bbn($keyword);
		$musicurl = $bbn[$keyword]['musicurl'];
		$title = $bbn[$keyword]['title'];
		$desc = '点击►收听 公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 每日更新';
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'music',
			'cache' =>  43200,
			'obj'		=> array(
				'title'	=> $title,
				'desc'	=>	$desc,
				'musicurl'	=>	$musicurl,
				'hgmusicurl'	=>	$musicurl,
			),
		);
		if(date('G')<11) {
			$resources['key_'.$change_keyword]['custommessage'] = "弟兄姊妹，平安，圣经广播网4开头节目于每早11点更新，请11点后点击播放即可，谢谢代祷推荐给亲朋好友\n永不止息，需要有你[握手]";
	  }
	}
	return $resources;
}

// 图片相对路径
// token 防盗链密钥
// 授权1分钟后过期
// 图片相对路径
// token 防盗链密钥
// 授权1分钟后过期
function upyun_get_token($path, $etime = 86400, $key = 'ly729'){
	$etime = time()+$etime; // 授权1分钟后过期
	return '?_upt='. substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;
}
