<?php
/**
 * hook_rescources_info
 */
function mp_liangyou_rescources_info(){
	$rescources[] = array(
    'name' => 'ly',
    'desc' =>	'良友广播【ly】',
  );
	$rescources[] = array(
    'name' => 'ly2',
    'desc' =>	'良友广播【600】',
  );
	$rescources[] = array(
    'name' => '365',
    'desc' =>	'恩典365【365】【366】',
  );
	$rescources[] = array(
    'name' => '523',
    'desc' =>	'在天父怀中【523】',
  );
	$rescources[] = array(
    'name' => '400',
    'desc' =>	'圣经广播网【400】',
  );
	$rescources[] = array(
    'name' => '1225',
    'desc' =>	'耶稣全貌【1225】',
  );
	$rescources[] = array(
    'name' => 'swty',
    'desc' =>	'世外桃源【ty】',
  );
	$rescources[] = array(
    'name' => 'mav',
    'desc' =>	'良友圣经学院【a0】-【f0】',
  );
  return $rescources;
}

/**
 * hook_wxrescources
 */
function mp_liangyou_wxresources($resources, $account, $keyword){
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
	// watchdog('mp_liangyoukeyword', $keyword, array(), WATCHDOG_NOTICE, 'link');
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
  	//ee bv se gv
	  if(isset($enabled_resources['ly']) && $enabled_resources['ly']){
		  require_once('liangyou.inc');
		 	if($keyword == 'ly' || $keyword == '良友' ){
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
						'text'	=> ly_get_menu(),
					)
				);
				return $resources;
		 	}
		  $radios_list = liangyou_audio_list();
		  $radios_keys = array_keys($radios_list);
			// bc1
		  $key = substr($keyword, 0,2); 
		  if(in_array($key, $radios_keys)) {
		    $offset = 0;
		    if(strlen($keyword)>2) {
		      $offset = substr($keyword, 2,1);
		      if(!is_numeric($offset)) $offset = 0;
		    }
		    //se->bf
		    if ($key=='se' && $offset == 0 && date('N')>5) {
		    	$key = 'bf';
		    }
		    if($key=='bv') $key='mw';
		    if ($key=='bf' && $offset == 0 && date('N')<=5) {
		    	$keyword = '416';
		    	return mp_bbn_response($keyword,$key);
		    }
		    //6,7播出的节目
		    if (isset($radios_list[$key]['day']) && $radios_list[$key]['day']=='6' && $offset == 0 && date('N')<=5) {
		    	$offset = date('N')%2+1;
		    }
		    $string = date('ymd',time()-$offset*24*60*60); 
		    $desc = '公众号:永不止息 更多节目请回复【ly】';
		    $url = $radios_list[$key]['prefix'].$key.'/'.$key.$string.'.mp3';
		  	$resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $radios_list[$key]['name'],
						'desc'	=>	$desc,
						'musicurl'	=>	$url,
						'hgmusicurl'	=>	$url,
					),
				);
			}
	  }

		// 600-652 stream ly
	  if(isset($enabled_resources['ly2']) && $enabled_resources['ly2']){
		  require_once('liangyou.inc');
		 	if($keyword == 'ly2' || $keyword == '良友2'){
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
					'text'	=> ly_stream_menu(),
					)
				);
		 	}
		  if(is_numeric($keyword) && ($keyword>=600 && $keyword<=652) ) {
		    // $file_key = 'http://ly.yongbuzhixi.com/cron/cloud/'.date('Ymd').'.json'; 
		    date_default_timezone_set('Asia/Shanghai');
		    $file_key = dirname(__FILE__).'/'.date('Ymd').'.json';
		    if(!file_exists($file_key))  {
					$radios = ly_stream_source();
					foreach ($radios as $key => $radio) {
					  $url = $radio['url'];
					  $title = $radio['title'];

					  $html = file_get_html($url);
					  if(!$html) { 
					  	watchdog('mp_liangyou', 'lost audio:'.$title, array(), WATCHDOG_NOTICE, 'error');
					  	continue;
					  }
					  $url = $html->find('#div_playlist li', 0);

					  $title_get = $html->find('#div_playlist li .mp3_title', 0)->plaintext;
					  $mp3_description = $html->find('#div_playlist li .mp3_description', 0)->plaintext;
					  $dates = explode('-', $title_get);
					  $data[] = array(
					    'title' => $title,
					    'date' => $dates[1],
					    'url'   =>  $url->attr['data-stream'],
					    'desc'  => $mp3_description,
					    );
					  // break;
					}
					// var_dump($data);
					$file = json_encode($data);
					if(!is_null($file)){
					  file_put_contents( $file_key , $file );
					  $file_key = dirname(__FILE__).'/'.date('Ymd',time()-86400).'.json';
					  if(file_exists($file_key))
					  	unlink($file_key);
					  // watchdog('mp_liangyou', 'Success download ly audio list from stream', array(), WATCHDOG_NOTICE, 'link');
					}
				}

		    $file = file_get_contents($file_key);
		    $urls = json_decode($file,TRUE);
		    if($keyword == 600){
		     	$resources['key_'.$keyword] = array(
						'type'	=>	'text',
						'obj'		=> array(
						'text'	=> ly_stream_menu(),
						)
					);
		    }else{	    	
			    $before_keyword = $keyword;
			    $keyword = $keyword - 601;
			    // watchdog('keyword '.$before_keyword , $keyword, array(), WATCHDOG_NOTICE, 'link');
			    $title = str_replace($keyword, '', $urls[$keyword]['title']);
			    $musicurl = $urls[$keyword]['url'].'?='.$urls[$keyword]['date'].'.mp3';
			    $desc =  substr($urls[$keyword]['date'], 4).' '.truncate_utf8($urls[$keyword]['desc'], 16, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);
			    $resources['key_'.$before_keyword]= array(
						'type'	=>	'music',
						'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
						),
					);
					// watchdog('resources ', print_r($resources,TRUE), array(), WATCHDOG_NOTICE, 'link');
		    }
		  }
	  }
	  //523
	  if(isset($enabled_resources['523']) && $enabled_resources['523'])
	 	if($keyword == '523'){
	      $title = '在天父怀中';
	      $str = date('md');
	      //http://audio1.liangyou.net/files/media/ly_daily/2013Daily_130114.mp3
	      $musicurl = 'http://inhim.qiniudn.com/2013Daily_13'.$str.'.mp3';
	      $desc = "点击►收听 服务号:永不止息 每日更新 ".date('md');
	      $url = $musicurl;
	      $resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'obj'		=> array(
					'title'	=> $title,
					'desc'	=>	$desc,
					'musicurl'	=>	$url,
					'hgmusicurl'	=>	$url,
				),
			);
	 	}

	  //365||366
	  $check_word = substr($keyword, 0,3);
	  if(isset($enabled_resources['365']) && $enabled_resources['365'])
	  if($check_word == '365' || $check_word == '366' ) {
	    $str = date('md');
	    if (strlen($keyword) ==7) {
	      $str = substr($keyword, 3,5);//0430
	      $month = (int) substr($str, 0,2);
	    }
	    $title = "恩典365";// '【'.$check_word.'】'.
	    $year = ($check_word=='365')?'2013':'2014';
	    $url = 'http://grace365.qiniudn.com/'.$year.'/'.$str.'.mp3';
	    $desc = "点击►收听 服务号:永不止息 每日更新";
	    $resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'obj'		=> array(
					'title'	=> $title,
					'desc'	=>	$desc,
					'musicurl'	=>	$url,
					'hgmusicurl'	=>	$url,
				),
			);
	  }



    //圣经广播网 400-435
    if(isset($enabled_resources['400']) && $enabled_resources['400'])
    if(is_numeric($keyword) && ($keyword>=400 && $keyword<=435) ) {
    	$resources = mp_bbn_response($keyword);
    }

 		if(isset($enabled_resources['1225']) && $enabled_resources['1225']){
	    //122501 http://www.ysqm.org/stream/ch-
	    if(substr($keyword, 0,4) == '1225' && strlen($keyword) ==6 ) {
	      require_once('ysqm.inc');
	      $str = substr($keyword, 4,6);
	      $str = str_pad($str%22,2,"0",STR_PAD_LEFT);
	      $ysqm = get_ysqm();
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';
	      $title = $ysqm[(int)$str];
	      $desc = '公众号:永不止息 圣诞特辑《耶稣全貌》';
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
	    }
	    //122501 http://www.ysqm.org/stream/ch-
	    if($keyword == '1225') {
	      $str = str_pad(date('d')%22,2,"0",STR_PAD_LEFT);
	      require_once('ysqm.inc');
	      $ysqm = get_ysqm();
	      $title = $ysqm[(int)$str];
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';        
	      $desc = '公众号:永不止息 《耶稣全貌》';
	      $hgmusicurl = $musicurl;
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
	    }
 		}

 		if(isset($enabled_resources['swty']) && $enabled_resources['swty']){
 			if(substr($keyword, 0,2) == 'ty' || substr($keyword, 0,4) == 'swty' || $keyword == '世外桃源') {
	 			require_once('swty.inc');
	 			$resources['key_'.$keyword] = wx_swty_resource_response($keyword);
	 		}
 		}
		//a1 b1 c1 d1 e1 f1-f9
		if(isset($enabled_resources['mav']) && $enabled_resources['mav']){
			// $keyword = 'd11';
			$first = substr($keyword, 0,1);
			$second = substr($keyword, 1,1);
			$temp = array('a','b','c','d','e','f');
			if(in_array($first, $temp) && $second>0 && $second<10 ){
				$third = substr($keyword, 2,2);
				$mav = get_ly_mav();
				$mav = $mav[$first.$second];
				if($third>0&&$third<$mav['count']){
					//24 => 001
					$count = $mav['count'];

					$rep = str_pad($third, 2,'0',STR_PAD_LEFT);
					$link = str_replace("$count", str_pad($third, 2,'0',STR_PAD_LEFT), $mav['link']);
					$link = 'http://liangyou.u.qiniudn.com/old/'.urlencode($link);
					$resources['key_'.$keyword]= array(
						'type'	=>	'music',
						'obj'		=> array(
							'title'	=> $mav['title'],
							'desc'	=>	"良友圣经学院 服务号:永不止息 点击►收听",
							'musicurl'	=>	$link,
							'hgmusicurl'	=>	$link,
						),
					);
				}else{
					//编码对，编号不对！
					$resources['key_'.$keyword]= array(
						'type'	=>	'text',
						'obj'		=> array(
							'text'	=> "[大哭]编码对，数字不对！",
						)
					);
				}
			}else{// a0 b0 c0 d0 e0 f0 
				$menu = array('a0','b0','c0','d0','e0','f0');
				$temp_keyword = substr($keyword, 0,2);
				$first = substr($keyword, 0,1);
				if(in_array($temp_keyword, $menu)){
					$mav = get_ly_mav();
					$mavmenu = '良友圣经学院课程目录'.$first."\n";
					foreach ($mav as $key => $value) {
						if(strpos($key,$first) !== false){
							$mavmenu .= "【".$key."】".$value['title']."\n";
						}
					}
					$mavmenu .="回复【".$first."11】，即可获得第一课[强]";
					$resources['key_'.$keyword]= array(
						'type'	=>	'text',
						'obj'		=> array(
						'text'	=> $mavmenu,
						)
					);
				}
			}
		}//end of 良友圣经学院
		//begin lysd sd1-sd999
		$orikeyword = $keyword;
		$check_keyword = substr($keyword, 0,2);
		$index = substr($keyword, 2,3);
		if($check_keyword == 'sd'){
			$lysd = get_lysd();
			if($keyword = 'sd'){
				$mavmenu = "目录\n";
				foreach ($lysd as $key => $value) {
					$mavmenu .= $key.' sd'.$value['begin'].'-sd'.$value['end']."\n";
				}
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
					'text'	=> $mavmenu,
					)
				);
			}
			if(is_numeric($index)){
				foreach ($lysd as $key => $value) {
					if($index>=$value['begin'] && $index<=$value['end']){
						$link = $value['title'].'/'.str_pad($index, 3,'0',STR_PAD_LEFT).'.mp3';
						$link = 'http://ly729.b0.upaiyun.com/lysd/'.urlencode($link);
						$resources['key_'.$orikeyword]= array(
							'type'	=>	'music',
							'obj'		=> array(
								'title'	=> $value['title'],
								'desc'	=>	"良友圣经学院 服务号:永不止息 点击►收听",
								'musicurl'	=>	$link,
								'hgmusicurl'	=>	$link,
							),
						);
						break;
					}
				}
			}
		}
		//begin bos
 		date_default_timezone_set('Asia/Shanghai');
 		if(substr($keyword, 0,6) == '目录'){
			$file_key = 'http://729ly.bj.bcebos.com/home/bae/app/cron/nzzlist/'.date('Ymd').'.json';
			if(@get_headers($file_key)[0] == 'HTTP/1.1 404 Not Found'){
				$file_key = 'http://ly.yongbuzhixi.com/cron/nzzlist/'.date('Ymd').'.json';
			}
 			$file = file_get_contents($file_key);
			$urls = json_decode($file,TRUE);
			$menu = "回复【】内的汉字，即可获得响应节目[调皮]\n";
			foreach ($urls as $key => $value) {
				if(isset($value['bce']))
					$menu .= '【'.$value['title']."】\n";
			}
			$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
						'text'	=> $menu,
					)
			);
 		}
 		if(!isset($resources)){
			$file_key = 'http://729ly.bj.bcebos.com/home/bae/app/cron/nzzlist/'.date('Ymd').'.json';
			if(@get_headers($file_key)[0] == 'HTTP/1.1 404 Not Found'){
				$file_key = 'http://ly.yongbuzhixi.com/cron/nzzlist/'.date('Ymd').'.json';
			}
 			$file = file_get_contents($file_key);
			$urls = json_decode($file,TRUE);
			if(count($urls))
			foreach ($urls as $key => $value) {
				if($value['title'] ==$keyword){
					$resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $value['title'],
						'desc'	=>	"点击►收听 服务号:永不止息 每日更新",
						'musicurl'	=>	'http://bos.yongbuzhixi.com'.$value['bce'],//bce gprs
						'hgmusicurl'	=>	'http://bos.yongbuzhixi.com'.$value['bce'],//$value['mp3_link'], //wifi  http://liangyou2.nissigz.com:15200/vhh/vhh151012.mp3
					),
				);
					break;
				}
			}
 		}//end bos

	}
	return $resources;
}

/**
 * $change_keyword = return key!
 */
function mp_bbn_response($keyword,$change_keyword=NULL){
	$resources = array();
	if (!$change_keyword) {
		$change_keyword = $keyword;
	}
	require_once('bbn.inc');
 	if($keyword == '400'){
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'text',
			'obj'		=> array(
			'text'	=> bbn_audio_menu(),
			)
		);
 	}else{
		$musicurl = bbn_url($keyword);
		$bbns = bbn_audio_list();
		$title = $bbns[$keyword]['title'];
		$desc = '点击►收听 公众号:永不止息 '.truncate_utf8($bbns[$keyword]['description'], 12, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'music',
			'obj'		=> array(
				'title'	=> $title,
				'desc'	=>	$desc,
				'musicurl'	=>	$musicurl,
				'hgmusicurl'	=>	$musicurl,
			),
		);
	}
	return $resources;
}