<?php
$upyun_bucket_name = 'lywxaudio';
$cdnlink = $upyun_bucket_name.'.b0.upaiyun.com';
/**
 * hook_rescources_info
 */
function mp_liangyou_rescources_info(){
	// $rescources[] = array(
 //    'name' => 'ly',
 //    'desc' =>	'良友电台线路1【ly】',
 //  );
	$rescources[] = array(
    'name' => 'ly2',
    'desc' =>	'良友电台【600】',
  );
	$rescources[] = array(
    'name' => '365',
    'desc' =>	'恩典【365】【366】',
  );
	$rescources[] = array(
    'name' => '523',
    'desc' =>	'在天父怀中【523】',
  );
	$rescources[] = array(
    'name' => '400',
    'desc' =>	'圣经广播网【400】',
  );
	$rescources[] = array(
    'name' => '1225',
    'desc' =>	'耶稣全貌【1225】',
  );
	// $rescources[] = array(
 //    'name' => 'swty',
 //    'desc' =>	'世外桃源【ty】',
 //  );
	$rescources[] = array(
    'name' => 'mav',
    'desc' =>	'良友圣经学院【a0】~【g0】',
  );
	$rescources[] = array(
    'name' => 'jckc',
    'desc' =>	'良院基础课程【jc】',
  );
  return $rescources;
}

/**
 * hook_wxrescources
 */
function mp_liangyou_wxresources($resources, $account, $keyword){
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
	// watchdog('mp_liangyoukeyword', $keyword, array(), WATCHDOG_NOTICE, 'link');
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
  	//ee bv se gv
	  if(1||(isset($enabled_resources['ly']) && $enabled_resources['ly'])){
		  require_once('liangyou.inc');
		 	if($keyword == 'ly' || $keyword == '良友' ){
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
						'text'	=> ly_get_menu(),
					)
				);
				return $resources;
		 	}
		  $radios_list = liangyou_audio_list();
		  $radios_keys = array_keys($radios_list);
			// bc1
		  $key = substr($keyword, 0,2); 
		  if(in_array($key, $radios_keys)) {
		    $offset = 0;
		    if(strlen($keyword)>2) {
		      $offset = substr($keyword, 2,1);
		      if(!is_numeric($offset)) $offset = 0;
		    }
		    //se->bf
		    if ($key=='se' && $offset == 0 && date('N')>5) {
		    	$key = 'bf';
		    }
		    if ($key=='bc' && $offset == 0 && date('N')>5) {
		    	$key = 'rt';
		    }
		    if($key=='bv') $key='mw';
		    if($key=='cc' && $offset == 0) $offset=1;
	    	// if($key=='603') $keyword='cc1';
		    if ($key=='bf' && $offset == 0 && date('N')<=5) {
		    	$keyword = '416';
		    	return mp_bbn_response($keyword,$account,$key);
		    }
		    //6,7播出的节目
		    if (isset($radios_list[$key]['day']) && $radios_list[$key]['day']=='67' && $offset == 0 && date('N')<=5) {
		    	$offset = date('N');
		    }
		    //7周日播出
		    if (isset($radios_list[$key]['day']) && $radios_list[$key]['day']=='7' && $offset == 0 && date('N')<=6) {
		    	$offset = date('N');
		    }
		    //周1-5播出
		    if (isset($radios_list[$key]['day']) && $radios_list[$key]['day']=='5' && $offset == 0 && date('N')>=6) {
		    	$offset = date('N')%2+1;
		    }

		    $string = date('ymd',time()-$offset*24*60*60); 
		    $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 更多节目请回复【600】';
		    $url = $radios_list[$key]['prefix'].$key.'/'.$key.$string.'.mp3';
		    //USE UPYUN
	 if(0){
		 			$file_key = 'http://ly.yongbuzhixi.com/cron/nissigz/json/'.date('Ym').'/'.date('Ymd') . '.json';
					$getheaders = @get_headers($file_key);
					if(isset($getheaders)&&$getheaders[0] == 'HTTP/1.1 404 Not Found'){
						//do nothing!
					}else{
						require_once('liangyou_audio_list.php');
						$liangyou_audio_list = liangyou_audio_list2();
						$liangyou_audio_list_info = $liangyou_audio_list[$key];
						$title = $liangyou_audio_list_info['title'];
						$code = $key;

						$dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');
	          $objectKey = '/'.$dir_stru .'/'.$code. date('ymd').'.mp3';
	          $bce_url = '/liangyou/nissigz/'.urlencode($title).'/'.date('Ym').'/'.$code.date('ymd').'.mp3';
	          $musicurl = 'http://'.$cdnlink.$bce_url.upyun_get_token($objectKey);
	          $temp = @get_headers($musicurl);
	          if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
								$resources['key_'.$keyword]= array(
									'type'	=>	'music',
									'obj'		=> array(
										'title'	=> $title.'♪',
										'desc'	=>	"点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新",
										'musicurl'	=>	$musicurl,
										'hgmusicurl'	=>	$musicurl,
									),
								);
								return $resources;
	          }
					}
		    }//UPYUN END
		  	$resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $radios_list[$key]['name'],
						'desc'	=>	$desc,
						'musicurl'	=>	$url,
						'hgmusicurl'	=>	$url,
					),
				);
			}
	  }

		// 600-652 stream ly
	  if(isset($enabled_resources['ly2']) && $enabled_resources['ly2']){
		  require_once('liangyou.inc');
		  if(is_numeric($keyword) && ($keyword>=600 && $keyword<=652) ) {
				$orikeyword = $keyword;
				if(date('N')>5&&$keyword=='612') {//【612】书香园地＝》【614】今夜心未眠
					$keyword = '614';
				}
				if(date('N')>5&&$keyword=='606') {//【606】亲情不断电＝》【605】幸福满家园
					$keyword = '605';
				}
				if(date('N')>5&&$keyword=='609') {//【609】微播出炉=>【610】生活无国界
					$keyword = '610';
				}
				if(date('N')>5&&$keyword=='619') {//【619】拥抱每一天=>【652】燃亮的一生
					$keyword = '652';
				}
				if(date('N')>5&&$keyword=='623') {//【623】齐来颂扬＝》【615】彩虹桥
					$keyword = '615';
				}
				if(date('N')>5&&$keyword=='608') {//【608】绝妙当家＝》【610】生活无国界
					$keyword = '610';
				}
				if(date('N')<=5&&$keyword=='605') {//【605】幸福满家园=>【606】亲情不断电
					$keyword = '606';
				}
				
		     //USE UPYUN
		if(0){
		 			$file_key = 'http://ly.yongbuzhixi.com/cron/nissigz/json/'.date('Ym').'/'.date('Ymd') . '.json';
					$getheaders = @get_headers($file_key);
					if(isset($getheaders)&&$getheaders[0] == 'HTTP/1.1 404 Not Found'){
						//do nothing!
					}else{
						
						require_once('liangyou_audio_list.php');
						$liangyou_audio_list = liangyou_audio_list_byindex();
						if(isset($liangyou_audio_list[$keyword])){

							$liangyou_audio_list_info = $liangyou_audio_list[$keyword];
							$title = $liangyou_audio_list_info['title'];
							$code = $liangyou_audio_list_info['code'];

							$dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');
		          $objectKey = '/'.$dir_stru .'/'.$code. date('ymd').'.mp3';
		          $bce_url = '/liangyou/nissigz/'.urlencode($title).'/'.date('Ym').'/'.$code.date('ymd').'.mp3';
		          $musicurl = 'http://'.$cdnlink.$bce_url.upyun_get_token($objectKey);

		          $temp = @get_headers($musicurl);
		          if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
									$resources['key_'.$orikeyword]= array(
										'type'	=>	'music',
										'obj'		=> array(
											'title'	=> $title.'♪',
											'desc'	=>	"点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新",
											'musicurl'	=>	$musicurl,
											'hgmusicurl'	=>	$musicurl,
										),
									);
									return $resources;
		          }
						}
					}
		    }//UPYUN END
		    $file_path = DRUPAL_ROOT.'/sites/default/files/cron/lycloudjson/';
		    if (!is_dir($file_path)) {
		      mkdir($file_path, 0777, true);
		    }
		    // $file_key = dirname(__FILE__).'/'.date('Ymd').'.json';
		    $file_key = drupal_realpath('public://cron/lycloudjson/'.date('Ymd').'.json') ;
		    if(!file_exists($file_key))  {
					$radios = ly_stream_source();
					foreach ($radios as $key => $radio) {
					  // $url = $radio['url'];
					  // $title = $radio['title'];
					  $url = $radio;
					  $title = $key;

					  $html = file_get_html($url);
					  if(!$html) { 
					  	watchdog('mp_liangyou', 'lost audio:'.$title, array(), WATCHDOG_NOTICE, 'error');
					  	continue;
					  }
					  $url = $html->find('#div_playlist li', 0);

					  $title_get = $html->find('#div_playlist li .mp3_title', 0)->plaintext;
					  $mp3_description = $html->find('#div_playlist li .mp3_description', 0)->plaintext;
					  $dates = explode('-', $title_get);
					  $data[] = array(
					    'title' => $title,
					    'date' => $dates[1],
					    'url'   =>  $url->attr['data-stream'],
					    'desc'  => $mp3_description,
					    );
					  // break;
					}
					// var_dump($data);
					$file = json_encode($data);
					if(!is_null($file)){
					  file_put_contents( $file_key , $file );
					  // $file_key = dirname(__FILE__).'/'.date('Ymd',time()-86400).'.json';
					  // if(file_exists($file_key))
					  // 	unlink($file_key);
					  // watchdog('mp_liangyou', 'Success download ly audio list from stream', array(), WATCHDOG_NOTICE, 'link');
					}
				}

		    $file = file_get_contents($file_key);
		    $urls = json_decode($file,TRUE);
		    if($keyword == 600){
		     	$resources['key_'.$keyword] = array(
						'type'	=>	'text',
						'obj'		=> array(
						'text'	=> ly_stream_menu(),
						)
					);
		    }else{	    	
			    // $before_keyword = $keyword;
			    $keyword = $orikeyword - 601;
			    // watchdog('keyword '.$before_keyword , $keyword, array(), WATCHDOG_NOTICE, 'link');
			    $title = str_replace($keyword, '', $urls[$keyword]['title']);
			    $musicurl = $urls[$keyword]['url'].'?='.$urls[$keyword]['date'].'.mp3';
			    $desc =  substr($urls[$keyword]['date'], 4).' '.truncate_utf8($urls[$keyword]['desc'], 16, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);
			    $resources['key_'.$orikeyword]= array(
						'type'	=>	'music',
						'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
						),
					);
					// watchdog('resources ', print_r($resources,TRUE), array(), WATCHDOG_NOTICE, 'link');
		    }
		  }
	  }
	  //523
	  if(isset($enabled_resources['523']) && $enabled_resources['523'])
	 	if($keyword == '523'){
	      $title = '在天父怀中';
	      $str = date('md');
	      //http://audio1.liangyou.net/files/media/ly_daily/2013Daily_130114.mp3
	      $musicurl = 'http://inhim.qiniudn.com/2013Daily_13'.$str.'.mp3';
	      $desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新 ".date('md');
	      $url = $musicurl;
	      $resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'obj'		=> array(
					'title'	=> $title.'♫',
					'desc'	=>	$desc,
					'musicurl'	=>	$url,
					'hgmusicurl'	=>	$url,
				),
			);
	 	}

	  //365||366
	  $check_word = substr($keyword, 0,3);
	  if(isset($enabled_resources['365']) && $enabled_resources['365'])
	  if($check_word == '365' || $check_word == '366' ) {
	    $str = date('md');
	    if (strlen($keyword) ==7) {
	      $str = substr($keyword, 3,5);//0430
	      $month = (int) substr($str, 0,2);
	    }
	    $title = "恩典365";// '【'.$check_word.'】'.
	    $year = ($check_word=='365')?'2013':'2014';
	    $url = 'http://grace365.qiniudn.com/'.$year.'/'.$str.'.mp3';
	    $desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新";
	    $resources['key_'.$keyword]= array(
				'type'	=>	'music',
				'obj'		=> array(
					'title'	=> $title.'♫',
					'desc'	=>	$desc,
					'musicurl'	=>	$url,
					'hgmusicurl'	=>	$url,
				),
			);
	  }



    //圣经广播网 400-435
    if(isset($enabled_resources['400']) && $enabled_resources['400'])
    if(is_numeric($keyword) && ($keyword>=400 && $keyword<=435) ) {
    	$resources = mp_bbn_response($keyword,$account);
    }

 		if(isset($enabled_resources['1225']) && $enabled_resources['1225']){
	    //122501 http://www.ysqm.org/stream/ch-
	    if(substr($keyword, 0,4) == '1225' && strlen($keyword) ==6 ) {
	      require_once('ysqm.inc');
	      $str = substr($keyword, 4,6);
	      $str = str_pad($str%22,2,"0",STR_PAD_LEFT);
	      $ysqm = get_ysqm();
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';
	      $title = $ysqm[(int)$str];
	      $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 圣诞特辑《耶稣全貌》';
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
	    }
	    //122501 http://www.ysqm.org/stream/ch-
	    if($keyword == '1225') {
	      $str = str_pad(date('d')%22,2,"0",STR_PAD_LEFT);
	      require_once('ysqm.inc');
	      $ysqm = get_ysqm();
	      $title = $ysqm[(int)$str];
	      $musicurl = 'http://bibles.qiniudn.com/ysqm/ch-'.$str.'.mp3';        
	      $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 《耶稣全貌》';
	      $hgmusicurl = $musicurl;
	      $resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $title,
						'desc'	=>	$desc,
						'musicurl'	=>	$musicurl,
						'hgmusicurl'	=>	$musicurl,
					),
				);
	    }
 		}

 		if(isset($enabled_resources['swty']) && $enabled_resources['swty']){
 			if(substr($keyword, 0,2) == 'ty' || substr($keyword, 0,4) == 'swty' || $keyword == '世外桃源') {
	 			require_once('swty.inc');
	 			$resources['key_'.$keyword] = wx_swty_resource_response($keyword);
	 		}
 		}
		//a1 b1 c1 d1 e1 f1-f9

		if(isset($enabled_resources['mav']) && $enabled_resources['mav']){
			// $keyword = 'd11';
			$first = substr($keyword, 0,1);
			$second = substr($keyword, 1,1);
			$temp = array('a','b','c','d','e','f','g');
			if(in_array($first, $temp) && $second>0 && $second<10 ){
				$third = substr($keyword, 2,2);
				$mav = get_ly_mav();
				if(isset($mav[$first.$second])){
					$mav = $mav[$first.$second];
				}else{
					return $resources['key_'.$keyword]= array(
							'type'	=>	'text',
							'obj'		=> array(
								'text'	=> "[大哭]编码有误，请回复a0、b0、c0...f0查看目录哦！",
							)
						);
				}
				$level = (($mav['level'] == 1)?'本科课程':'进深课程');
				if($third>0&&$third<=$mav['count']){
					//24 => 001
					$count = $mav['count'];
					if($count<9)
						$count = '0'.$count;
					$rep = str_pad($third, 2,'0',STR_PAD_LEFT);
					$link = 'new/'.$level.'/'.$mav['title'].'/'.$mav['prefex'].$rep.'.mp3';	
					
					$etime = time()+3600; // 授权十分钟后过期
					$key = 'ly729';   // token 防盗链密钥
					$path = '/'.$link; // 图片相对路径
					$sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;

					$cdn = 'http://lts33.b0.upaiyun.com/';
					$link = $cdn . urlencode($link).'?_upt='.$sign;
					$resources['key_'.$keyword]= array(
						'type'	=>	'music',
						'obj'		=> array(
							'title'	=> $mav['title'].'-'.$rep,
							'desc'	=>	"良友圣经学院 ".$level." 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 点击►收听",
							'musicurl'	=>	$link,
							'hgmusicurl'	=>	$link,
						),
					);
				}else{
					//编码对，编号不对！
					$path = 'new/'.$level.'/'.$mav['title'].'/'.$mav['title'].'.pdf';
					$cdn = 'http://lts33.b0.upaiyun.com/';
					

					$etime = time()+864000; // 授权十天后过期
					$key = 'ly729';   // token 防盗链密钥
					$path = '/'.$path; // 图片相对路径
					$sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;

					$link = $cdn . urlencode($path).'?_upt='.$sign;

					if($mav['pdf']>0){
						$resources['key_'.$keyword]= array(
							'type'	=>	'text',
							'obj'		=> array(
								'text'	=> "恭喜您，良院 $level 《".$mav['title']."》已结束！\n回复".$first.($second+1)."1学习下一门课程[强]\n".'<a href="http://ly.yongbuzhixi.com/pdfviewer/web/?pdf='.$link.'&q='.time().'">查看'.$mav['title'].'讲义</a>',
							)
						);
					}else{
						$resources['key_'.$keyword]= array(
							'type'	=>	'text',
							'obj'		=> array(
								'text'	=> "[大哭]本科没有讲义哦！",
							)
						);
					}
				}
			}else{
				$menu = array('a0','b0','c0','d0','e0','f0','g0');
				$temp_keyword = substr($keyword, 0,2);
				$first = substr($keyword, 0,1);
				if(in_array($temp_keyword, $menu)){
					$mav = get_ly_mav();
					if(in_array($temp_keyword, array('e0','f0','g0'))){
						$level = '进深';
					}else{
						$level = '本科';
					}
					$mavmenu = '良院'.$level.'文凭课程目录'.$first."\n";
					foreach ($mav as $key => $value) {
						if(strpos($key,$first) !== false){
							$mavmenu .= "【".$key."】".$value['title']."\n";
						}
					}
					$mavmenu .="回复【".$first."11】，即可获得第一课[强]";
					$resources['key_'.$keyword]= array(
						'type'	=>	'text',
						'obj'		=> array(
						'text'	=> $mavmenu,
						)
					);
				}
			}
		}//end of 良友圣经学院
		//x0 y0 z0
		// 		阮老师，我在设计新的良院编码，这样可以吗？：
		// 用户回复【基础课程】或【jckc】可得到基础课程8科按顺序排列的节目，8*24+1(pdf)=200天循环一次。
		// 每个科目，比如事奉装备，用户回复【事奉装备】或【sfzb】获得当天节目，25天一循环，收听14课可以回复【sfzb14】
		//begin new 良友圣经学院
	if(isset($enabled_resources['jckc']) && $enabled_resources['jckc']){
		if($keyword == '基础' || $keyword == 'jc'){
			$mav = get_ly_jckc();
			$mavmenu = "良院基础课程目录\n";
			foreach ($mav as $key => $value) {
				$mavmenu .= "【J".$value['order']."】".$value['title']."\n";//"【".strtoupper($key)."】".
			}
			$mavmenu .="回复【J11】，即可获得第一课[强]";
			$resources['key_'.$keyword]= array(
				'type'	=>	'text',
				'obj'		=> array(
				'text'	=> $mavmenu,
				)
			);
		}

		$temp_keyword = $keyword;
		if($keyword == '基础课程' || $keyword == 'jckc'){
			$index_day = date('z');
			$total = 25;
			$index1 = $index_day%200;//200天一循环！
			// dvm($index1);
			// dvm($index1%25,'课');
			// dvm(ceil($index1/25),'单元');
			$course_id = $index1%$total;//课
			$course_index = ceil($index1/$total);//单元
			$temp_keyword = 'j'.$course_index.$course_id;//326 j1514
			// watchdog('course_id', $course_id, array(), WATCHDOG_NOTICE, 'link');
			// watchdog('course_index', $course_index, array(), WATCHDOG_NOTICE, 'link');
			// watchdog('keyword', $keyword, array(), WATCHDOG_NOTICE, 'link');
		}

		//J11 J124 J21 J224...
		$first = substr($temp_keyword, 0,1);//J
		$second = substr($temp_keyword, 1,1);//1-8
		$temp = array('j');
		$level = '基础课程';
		
		if(in_array($first, $temp) && $second>0 && $second<10 ){
			$third = substr($temp_keyword, 2,2);
			$mav = get_ly_jckc();
			$mav = $mav[$second];
			if($third>0&&$third<=$mav['max']){
				//24 => 001
				$count = $mav['max'];
				$index = str_pad($third, 2,'0',STR_PAD_LEFT);


				$link = 'new/'.$level.'/'.$mav['title'].'/'.$mav['prefex'].$index.'.mp3';

				$etime = time()+3600; // 授权十分钟后过期
				$key = 'ly729';   // token 防盗链密钥
				$path = '/'.$link; // 图片相对路径
				$sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;
				
				$cdn = 'http://lts33.b0.upaiyun.com/';
				$link = $cdn . urlencode($link).'?_upt='.$sign;
				$resources['key_'.$keyword]= array(
					'type'	=>	'music',
					'obj'		=> array(
						'title'	=> $mav['title'].'-'.$index,
						'desc'	=>	"良友圣经学院 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 点击►收听",
						'musicurl'	=>	$link,
						'hgmusicurl'	=>	$link,
					),
				);
			}else{
				//编码对，编号不对！
				$link = 'new/'.$level.'/'.$mav['title'].'/'.$mav['title'].'.pdf';
				$cdn = 'http://lts33.b0.upaiyun.com/';


				$etime = time()+864000; // 授权十天后过期
				$key = 'ly729';   // token 防盗链密钥
				$path = '/'.$link; // 图片相对路径
				$sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;

				$link = $cdn . urlencode($path).'?_upt='.$sign;
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
						'text'	=> "恭喜您，良友圣经学院 $level 《".$mav['title']."》已结束！\n回复J".($second+1)."1学习下一门课程[强]\n".'<a href="http://ly.yongbuzhixi.com/pdfviewer/web/?pdf='.$link.'">查看'.$mav['title'].'讲义</a>',
					)
				);
			}	
		}
		//end of new 良友圣经学院
	}
		//begin lysd sd1-sd999
		$orikeyword = $keyword;
		$check_keyword = substr($keyword, 0,2);
		$index = substr($keyword, 2,3);
		if($check_keyword == 'sd' && $account->uid != 8 ){
			$lysd = get_lysd();
			if($keyword = 'sd'){
				$mavmenu = "----四等奖目录----\n";
				foreach ($lysd as $key => $value) {
					$mavmenu .= $key.' sd'.$value['begin'].'-sd'.$value['end']."\n";
				}
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
					'text'	=> $mavmenu,
					)
				);
			}
			if(is_numeric($index)){
				foreach ($lysd as $key => $value) {
					if($index>=$value['begin'] && $index<=$value['end']){
						$link = $value['title'].'/'.str_pad($index, 3,'0',STR_PAD_LEFT).'.mp3';

						$etime = time()+3600; // 授权十分钟后过期
						$key = 'ly729';   // token 防盗链密钥
						$path = '/lysd/'.$link; // 图片相对路径
						$sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;

						$link = 'http://ly729.b0.upaiyun.com/lysd/'.urlencode($link).'?_upt='.$sign;

						$resources['key_'.$orikeyword]= array(
							'type'	=>	'music',
							'obj'		=> array(
								'title'	=> $value['title'],
								'desc'	=>	"良友礼品卡 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 点击►收听",
								'musicurl'	=>	$link,
								'hgmusicurl'	=>	$link,
							),
						);
						break;
					}
				}
			}
		}
		//begin bos
if(0){
 		if(!isset($resources)){
 			$file_key = 'http://ly.yongbuzhixi.com/cron/nissigz/json/'.date('Ym').'/'.date('Ymd') . '.json';
			$getheaders = @get_headers($file_key);
			if(isset($getheaders)&&$getheaders[0] == 'HTTP/1.1 404 Not Found'){
				$resources['key_'.$keyword]= array(
					'type'	=>	'text',
					'obj'		=> array(
						'text'	=>'亲，分发下载还没完成，请稍后再试！',
					)
				);
				return;
			}
 			$file = file_get_contents($file_key);
			$urls = json_decode($file,TRUE);

			if(count($urls))
			foreach ($urls as $key => $value) {
				if($value['title'] == $keyword){
					if(!isset($value['bce'])) return;
					$musicurl = 'http://'.$cdnlink.$value['bce'].upyun_get_token($value['objectKey']);
					$resources['key_'.$keyword]= array(
						'type'	=>	'music',
						'obj'		=> array(
							'title'	=> $value['title'].'♪',
							'desc'	=>	"点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新",
							'musicurl'	=>	$musicurl,
							'hgmusicurl'	=>	$musicurl,
						),
					);
					break;
				}
			}
 		}//end bos
 	}

	}
	return $resources;
}

/**
 * $change_keyword = return key!
 */
function mp_bbn_response($keyword,$account,$change_keyword=NULL){
	$resources = array();
	if (!$change_keyword) {
		$change_keyword = $keyword;
	}
	require_once('bbn.inc');
 	if($keyword == '400'){
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'text',
			'obj'		=> array(
			'text'	=> bbn_audio_menu(),
			)
		);
 	}else{
		$bbn = mp_get_bbn($keyword);
		$musicurl = $bbn[$keyword]['musicurl'];
		$title = $bbn[$keyword]['title'];
		$desc = '点击►收听 公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 每日更新';
		$resources['key_'.$change_keyword]= array(
			'type'	=>	'music',
			'obj'		=> array(
				'title'	=> $title,
				'desc'	=>	$desc,
				'musicurl'	=>	$musicurl,
				'hgmusicurl'	=>	$musicurl,
			),
		);
	}
	return $resources;
}

// 图片相对路径
// token 防盗链密钥
// 授权1分钟后过期
// 图片相对路径
// token 防盗链密钥
// 授权1分钟后过期
function upyun_get_token($path, $etime = 86400, $key = 'ly729'){
	$etime = time()+$etime; // 授权1分钟后过期
	return '?_upt='. substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;
}