<?php
/**
 * Utility function to check for and return a managed file.
 *
 * In this demonstration code we don't necessarily know if a file is managed
 * or not, so often need to check to do the correct behavior. Normal code
 * would not have to do this, as it would be working with either managed or
 * unmanaged files.
 *
 * @param string $uri
 *   The URI of the file, like public://test.txt.
 */
function bos_get_managed_file($uri) {
  $fid = db_query('SELECT fid FROM {file_managed} WHERE uri = :uri', array(':uri' => $uri))->fetchField();
  if (!empty($fid)) {
    $file_object = file_load($fid);
    return $file_object;
  }
  return FALSE;
}

/**
 * Implements hook_stream_wrappers().
 *
 * hook_stream_wrappers() is Drupal's way of exposing the class that PHP will
 * use to provide a new stream wrapper class. In this case, we'll expose the
 * 'session' scheme, so a file reference like "session://example/example.txt"
 * is readable and writable as a location in the $_SESSION variable.
 *
 * @see BaiduBosStreamWrapper
 */
function bos_stream_wrappers() {
  $wrappers = array(
    'session' => array(
      'name' => t('BOS storage'),
      'class' => 'BaiduBosStreamWrapper',
      'description' => t('Store files in the　BOS.'),
    ),
  );
  return $wrappers;
}


/**
 * @} End of "defgroup file_example".
 */
