<?php
/**
 * hook_rescources_info
 */
function mp_lts_rescources_info(){
  $rescources[] = array(
    'name' => 'mav',
    'desc' => '良友圣经学院【#100】',
  );
  return $rescources;
}

function  get_mp_ltsma(){
  return array(
    '101'=>array(
      'title'=>'婚姻与家庭',
      'prefex'=>'vmf1',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'罗加怡,李兰',
    ),
    '102'=>array(
      'title'=>'新约浅说',
      'prefex'=>'vkn0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'张得仁',
    ),
    '103'=>array(
      'title'=>'旧约浅说',
      'prefex'=>'vko0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'李重恩',
    ),
    '104'=>array(
      'title'=>'基要真理',
      'prefex'=>'vfb0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'姚谦',
    ),
    '105'=>array(
      'title'=>'基本研经法',
      'prefex'=>'vbm0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'林诚',
    ),
    '106'=>array(
      'title'=>'耶稣生平',
      'prefex'=>'vls0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'张得仁',
    ),
    '107'=>array(
      'title'=>'信仰与生活',
      'prefex'=>'vfl0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'李悦心',
    ),
    '108'=>array(
      'title'=>'事奉装备',
      'prefex'=>'vpr0',
      'count'=>24,
      'level'=>'基础课程',
      'author'=>'李兰',
    ),
    //109--199 预留给专辑
    //默认都有讲义。 如果无讲义，'pdf' =>0,
    //201-204 本科先修科
    '201'=>array(
      'title'=>'新约综览',
      'prefex'=>'vnt0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)本科先修科',
      'author'=>'李悦心',
    ),
    '202'=>array(
      'title'=>'旧约综览',
      'prefex'=>'vot0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)本科先修科',
      'author'=>'王羽燕',
    ),
    '203'=>array(
      'title'=>'基督教教义',
      'prefex'=>'vcd0',
      'count'=>30,
      'level'=>'本科课程',
      'author'=>'周广亮',
      'category'=>'神学(8科)本科先修科',
    ),
    '204'=>array(
      'title'=>'解经与研经',
      'prefex'=>'vhe0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'圣经(17科)本科先修科',
      'author'=>'林诚',
    ),
    '205'=>array(
      'title'=>'33周年院庆培灵会',
      'prefex'=>'lts330',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'良院老师',
      'pdf' =>0,
    ),
     '206'=>array(
      'title'=>'毕业周特辑2015',
      'prefex'=>'grc150',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'良院老师',
      'pdf' =>0,
    ),
     '207'=>array(
      'title'=>'开学周特辑2015',
      'prefex'=>'opc150',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'良院老师',
      'pdf' =>0,
    ),
     '208'=>array(
      'title'=>'圣诞节特辑2015',
      'prefex'=>'xma150',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'文惠、万峰',
    ),
     '209'=>array(
      'title'=>'春节培灵会2016',
      'prefex'=>'sfs160',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'卢文、周广亮、袁择善',
      'pdf' =>0,
    ),
     '210'=>array(
      'title'=>'烽火宣教情',
      'prefex'=>'amp0',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'魏外扬',
    ),
     '211'=>array(
      'title'=>'道在职场',
      'prefex'=>'vlw0',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'崔老师、文惠、杨天成',
    ),
     '212'=>array(
      'title'=>'城市宣教',
      'prefex'=>'vcn0',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'陈慕天、文惠',
    ),
     '213'=>array(
      'title'=>'复活节特辑2016',
      'prefex'=>'esp160',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'吴加恩',
    ),
    '214'=>array(
      'title'=>'慎思明辨',
      'prefex'=>'vfd0',
      'count'=>6,
      'level'=>'专辑课程',
      'category'=>'专题特辑',
      'author'=>'程蒙恩',
    ),
    //205--299 预留给专辑
    //默认都有讲义。 如果无讲义，'pdf' =>0,
    //301-314(317-3)本科课程 圣经

    '301'=>array(
      'title'=>'摩西五经',
      'prefex'=>'vph0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'梁凯玲',
    ),
    '302'=>array(
      'title'=>'旧约历史书I',
      'prefex'=>'voh0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'李重恩',
    ),
    '303'=>array(
      'title'=>'旧约历史书II',
      'prefex'=>'voi0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'李重恩',
    ),
    '304'=>array(
      'title'=>'诗歌智慧书I',
      'prefex'=>'vpb0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'胡卫理',
    ),
    '305'=>array(
      'title'=>'诗歌智慧书II',
      'prefex'=>'vpk0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'胡卫理',
    ),
    '306'=>array(
      'title'=>'先知书I',
      'prefex'=>'vop0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'林诚',
    ),
    '307'=>array(
      'title'=>'先知书II',
      'prefex'=>'vor0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'林诚',
    ),
    '308'=>array(
      'title'=>'约翰福音',
      'prefex'=>'vjo0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'刘锐光',
    ),
    '309'=>array(
      'title'=>'使徒行传',
      'prefex'=>'vas0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'袁择善',
    ),
    '310'=>array(
      'title'=>'保罗书信I',
      'prefex'=>'vpa0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'蔡筱枫',
    ),
    '311'=>array(
      'title'=>'保罗书信II',
      'prefex'=>'vpu0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'蔡筱枫',
    ),
    '312'=>array(
      'title'=>'普通书信',
      'prefex'=>'vge0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'张得仁',
    ),
    '313'=>array(
      'title'=>'罗马书',
      'prefex'=>'vrs0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'周广亮',
    ),
    '314'=>array(
      'title'=>'启示录',
      'prefex'=>'vrt0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'圣经(17科)',
      'author'=>'李悦心',
    ),
    //401-407(8-1)本科课程 神学(8科)
    '401'=>array(
      'title'=>'教会历史',
      'prefex'=>'vch0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'李重恩',
    ),
    '402'=>array(
      'title'=>'讲道学',
      'prefex'=>'vho1',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'周广亮,周大吉',
    ),
    '403'=>array(
      'title'=>'基督工人操守',
      'prefex'=>'vcw0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'周广亮',
    ),
    '404'=>array(
      'title'=>'异端与极端',
      'prefex'=>'vhx0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'郑子民',
    ),
    '405'=>array(
      'title'=>'教会行政',
      'prefex'=>'vca0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'姚谦,文惠',
    ),
    '406'=>array(
      'title'=>'圣灵论',
      'prefex'=>'vpn1',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'周广亮',
    ),
    '407'=>array(
      'title'=>'基督教伦理学',
      'prefex'=>'vce0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'神学(8科)',
      'author'=>'张得仁',
    ),
    //501-503本科课程 差传(3科)
    '501'=>array(
      'title'=>'差传导论',
      'prefex'=>'vmi0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'差传(3科)',
      'author'=>'姚谦',
    ),
    '502'=>array(
      'title'=>'教会增长',
      'prefex'=>'vcg0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'差传(3科)',
      'author'=>'卢文,郑子民',
    ),
    '503'=>array(
      'title'=>'本土差传',
      'prefex'=>'vom0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'差传(3科)',
      'author'=>'卢文,周广亮',
    ),
    //601-617 选修科
    '601'=>array(
      'title'=>'圣经背景',
      'prefex'=>'vbi0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'李兰',
    ),
    '602'=>array(
      'title'=>'路加福音',
      'prefex'=>'vlu0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'赵荣光',
    ),
    '603'=>array(
      'title'=>'基督教与科学',
      'prefex'=>'vcs0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'黄雅格',
    ),
    '604'=>array(
      'title'=>'基督教教育(制作中)',
      'prefex'=>'ved1',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'文惠,殷言',
    ),
    '605'=>array(
      'title'=>'主日学教学法',
      'prefex'=>'vst0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'文惠',
    ),
    '606'=>array(
      'title'=>'教导与牧养',
      'prefex'=>'vtp0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'周广亮',
    ),
    '607'=>array(
      'title'=>'基督化家庭',
      'prefex'=>'vcf1',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'周广亮,周素琴',
    ),
    '608'=>array(
      'title'=>'婚姻辅导',
      'prefex'=>'vmc0',
      'count'=>30,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'林真儿',
    ),
    '609'=>array(
      'title'=>'灵修默想与应用',
      'prefex'=>'vdm0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'林真儿',
    ),
    '610'=>array(
      'title'=>'苦难与罪恶',
      'prefex'=>'vss0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'郑子民',
    ),
    '611'=>array(
      'title'=>'青少年事工',
      'prefex'=>'vym0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'林真儿',
    ),
    '612'=>array(
      'title'=>'讲道实习',
      'prefex'=>'vhp1',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'文惠',
    ),
    '613'=>array(
      'title'=>'神迹奇事',
      'prefex'=>'vsw0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'袁择善',
    ),
    '614'=>array(
      'title'=>'教会复兴运动',
      'prefex'=>'vcm0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'周广亮',
    ),
    '615'=>array(
      'title'=>'圣经教师训练',
      'prefex'=>'vtb0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'林真儿',
    ),
    '616'=>array(
      'title'=>'单身事工',
      'prefex'=>'vsy0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'文惠',
    ),
    '617'=>array(
      'title'=>'中国教会史',
      'prefex'=>'vcc0',
      'count'=>24,
      'level'=>'本科课程',
      'category'=>'选修科',
      'author'=>'孙睿之',
    ),
    //701-706 进深课程 神学
    '701'=>array(
      'title'=>'基督论',
      'prefex'=>'vcy1',//?0?1
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'林诚',
    ),
    '702'=>array(
      'title'=>'末世论',
      'prefex'=>'vet0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'李悦心',
    ),
    '703'=>array(
      'title'=>'教会论',
      'prefex'=>'vey0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'吕路加',
    ),
    '704'=>array(
      'title'=>'圣经论(制作中)',//没有！
      'prefex'=>'v??0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'',
    ),
    '705'=>array(
      'title'=>'神论',
      'prefex'=>'vth0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'吕路加',
    ),
    '706'=>array(
      'title'=>'救恩论',
      'prefex'=>'vsn0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'林诚',
    ),
    '707'=>array(
      'title'=>'启示论',
      'prefex'=>'vdr0',
      'count'=>18,
      'level'=>'进深课程',
      'category'=>'神学',
      'author'=>'吕路加',
    ),
    //801-813 圣经(13科)
    '801'=>array(
      'title'=>'圣经神学',
      'prefex'=>'vbt0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'郑子民',
    ),
    '802'=>array(
      'title'=>'旧约神学',
      'prefex'=>'vog0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'古元明',
    ),
    '803'=>array(
      'title'=>'新约神学',
      'prefex'=>'vng1',//?0?1
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'吴加恩',
    ),
    '804'=>array(
      'title'=>'创世记',
      'prefex'=>'vgs1',//?0?1
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'赵伟文',
    ),
    '805'=>array(
      'title'=>'以赛亚书',
      'prefex'=>'vis0',
      'count'=>30,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'罗文辉',
    ),
    '806'=>array(
      'title'=>'但以理书',
      'prefex'=>'vda0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'李悦心',
    ),
    '807'=>array(
      'title'=>'哥林多前书',
      'prefex'=>'vic0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'张得仁',
    ),
    '808'=>array(
      'title'=>'哥林多后书',
      'prefex'=>'vio0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'张得仁',
    ),
    '809'=>array(
      'title'=>'加拉太书',
      'prefex'=>'vga0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经(13科)',
      'author'=>'李悦心,罗文辉',
    ),
    '810'=>array(
      'title'=>'以弗所书',
      'prefex'=>'vee0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'林真儿',
    ),
    '811'=>array(
      'title'=>'教牧书信',
      'prefex'=>'vps1',//?0?1
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'姚谦',
    ),
    '812'=>array(
      'title'=>'希伯来书',
      'prefex'=>'vhb1',//?0?1
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'张风',
    ),
    '813'=>array(
      'title'=>'圣经文学导论',
      'prefex'=>'vbl0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'圣经',
      'author'=>'阮一心',
    ),
    //901-908 进深课程 实用神学
    '901'=>array(
      'title'=>'释经与讲道',
      'prefex'=>'veh1',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'张得仁',
    ),
    '902'=>array(
      'title'=>'领袖训练I',
      'prefex'=>'vla0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'李星沙',
    ),
    '903'=>array(
      'title'=>'领袖训练II',
      'prefex'=>'vlb0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'李星沙',
    ),
    '904'=>array(
      'title'=>'教牧学',
      'prefex'=>'vpt0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'姚谦',
    ),
    '905'=>array(
      'title'=>'教牧辅导',
      'prefex'=>'vpc0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'林诚,徐婷',
    ),
    '906'=>array(
      'title'=>'崇拜学',
      'prefex'=>'vso1',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'张得仁',
    ),
    '907'=>array(
      'title'=>'差传神学',
      'prefex'=>'vmg0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'姚谦',
    ),
    '908'=>array(
      'title'=>'进深讲道学',
      'prefex'=>'vhh0',
      'count'=>24,
      'level'=>'进深课程',
      'category'=>'实用神学',
      'author'=>'罗文辉',
    ),
  );
}

function get_mp_lts_menu1(){
  //   $mavs = get_mp_ltsma();
  //   watchdog('mp_lts', $index, array(), WATCHDOG_NOTICE, 'link');
  // if($index==100){
  //   $text = '';
  //   $add = '★';
  //   foreach ($mavs as $key => $mav) {
  //     // if($mav['level']=='本科课程')
  //     //   $add = '✿';
  //     if($mav['level']!='进深课程') continue;
  //       $add = '☆';
  //     $text .= '【#'.$key.'】'.$mav['title'].$add."\n";
  //   }
  return '  【#101】婚姻与家庭★
  【#102】新约浅说★
  【#103】旧约浅说★
  【#104】基要真理★
  【#105】基本研经法★
  【#106】耶稣生平★
  【#107】信仰与生活★
  【#108】事奉装备★
  【#201】新约综览✿
  【#202】旧约综览✿
  【#203】基督教教义✿
  【#204】解经与研经✿
  【#205】33周年院庆培灵会*
  【#206】毕业周特辑2015*
  【#207】开学周特辑2015*
  【#208】圣诞节特辑2015*
  【#209】春节培灵会2016*
  【#210】烽火宣教情*
  【#211】道在职场*
  【#212】城市宣教*
  【#213】复活节特辑2016*
  【#301】摩西五经✿
  【#302】旧约历史书(I)✿
  【#303】旧约历史书(II)✿
  【#304】诗歌智慧书(I)✿
  【#305】诗歌智慧书(II)✿
  【#306】先知书(I)✿
  【#307】先知书(II)✿
  【#308】约翰福音✿
  【#309】使徒行传✿
  【#310】保罗书信(I)✿
  【#311】保罗书信(II)✿
  【#312】普通书信✿
  【#313】罗马书✿
  【#314】启示录✿
  【#401】教会历史✿
  【#402】讲道学✿
  【#403】基督工人操守✿
  【#404】异端与极端✿
  【#405】教会行政✿
  【#406】圣灵论✿
  【#407】基督教伦理学✿
  【#501】差传导论✿
  【#502】教会增长✿
  【#503】本土差传✿
  【#601】圣经背景✿
  【#602】路加福音✿
  【#603】基督教与科学✿
  【#604】基督教教育(制作中)
  【#605】主日学教学法✿
  【#606】教导与牧养✿
  【#607】基督化家庭✿
  【#608】婚姻辅导✿
  【#609】灵修、默想与应用✿
  【#610】苦难与罪恶✿
  【#611】青少年事工✿
  【#612】讲道实习✿
  【#613】神迹奇事✿
  【#614】教会复兴运动✿
  【#615】圣经教师训练✿
  【#616】单身事工✿
  【#617】中国教会史✿
  【#100】★基础课程 ✿本科课程
  【#700】☆进深课程 *专辑课程
  回复【#608】收听[ThumbsUp]';
}
function get_mp_lts_menu2(){
  return '  【#701】基督论☆
  【#702】末世论☆
  【#703】教会论☆
  【#704】圣经论(制作中)
  【#705】神论☆
  【#706】救恩论☆
  【#707】启示论☆
  【#801】圣经神学☆
  【#802】旧约神学☆
  【#803】新约神学☆
  【#804】创世记☆
  【#805】以赛亚书☆
  【#806】但以理书☆
  【#807】哥林多前书☆
  【#808】哥林多后书☆
  【#809】加拉太书☆
  【#810】以弗所书☆
  【#811】教牧书信☆
  【#812】希伯来书☆
  【#813】圣经文学导论☆
  【#901】释经与讲道☆
  【#902】领袖训练I☆
  【#903】领袖训练II☆
  【#904】教牧学☆
  【#905】教牧辅导☆
  【#906】崇拜学☆
  【#907】差传神学☆
  【#908】进深讲道学☆
  【#100】★基础课程 ✿本科课程
  【#700】☆进深课程
   回复【#701】收听[ThumbsUp]';
};
/**
 * hook_wxrescources
 */
function mp_lts_wxresources($resources, $account, $keyword){
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['mav']) && $enabled_resources['mav'])){
    return ;
  }
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_lts_wxresources_'.$keyword)) {
      $my_data = $cache->data;
    }
    else {
      //将一些高花销的计算逻辑写在这里，并将结果赋值给$my_data变量。
      //这里将计算的结果保存到cache表中。
      // 如果你的缓存的过期时间是有规律的，可以预测的，可以尝试使用下面方式来给缓存设置过期时间。
      // cache_set('my_module_data', $my_data, 'cache', time() + 3600);
      $my_data = _mp_getwxresources($resources, $account, $keyword);
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_lts_wxresources_'.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_lts_wxresources_'.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  return $my_data;
}
function _mp_getwxresources($resources, $account, $keyword){
  {
    #101-999
    if(substr($keyword, 0, 1)!='#')return;
    $subkey = str_replace('#', '', $keyword);
    $index = substr($subkey, 0, 3);//101-999
    if(!($index>=100&&$index<=999))return;

    $mavs = get_mp_ltsma();
    if(substr($index, 1)==='00'){
      if($index==100){
        $resources['key_'.$keyword]= array(
            'type'  =>  'text',
            'cache' =>  0,
            'gadata'   =>  array(
               'category'        => 'lts33',
               'action'          => 'menu_100',
               'label'           => 'wxservice_'.$account->uid,
            ),
            'obj'   => array(
              'text'  => get_mp_lts_menu1(),
            )
          );
        return $resources;
      }
      if($index==700){
        $resources['key_'.$keyword]= array(
            'type'  =>  'text',
            'cache' =>  0,
            'gadata'   =>  array(
               'category'        => 'lts33',
               'action'          => 'menu_700',
               'label'           => 'wxservice_'.$account->uid,
            ),
            'obj'   => array(
              'text'  => get_mp_lts_menu2(),
            )
          );
        return $resources;
      }

      $num = substr($index,0,1);
      $begin = $num.'00';
      $end = $num.'99';
      $text = '';
      $add = '★';
      foreach ($mavs as $key => $mav) {
        if($key>$begin&&$key<=$end) {
          if($mav['level']=='本科课程')
            $add = '✿';
          if($mav['level']=='进深课程')
            $add = '☆';
          if($mav['level']=='专辑课程')
            $add = '*';
          $text .= '【#'.$key.'】'.$mav['title'].$add."\n";
        }
      }
      $resources['key_'.$keyword]= array(
          'type'  =>  'text',
          'cache' =>  0,
          'gadata'   =>  array(
             'category'        => 'lts33',
             'action'          => 'menu_other',
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'text'  => $text."【#100】★基础课程✿本科课程\n【#700】☆进深课程\n回复【#".$num."01】收听\n回复【#".$num."010】查看讲义！[ThumbsUp]",
          )
        );
      return $resources;

    }

    if(!in_array($index, array_keys($mavs))){
      //error!编码超出范围！暂时没有，敬请期待！
      $resources['key_'.$keyword]= array(
          'type'  =>  'text',
          'cache' =>  0,
          'gadata'   =>  array(
             'category'        => 'lts33',
             'action'          => '编码超出范围',
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'text'  => "[大哭]编码有误，回复【#100】查看目录！",
          )
        );
      return $resources;
    }
    $mav = $mavs["$index"];
    $total = $mav['count'];
    $level = $mav['level'];
    $count = substr($subkey, 3);//1-24-30
    if($count>$total) {//error!编码不对！
      $resources['key_'.$keyword]= array(
        'type'  =>  'text',
        'cache' =>  0,
        'gadata'   =>  array(
           'category'        => 'lts33',
           'action'          => '编码不对',
           'label'           => 'wxservice_'.$account->uid,
        ),
        'obj'   => array(
          'text'  => "[大哭]编码有误，超出最大范围！\n回复【#".$index."0】查看讲义！",
        )
      );
      return $resources;
    }
    if($count==='0'){//获取目录概括+//获取pdf
      $link = 'new/'.$level.'/'.$mav['title'].'/'.$mav['title'].'.pdf';
      $cdn = 'http://lts33.b0.upaiyun.com/';
      $etime = time()+864000; // 授权十天后过期
      $key = 'ly729';   // token 防盗链密钥
      $path = '/'.$link; // 图片相对路径
      $sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;
      $link = $cdn . urlencode($path).'?_upt='.$sign;
      $temp = @get_headers($link);
      if($temp[0] != 'HTTP/1.1 200 OK'){//远程暂无!!!
        $resources['key_'.$keyword]= array(
          'type'  =>  'text',
          'cache' =>  864000,
          'gadata'   =>  array(
             'category'        => 'lts33',
             'action'          => '远程暂无',
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'text'  => '【#'.$index.'】'.$mav['title']."\n课程有".$mav['count']."课时\n属于".$mav['level']."\n授课老师：".$mav['author']."\n回复【#".$index."1】到【#".$index.$total."】获取节目！\n每日获取同步【#".$index."】\n[大哭]本课程暂无讲义哦！",
          )
        );
        return $resources;
      }
      $resources['key_'.$keyword]= array(
          'type'  =>  'text',
          'cache' =>  864000,
          'gadata'   =>  array(
             'category'        => 'lts33',
             'action'          => $mav['title'].'_pdf',
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'text'  => '【#'.$index.'】'.$mav['title']."\n课程有".$mav['count']."课时\n属于".$mav['level']."\n授课老师：".$mav['author']."\n<a href='http://ly.yongbuzhixi.com/pdfviewer/web/?pdf=".$link."'>》点此查看讲义</a>\n每日获取同步【#".$index."】\n",
          )
        );
      return $resources;
    }
    $update = '';
    if($count===FALSE) {
      $count = date('z')%$total;//按顺序循环播出，每天一集！
      ++$count;
      $update = ' 每日更新';
    }
    if($count==0) $count++;
    $rep = str_pad($count, 2,'0',STR_PAD_LEFT);
    $link = 'new/'.$level.'/'.$mav['title'].'/ma'.$mav['prefex'].$rep.'.mp3';
    // watchdog('$link', $link, array(), WATCHDOG_NOTICE, 'link');
    // $etime = time()+86400; // 授权1天后过期
    // $key = 'ly729';   // token 防盗链密钥
    $path = '/'.$link; // 图片相对路径
    // $sign = substr(md5($key.'&'.$etime.'&'.$path), 12,8).$etime;

    $cdn = 'http://lts33.b0.upaiyun.com/';
    $link = $cdn . urlencode($link);//.'?_upt='.$sign;
    // $temp = @get_headers($link);
    // if($temp[0] != 'HTTP/1.1 200 OK'){//远程暂无!!!
    //   $resources['key_'.$keyword]= array(
    //     'type'  =>  'text',
    //     'obj'   => array(
    //       'text'  => "[大哭]本课程还没有开放哦！",
    //     )
    //   );
    //   return $resources;
    // }
    $resources['key_'.$keyword]= array(
      'type'  =>  'music',
      'path' =>  $path,
      'cache' =>  0,
      'gadata'   =>  array(
         'category'        => 'lts33',
         'action'          => $mav['title'].'_'.$rep,
         'label'           => 'wxservice_'.$account->uid,
      ),
      'obj'   => array(
        'title' => '【'.$keyword.'】'.$mav['title'].'-'.$rep,
        'desc'  =>  "点击►收听".$update." 良院".str_replace('课程', '', $level) ." 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' 技术支持:'.($account->uid==255?'永不止息':'主内公众云'),
        'musicurl'  =>  $link,
        'hgmusicurl'  =>  $link,
      ),
    );
    return $resources;
  }
}
