<?php
/**
 * Implements hook_node_view().
 */
function wx_layout_node_view($node, $view_mode, $langcode) {
  if($node->type=='mpwechat' && $view_mode=='full'){
        $node->content['body'][0]['#markup'] .= '<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapsempqr" aria-expanded="false" aria-controls="collapsempqr">查看二维码</button>
      <div class="collapse" id="collapsempqr">
        <img src="'.$node->field_link['und'][1]['value'].'" alt="" class="img-responsive img-thumbnail">
      </div>';
    if(isset($node->field_redirect_link[LANGUAGE_NONE][0]['value'])){
        $node->content['body'][0]['#markup'] .= '<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapsempqr" aria-expanded="false" aria-controls="collapsempqr">查看二维码</button>
      <div class="collapse" id="collapsempqr">
        <a href="'.$node->field_redirect_link[LANGUAGE_NONE][0]['value'].'">
        <p>点击阅读原文链接关注 </p>
        <img src="'.$node->field_link['und'][1]['value'].'" alt="" class="img-responsive img-thumbnail"></a>
      </div>';
      }
  }
}
