<?php
/**
 * Implements hook_node_view().
 */
function wx_layout_node_view($node, $view_mode, $langcode) {
  if($node->type=='mpwechat' && $view_mode=='full'){
    if(isset($node->field_redirect_link[LANGUAGE_NONE][0]['value'])){
        $node->content['body'][0]['#markup'] .= '<button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapsempqr"'.$node->nid.' aria-expanded="false" aria-controls="collapsempqr'.$node->nid.'">查看二维码</button>&nbsp;&nbsp;<a class="btn btn-default" href="wxuser/'.$node->uid.'">本站收录<span class="badge">4</span></a>
      <div class="collapse collapsempqr" id="collapsempqr'.$node->nid.'">
        <a href="'.$node->field_redirect_link[LANGUAGE_NONE][0]['value'].'">
        <p>点击阅读原文链接关注 </p>
        <img src="'.$node->field_link['und'][1]['value'].'" alt="" class="img-responsive img-thumbnail"></a>
      </div>';
      }else{
        $node->content['body'][0]['#markup'] .= '<button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapsempqr'.$node->nid.'" aria-expanded="false" aria-controls="collapsempqr"'.$node->nid.'>查看二维码</button>&nbsp;&nbsp;<a class="btn btn-default" href="wxuser/'.$node->uid.'">本站收录<span class="badge">4</span></a>
      <div class="collapse collapsempqr" id="collapsempqr'.$node->nid.'">
        <img src="'.$node->field_link['und'][1]['value'].'" alt="" class="img-responsive img-thumbnail">
      </div>';
      }
  }
}
