<?php
/**
 * Implements hook_cron().
 */
function mp_cron_cron() {
  module_load_include('php', 'mp_liangyou', 'liangyou_audio_list');
  $radios = liangyou_audio_list2();
  //20160330.json
  $file_path = DRUPAL_ROOT.'/sites/default/files/cron/txly2/';
  if (!is_dir($file_path)) {
    mkdir($file_path, 0777, true);
  }
  $file_key = drupal_realpath('public://cron/txly2/'.date('Ymd').'.json') ;
  if(!file_exists($file_key))  {
    foreach ($radios as $code => $radio) {
      $title = $radio['title'];
      $url = 'http://txly2.net/'.$code;
      $html = file_get_html($url);
      if(!$html) {
        watchdog('mp_liangyou', 'lost audio:'.$title, array(), WATCHDOG_NOTICE, 'error');
        continue;
      }
      if(!isset($html->find('.ss-title p', 0)->plaintext)) continue;
      $mp3_description = $html->find('.ss-title p', 0)->plaintext;
      $title_get = $html->find('.ss-title a', 1)->plaintext;
      $dates = explode('-', $title_get);
      $data[] = array(
        'code'  => $code,
        'index'  => $radio['index'],
        'title' => $title,
        'date' => $dates[1],
        'desc'  => $mp3_description,
        );
      // break;
    }
    $file = json_encode($data);
    if(!is_null($file)){
      file_put_contents( $file_key , $file );
      watchdog('mp_liangyou', 'Success download ly audio list from txly2', array(), WATCHDOG_NOTICE, 'link');
    }
  }
  // each code.json
  foreach ($radios as $code => $radio) {
    $file_key = drupal_realpath('public://cron/txly2/'.$code.'.json');
    if(!file_exists($file_key))  {
      $url = 'http://txly2.net/'.$code;
      // $url = 'http://txly2.net/sg';
      $html = file_get_html($url);
      if(!$html) {
        watchdog('mp_cron', '!file_get_html:'.$code, array(), WATCHDOG_NOTICE, 'error');
        continue;
      }
      if(!isset($html->find('.ss-title p', 0)->plaintext)) continue;
      $mp3_description = $html->find('.ss-title p', 0)->plaintext;
      $title_get = $html->find('.ss-title a', 1)->plaintext;
      $dates = explode('-', $title_get);
      $data[$dates[1]] = $mp3_description;
      $file = json_encode($data);
      file_put_contents( $file_key , $file );
    }else{
      $data = json_decode(file_get_contents($file_key),true);
      if(isset($data[date('Ymd')])) continue; //20160330
      $url = 'http://txly2.net/'.$code;
      $html = file_get_html($url);
      if(!$html) {
        watchdog('mp_cron', '!file_get_html:'.$code, array(), WATCHDOG_NOTICE, 'error');
        continue;
      }
      if(!isset($html->find('.ss-title p', 0)->plaintext)) continue;
      $mp3_description = $html->find('.ss-title p', 0)->plaintext;
      $title_get = $html->find('.ss-title a', 1)->plaintext;
      $dates = explode('-', $title_get);
      $data[$dates[1]] = $mp3_description;
      $file = json_encode($data);
      file_put_contents( $file_key , $file );
      continue;
    }
  }
  // return $resources;
}

/**
 * called by corn.
 * @return [type] [description]
 */
function create_mp_cron_nodes($account=NULL){
  //get all 认证的账户
  //TODO no repeat meadia_ids!!!
  $account = user_load(8);
  $weObj= _mp_service_init_wechat($account);
  $medias = $weObj->getForeverList('news',1,20);
  foreach ($medias['item'] as $key => $media) {
    $node = new stdClass();
    $node->type = 'mp_cron';
    node_object_prepare($node);
    $node->uid = $account->uid;
    $node = $node;
    $node->field_media_id[LANGUAGE_NONE][0]['value']  =  $media['media_id'];
    // $node->field_publish_date[LANGUAGE_NONE][0]['value']  = date('Y-m-d H:i:s');
    foreach ($media['content']['news_item'] as $key => $item) {
      $node->field_title[LANGUAGE_NONE][]= array('value'=>$item['title']);
      $node->field_redirect_link[LANGUAGE_NONE][]= array('value'=>$item['url']);
      $node->field_link[LANGUAGE_NONE][]= array('value'=>$item['thumb_url']);//image
    }
    $node->title = $node->field_title[LANGUAGE_NONE][0]['value'];
    node_save($node);
  }
}
