<?php
/**
 * hook_rescources_info
 */
function mp_lywx_rescources_info(){
  $rescources[] = array(
    'name' => 'ly',
    'desc' => '良友【100】',
  );
  return $rescources;
}
/**
 * HOOK_wxresources
 * @param  [type] $resources [description]
 * @param  [type] $account   [description]
 * @param  [type] $keyword   [description]
 * @return [type]            [description]
 */
function  mp_lywx_wxresources($resources, $account, $keyword, $weObj){
  if(!is_string($keyword)) return;//!$keyword||
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['ly']) && $enabled_resources['ly'])){
    return;
  }
  //tq begin
  if($keyword=='tq') {
    $img = array(
      'Title'=>"良友67周年台庆微信留言板，点击查看更多～",
      'Description'=>"",
      'PicUrl'=>'http://wx.yongbuzhixi.com/sites/default/files/wxcomments/bg/729logo_67ann.png',
      'Url'=>'http://wx.yongbuzhixi.com/node/2089',
    );
    $news[] = $img;
    $nid = 2089;
    $node = node_load($nid);
    $mode = variable_get('comment_default_mode_' . $node->type, COMMENT_MODE_THREADED);
    $comments_per_page = 10;
    $info = '';
    if ($cids = comment_get_thread($node, $mode, $comments_per_page)) {
      $comments = comment_load_multiple($cids);
      // dpm($comments);
      foreach ($comments as $comment) {
        $registered_name = $comment->registered_name;
        $str = explode('_',$comment->registered_name);
        if(isset($str[1]))
          $registered_name = $str[0];
        $info .= '●'.$registered_name.':'.$comment->comment_body['und'][0]['safe_value']."\n";
      }
    }
    if(empty($info)){
      $info = '恭喜，快来抢沙发吧！发送任意祝福内容+729即可发布哦！';
    }
    $img = array(
      'Title'=>$info,
      'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
      'PicUrl'=>'',
      'Url'=>'http://wx.yongbuzhixi.com/node/2089',
    );
    $news[] = $img;
    $resources['key_'.$keyword]= array(
      'type'  =>  'news',
      'gadata' => array(
       'category'        => '图文',
       'action'          => '良友67周年台',
       'label'           => 'wxservice_'.$account->uid,
       ),
      'cache' =>  0,
      'obj'   =>  $news,
    );
    return $resources;
  }//留言板图文end
  //tq end!

  // $my_data = _mp_lywx_wxresources($resources, $account, $keyword,$weObj);
  // return $my_data;
  $my_data = &drupal_static(__FUNCTION__);
  if (1||!isset($my_data)) {
    if (0&&$cache = cache_get('mp_lywx_wxresources_'.$account->uid.$keyword)) {
      $my_data = $cache->data;
      //DEBUG TO DELETE!
      if($keyword=='202'||$keyword=='603'){
        $str = date('ymd');
        $pos = strpos($my_data['key_'.$keyword]['obj']['musicurl'], $str);
        if($pos === false){
          watchdog('mp_lywx', $keyword.'-'.$str.'-'.$my_data['key_'.$keyword]['obj']['musicurl'], array(), WATCHDOG_NOTICE, 'error');
        }
      }
      //DEBUG TO DELETE later!
    }else {
      $my_data = _mp_lywx_wxresources($resources, $account, $keyword,$weObj);
      //729 30days.begin to delete
      if(time()>strtotime('2016-06-28 23:59:59') && time()<strtotime('2016-07-28 23:59:59')){
        $custommessage = mp_lywx_wxresources($resources, $account, '729', $weObj);
        $my_data['key_'.$keyword]['custommessages'] = $custommessage;
      }
      ////729 30days.begin to delete end
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_lywx_wxresources_'.$account->uid.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_lywx_wxresources_'.$account->uid.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  return $my_data;
}

function _mp_lywx_wxresources($resources, $account, $keyword, $weObj){

  $allowkeywords = array('0');
  //1. 如輸入”0”時，會自動發送圖文“收听节目代号”。
  if(in_array($keyword, $allowkeywords)){
    $img = array(
      'Title'=>"收听节目代号",
      'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
      'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
      'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=502730954&idx=1&sn=f34dfca8e4eae2f8c434e44e97e93795&chksm=718517e146f29ef75c6738e67c5e78a93a5baf269d25ef77aa5ae2ec197a3b99070f6ee809c3&mpshare=1&scene=1&srcid=1129kvQDVnRdjrcFNiQpxS9i#rd',
    );
    $news[] = $img;
    $resources['key_'.$keyword]= array(
      'type'  =>  'news',
      'gadata' => array(
       'category'        => '图文',
       'action'          => '收听节目代号',
       'label'           => 'wxservice_'.$account->uid,
       ),
      'cache' =>  0,
      'obj'   =>  $news,
      );
    return $resources;
  }

  $ori_keyword = $keyword;
  module_load_include('php', 'mp_liangyou', 'liangyou_audio_list');
  $liangyou_audio_list = liangyou_audio_list_bylywxindex();
  $keyword = substr($ori_keyword, 0, 3);
  // 101-901
	if(in_array($keyword, array_keys($liangyou_audio_list))){
    $lywx = (int)$keyword;
		$liangyou_audio_list_info = $liangyou_audio_list[(int)$keyword];
		$ori_title = $liangyou_audio_list_info['title'];
		$code = $liangyou_audio_list_info['code'];
		$lywx = $liangyou_audio_list_info['lywx'];
		// http://lywxaudio.b0.upaiyun.com/2016/zz/zz160205.mp3
		// $dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');

		$upyun_bucket_name = 'lywxaudio';
		$cdnlink = $upyun_bucket_name.'.yongbuzhixi.com';

    $offset = substr($ori_keyword, 3) ?: 0;
		while ($offset <= 7) {
			$date = date('ymd',time()-$offset*86400);
			$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
			$musicurl = 'http://'.$cdnlink.$path;
      $upyunurl = $musicurl.upyun_get_token($path);
			$temp = @get_headers($upyunurl);
			if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
				$title = '【'.$lywx.'】'.$ori_title;
				$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' '.$date;
		    // $weObj->music($title , $desc, $musicurl, $musicurl)->reply();
        $resources['key_'.$ori_keyword]= array(
          'type'  =>  'music',
          'gadata'   =>  array(
             'category'        => 'lywxaudio',
             'action'          => $ori_title,
             'label'           => 'wxservice_'.$account->uid,
          ),
          'path'  => $path,
          'cache' => 43201,
          'obj'   => array(
            'title' => $title,
            'desc'  => $desc,
            'musicurl'  =>  $musicurl,
            'hgmusicurl'  =>  $musicurl,
          ),
        );
        return $resources;
			}
			$offset++;
		}
	}
  //get audio by title
	$liangyou_audio_list = liangyou_audio_list_bytitle();
	if(in_array($keyword, array_keys($liangyou_audio_list))){
		$liangyou_audio_list_info = $liangyou_audio_list[$keyword];
		$ori_title = $keyword;//$liangyou_audio_list_info['title'];
		$code = $liangyou_audio_list_info['code'];
		$lywx = $liangyou_audio_list_info['lywx'];
		// http://lywxaudio.b0.upaiyun.com/2016/zz/zz160205.mp3
		// $dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');

		$upyun_bucket_name = 'lywxaudio';
		$cdnlink = $upyun_bucket_name.'.yongbuzhixi.com';
		$offset=0;
		while ($offset <= 7) {
			$date = date('ymd',time()-$offset*86400);
			$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
			$musicurl = 'http://'.$cdnlink.$path;
      $upyunurl = $musicurl.upyun_get_token($path);
      $temp = @get_headers($upyunurl);
			if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
				$title = '【'.$lywx.'】'.$ori_title;
				$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' '.$date;
		    // $weObj->music($title , $desc, $musicurl, $musicurl)->reply();
        $resources['key_'.$ori_keyword]= array(
          'type'  =>  'music',
          // 'gakey'   =>  $ori_title,
          'gadata'   =>  array(
             'category'        => 'lywxaudio',
             'action'          => $ori_title,
             'label'           => 'wxservice_'.$account->uid,
          ),
          'path'  => $path,
          'cache' => 43201,
          'obj'   => array(
            'title' =>  $title,
            'desc'  => $desc,
            'musicurl'  =>  $musicurl,
            'hgmusicurl'  =>  $musicurl,
          ),
        );
        return $resources;
			}
			$offset++;
		}
	}

  if(date('md')!='0729')//台庆当天不使用微信客服功能
  if (strpos($ori_keyword,'您好') !== false||
      strpos($ori_keyword,'你好') !== false||
      strpos($ori_keyword,'请') !== false||
      strpos($ori_keyword,'播') !== false||
      strpos($ori_keyword,'哪') !== false||
      strpos($ori_keyword,'我') !== false||
      strpos($ori_keyword,'想') !== false||
      strpos($ori_keyword,'么') !== false||
      strpos($ori_keyword,'吗') !== false||
      strpos($ori_keyword,'几') !== false||
      strpos($ori_keyword,'怎') !== false||
      strpos($ori_keyword,'在') !== false||
      strpos($ori_keyword,'听') !== false||
      strpos($ori_keyword,'祷') !== false||
      strpos($ori_keyword,'帮') !== false||
      strpos($ori_keyword,'好') !== false||
      strpos($ori_keyword,'呢') !== false||
      strpos($ori_keyword,'错') !== false||
      strpos($ori_keyword,'电话') !== false||
      strpos($ori_keyword,'手机') !== false||
      strpos($ori_keyword,'号码') !== false||
      strpos($ori_keyword,'没') !== false
    ){
    $weObj->transfer_customer_service()->reply();
    gapushagent('event',array(
     'category'        => 'getservice',
     'action'          => $ori_keyword,
     'label'           => 'wxservice_'.$account->uid,
    ));
    return ;
  }

  $len = strlen($ori_keyword);
  if(date('md')=='0729')//台庆当天使用留言板功能
  if($len >= 12) {//祝良友电台生日快乐729
    $nid = 2089;

    $node_type = 'wxcomments';
    //POST($user_info,$ori_keyword);
    $id = $weObj->getRevID();
    // watchdog('id?', $id, array(), WATCHDOG_NOTICE, 'link');
    // if(variable_get('mp_config_wxcomments_before', '0') == $id) {
    //   watchdog('prevent twice post by wechat servuce!', 'message', array(), WATCHDOG_NOTICE, 'link');
    //   return;
    // }
    $openid = $weObj->getRev()->getRevFrom();
    $user_info = $weObj->getUserInfo($openid);

    $comment_body = $ori_keyword;

    preg_match('/@\d{4}/', $ori_keyword,$m);//$m[0]=@2089
    if(isset($m[0])){
      $nid = str_replace('@', '', $m[0]);
      $comment_body =  str_replace($m[0], '', $comment_body);
    }

    if (strpos($ori_keyword,'729') !== false || strpos($ori_keyword,'台庆') !== false || strpos($ori_keyword,'生日') !== false) {
      $nid = 2089;
      $comment_body = $ori_keyword;
    }
    $pid = 0;
    $str = explode('?',$comment_body);
    if(isset($str[1])){
      $str2 = explode('#',$str[1]);
      if(isset($str2[0])){
        if(node_load($str2[0]))
          $nid = $str2[0];
      }
      if(isset($str2[1]))
        $pid = $str2[1];
    }
    $url = url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q=').'node/'.$nid;
    // $resources = mp_lywx_wxresources($resources, $account, 'tq', $weObj);
    $weObj->text("留言成功，审核后会出现在 “<a href='".$url."'>台庆留言版</a>”\n请点击蓝色字体的 “<a href='".$url."'>台庆留言版</a>”进入")->reply();
    //...TODO sen news!
    $before = variable_get('mp_config_wxcomments_wxid', '0');
    // dpm($before);
    // watchdog('before', $before, array(), WATCHDOG_NOTICE, 'link');
    // watchdog('id', $id, array(), WATCHDOG_NOTICE, 'link');
    if($before!=$id){
      variable_set('mp_config_wxcomments_wxid', $id);
      _post_wxcomments($user_info,$comment_body,$nid,$id,$pid);
      if($account->uid>1) gapushagent('event',array(
       'category'        => 'comments',
       'action'          => $ori_keyword,
       'label'           => 'wxservice_'.$account->uid,
      ));
    }
    return $resources;
  }
  //2. 如輸入”0”或節目代號以外的任何數字、英文、符號等，會自動發送圖文“良友知音使用说明”。
  $img = array(
    'Title'=>"良友知音使用说明",
    'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
    'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
    'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=403749894&idx=1&sn=0158a36a4c6d87aed8c7bad66a738791#rd',
  );
  $news[] = $img;
  $resources['key_'.$keyword]= array(
    'type'  =>  'news',
    'gadata' => array(
     'category'        => '图文',
     'action'          => '良友知音使用说明',
     'label'           => 'wxservice_'.$account->uid,
     ),
    'cache' =>  0,
    'obj'   =>  $news,
    );
  return $resources;
}


/**
 * Hook_wxservice_event_alter
 */
function mp_lywx_wxservice_event_alter($weObj,$event,$account){
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['ly']) && $enabled_resources['ly'])){
    return;
  }
  // watchdog('mp_lywx', '<pre>'.print_r($event, 1), array(), WATCHDOG_NOTICE, 'link');
  if($event['event']=='subscribe'){
    // $img = array(
    //   'Title'=>"良友知音使用说明",
    //   'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
    //   'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
    //   'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=403749894&idx=1&sn=0158a36a4c6d87aed8c7bad66a738791#rd',
    // );
    // $news[] = $img;
    // $img = array(
    //   'Title'=>"收听节目代号",
    //   'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
    //   'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
    //   'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=2650214608&idx=5&sn=ab99137cf51d49c2975940bf1918fbf9&chksm=f18517fbc6f29eede4dbcccd13aff5082759602ca219113fc2cfa9cb072d0025530a5bd401df&scene=0#wechat_redirect',
    // );
    // $news[] = $img;    $weObj->news($news);
    $weObj->text("欢迎您关注【良友知音】微信订阅号。本订阅号可收听良友电台节目、了解电台最新节目动向和各类活动消息、与电台互动。每日为您推送灵修节目《旷野吗哪》声档和文章，选推各类精彩节目图文~~\n<a href='http://mp.weixin.qq.com/mp/getmasssendmsg?__biz=MzI1MDE0NzM5Ng==#wechat_webview_type=1&wechat_redirect'>点此可查看历史图文</a>\n还可以发送节目代号，获取音频，收听几十档有关信仰、生活、婚姻、家庭、教养子女等各类的节目。【良友知音】盼望与您“知音、牵手、同行”，一起做“指尖的福音分享”，透过一个简单的分享动作把福音、爱、希望分享给更多的人。\n发送数字0可获取 “发送代号”，查看每个节目相对应的代号，观看“良友知音”收听节目与分享节目的操作指南。\n更多功能请点击下方菜单栏");

  }
}

/**
 * Implements hook_node_view().
 */
function mp_lywx_node_view($node, $view_mode, $langcode) {
  $nid = 2089;
  if($node->nid == $nid && $view_mode=='full'){
    global $user;
    if(isset($_GET['award'])&& $user->uid == $node->uid){
      $query = db_select('comment', 'c');
      $query->join('users', 'u', 'c.uid = u.uid'); //JOIN node with users
      $query->condition('c.nid', $nid);
      $query->groupBy('c.uid');//GROUP BY user ID
      $query->fields('u', array('name'));
      $query->fields('u', array('uid'));
      $result = $query->execute()->fetchAll();

      $count = db_query('SELECT c.cid FROM {comment} c WHERE c.nid = :nid', array(':nid' => $nid));
      $count->fetchCol();
      $count = $count->rowCount();

      $min=0; $max=count($result)-1; $quantity=3;
      $awards = '截至'.date('Y.m.d H:i').',微信参与人数：'.$max.'; 总共接受到用户发送微信互动消息'.$count."条; 本次随机抽取的".$quantity."位听众如下：<br/><ol id='729award'>";
      $numbers = range($min,$max);
      shuffle($numbers);
      $indexs = array_slice($numbers, 0, $quantity);
      foreach ($indexs as $index) {
        $registered_name = $result[$index]->name;
        $str = explode('_',$result[$index]->name);
        if(isset($str[1]))
          $registered_name = $str[0];
        $account = user_load($result[$index]->uid);
        $province = isset($account->data['province'])?$account->data['province']:'';
        $city = isset($account->data['city'])?$account->data['city']:'';
        $sex = '未知';
        if(isset($account->field_user_sex['und'][0]['value'])){
          $sex=$account->field_user_sex['und'][0]['value']?'弟兄':'姊妹';
        }
        $awards .= '<li>'.$result[$index]->uid .'：'. $registered_name .$sex.' '.$province.$city. "</li>";
      }
      $awards .= '</ol>';
      $node->content['my_additional_field'] = array(
        '#markup' => $awards,
        '#weight' => 10,
      );return $node;
    }
  }

  $nid = 2110;
  if($node->nid == $nid && $view_mode=='full'){
    global $user;
    if(in_array('义工编辑',$user->roles)){
      $nid = 2110;
      $result = db_query('SELECT c.uid FROM {comment} c WHERE c.nid = :nid', array(':nid' => $nid));
      $uids = $result->fetchCol();
      $count = $result->rowCount();
      $uids = array_unique($uids);

      $max=count($result)-1;
      $awards = '截至'.date('Y.m.d H:i').',微信参与问答人数：'.count($uids).'; 总共接受到用户发送微信问答消息'.$count."条；听众回答排行榜：<br/><ul id='729award'>";

      if (!function_exists('sortByCount')){
        function sortByCount($a, $b) {
            $a = count($a);
            $b = count($b);

            if($a == $b) {
                return 0;
            }

            return ($a > $b) ? -1 : 1;
        }
      }
      //get all right answers cid&qid
      $query = db_select('field_data_field_questionid', 'q');
      $query->join('field_data_field_rightwrong', 'r', 'r.entity_id = q.entity_id');
      $query->fields('q', array('entity_id','field_questionid_value'));
      // $query->fields('r', array('field_rightwrong_value'));
      $query->condition('r.field_rightwrong_value', 1);
      $results = $query->execute()->fetchAll();
      // dpm($results);
      foreach ($results as $result) {
        $query = db_select('comment', 'c');
        $query->fields('c', array('name','uid'));
        $query->condition('c.cid', $result->entity_id);//
        $ccuser = $query->execute()->fetchAll();
        $top[$ccuser[0]->uid][$result->field_questionid_value] = $ccuser[0]->name;
      }
      uasort($top, 'sortByCount');
      // dpm($top);
      foreach ($top as $uid => $value) {
        $account = user_load($uid);
        $registered_name = $account->name;
        $str = explode('_',$account->name);
        if(isset($str[1]))
          $registered_name = $str[0];
        $province = isset($account->data['province'])?$account->data['province']:'';
        $city = isset($account->data['city'])?$account->data['city']:'';
        $sex = '未知';
        if(isset($account->field_user_sex['und'][0]['value'])){
          $sex=$account->field_user_sex['und'][0]['value']?'弟兄':'姊妹';
        }
        $awards .= '<li>'.count($value).'：'. $registered_name .$sex.' '.$province.$city. "</li>";
      }
      $awards .= '</ol>';

      $node->content['my_additional_field'] = array(
        '#markup' => $awards,
        '#weight' => 10,
      );return $node;
    }
  }
}


