<?php
function lywx_menu(){
return
'输入以下数字代号，可以收听良友电台相关的节目：

生活智慧
101：微播出炉
102：书香园地
103：今夜心未眠
104：绝妙当家
105：生活无国界
106：零点零距离
107：iradio爱广播

关怀辅导
201：空中辅导
202：无限飞行号
203：i关怀心磁场

婚恋家庭
301：恋爱季节
302：幸福满家园
303：亲情不断电
304：欢乐卡恰碰

诗歌音乐
401：齐来颂扬
402：彩虹桥
403：长夜的牵引

慕道探索
501：生命的福音
502：现代人的希望
503：津津乐道

生命成长
601：旷野吗哪
602：生命的四季
603：拥抱每一天
604：施恩座前
605：这一刻清心
606：空中崇拜
607：燃亮的一生
608：佳美脚踪
609：真理之光
610：生根建造
611：给力人生
612：信仰百宝箱
613：空中门训

学习真道
701：真道分解
702：圣言盛宴
703：聆听主道
704：经动人心
705：好牧人
706：善牧良言
707：真理与柱石
708：生活之光

中英双语
801：蓝天绿洲
802：天路导向
803：天路导向粤

少数民族
901：恩典与真理
902：爱在人间

栽培训练
1001：接棒人
1002：晨曦讲座
1003：良院精选';
}
/**
 * hook_rescources_info
 */
function mp_lywx_rescources_info(){
  $rescources[] = array(
    'name' => 'ly',
    'desc' => '良友【100】',
  );
  return $rescources;
}
/**
 * HOOK_wxresources
 * @param  [type] $resources [description]
 * @param  [type] $account   [description]
 * @param  [type] $keyword   [description]
 * @return [type]            [description]
 */
function  mp_lywx_wxresources($resources, $account, $keyword, $weObj){
  if(!is_string($keyword)) return;//!$keyword||
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['ly']) && $enabled_resources['ly'])){
    return;
  }
  $my_data = _mp_lywx_wxresources($resources, $account, $keyword,$weObj);
  // return $my_data;
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_lywx_wxresources_'.$account->uid.$keyword)) {
      $my_data = $cache->data;
    }else {
      $my_data = _mp_lywx_wxresources($resources, $account, $keyword,$weObj);
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_lywx_wxresources_'.$account->uid.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_lywx_wxresources_'.$account->uid.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  return $my_data;
}

function _mp_lywx_wxresources($resources, $account, $keyword, $weObj){
	module_load_include('php', 'mp_liangyou', 'liangyou_audio_list');
	$liangyou_audio_list = liangyou_audio_list_bylywxindex();
  $orikeyword = $keyword;
  // 101-901
	if(in_array($keyword, array_keys($liangyou_audio_list))){
    $lywx = (int)$keyword;
		$liangyou_audio_list_info = $liangyou_audio_list[(int)$keyword];
		$ori_title = $liangyou_audio_list_info['title'];
		$code = $liangyou_audio_list_info['code'];
		$lywx = $liangyou_audio_list_info['lywx'];
		// http://lywxaudio.b0.upaiyun.com/2016/zz/zz160205.mp3
		// $dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');

		$upyun_bucket_name = 'lywxaudio';
		$cdnlink = $upyun_bucket_name.'.yongbuzhixi.com';

		$offset=0;
		while ($offset <= 7) {
			$date = date('ymd',time()-$offset*86400);
			$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
			$musicurl = 'http://'.$cdnlink.$path;
      $upyunurl = $musicurl.upyun_get_token($path);
			$temp = @get_headers($upyunurl);
			if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
				$title = '【'.$lywx.'】'.$ori_title;
				$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' '.$date;
		    // $weObj->music($title , $desc, $musicurl, $musicurl)->reply();
        $resources['key_'.$orikeyword]= array(
          'type'  =>  'music',
          'gadata'   =>  array(
             'category'        => 'lywxaudio',
             'action'          => $ori_title,
             'label'           => '一次一个',
          ),
          'path'  => $path,
          'cache' => 43201,
          'obj'   => array(
            'title' => $title,
            'desc'  => $desc,
            'musicurl'  =>  $musicurl,
            'hgmusicurl'  =>  $musicurl,
          ),
        );
        return $resources;
			}
			$offset++;
		}
	}
  //get audio by title
	$liangyou_audio_list = liangyou_audio_list_bytitle();
	if(in_array($keyword, array_keys($liangyou_audio_list))){
		$liangyou_audio_list_info = $liangyou_audio_list[$keyword];
		$ori_title = $keyword;//$liangyou_audio_list_info['title'];
		$code = $liangyou_audio_list_info['code'];
		$lywx = $liangyou_audio_list_info['lywx'];
		// http://lywxaudio.b0.upaiyun.com/2016/zz/zz160205.mp3
		// $dir_stru = 'liangyou/nissigz/'.$title.'/'.date('Ym');

		$upyun_bucket_name = 'lywxaudio';
		$cdnlink = $upyun_bucket_name.'.yongbuzhixi.com';
		$offset=0;
		while ($offset <= 7) {
			$date = date('ymd',time()-$offset*86400);
			$path = '/'.date('Y').'/'.$code.'/'.$code.$date.'.mp3';
			$musicurl = 'http://'.$cdnlink.$path;
      $upyunurl = $musicurl.upyun_get_token($path);
      $temp = @get_headers($upyunurl);
			if($temp[0] == 'HTTP/1.1 200 OK'){//远程有!!!
				$title = '【'.$lywx.'】'.$ori_title;
				$desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息").' '.$date;
		    // $weObj->music($title , $desc, $musicurl, $musicurl)->reply();
        $resources['key_'.$orikeyword]= array(
          'type'  =>  'music',
          'gakey'   =>  $ori_title,
          'path'  => $path,
          'cache' => 43201,
          'obj'   => array(
            'title' =>  $title,
            'desc'  => $desc,
            'musicurl'  =>  $musicurl,
            'hgmusicurl'  =>  $musicurl,
          ),
        );
        return $resources;
			}
			$offset++;
		}
	}
  $ori_keyword = $keyword;
  if (strpos($ori_keyword,'您好') !== false||
      strpos($ori_keyword,'你好') !== false||
      strpos($ori_keyword,'请') !== false||
      strpos($ori_keyword,'播') !== false||
      strpos($ori_keyword,'哪') !== false||
      strpos($ori_keyword,'我') !== false||
      strpos($ori_keyword,'想') !== false||
      strpos($ori_keyword,'么') !== false||
      strpos($ori_keyword,'吗') !== false||
      strpos($ori_keyword,'几') !== false
    ){
    $weObj->transfer_customer_service()->reply();
    gapushagent('event',array(
     'category'        => 'lywxother',
     'action'          => '转接客服',
     'label'           => 'wxservice_'.$account->uid,
     'value'           => $ori_keyword,
    ));
    return ;
  }

	$allowkeywords = array('0');
	//1. 如輸入”0”時，會自動發送圖文“收听节目代号”。
  if(in_array($keyword, $allowkeywords)){
    $img = array(
      'Title'=>"收听节目代号",
      'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
      'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
      'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=401924143&idx=1&sn=9e7a4f6f8390b6a807060b99e9975c4a#rd',
    );
    $news[] = $img;
    $resources['key_'.$keyword]= array(
      'type'  =>  'news',
      'gadata' => array(
       'category'        => 'lywxother',
       'action'          => '收听节目代号',
       'label'           => $keyword,
       ),
      'cache' =>  0,
      'obj'   =>  $news,
      );
    return $resources;
	}
  //2. 如輸入”0”或節目代號以外的任何數字、英文、符號等，會自動發送圖文“良友知音使用说明”。
  $img = array(
    'Title'=>"良友知音使用说明",
    'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
    'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
    'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=403749894&idx=1&sn=0158a36a4c6d87aed8c7bad66a738791#rd',
  );
  $news[] = $img;
  $resources['key_'.$keyword]= array(
    'type'  =>  'news',
    'gadata' => array(
     'category'        => 'lywxother',
     'action'          => '使用说明',
     'label'           => $keyword,
     ),
    'cache' =>  0,
    'obj'   =>  $news,
    );
  return $resources;
}


/**
 * Hook_wxservice_event_alter
 */
function mp_lywx_wxservice_event_alter($weObj,$event,$account){
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['ly']) && $enabled_resources['ly'])){
    return;
  }
  if(isset($event['key'])){
    mp_service_keyword_response($weObj,$event['key'],$account);
  }
  switch ($event['event']) {
    case 'subscribe':
      $img = array(
        'Title'=>"良友知音使用说明",
        'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
        'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
        'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=403749894&idx=1&sn=0158a36a4c6d87aed8c7bad66a738791#rd',
      );
      $news[] = $img;
      $img = array(
        'Title'=>"收听节目代号",
        'Description'=>"欢迎收听我们的节目！知音‧牵手‧同行 ※ 为你送上精彩节目和活动！",
        'PicUrl'=>'https://mmbiz.qlogo.cn/mmbiz/JkVibryc6qrY4zkXwy5SPZbur1Jd7HMRneGCr0xhsqEJFXyQ0XkTqZmG8xCPIadhCt4GJk0kibtevrUIJ2Wpw7ag/0?wx_fmt=jpeg',
        'Url'=>'http://mp.weixin.qq.com/s?__biz=MzI1MDE0NzM5Ng==&mid=401924143&idx=1&sn=9e7a4f6f8390b6a807060b99e9975c4a#rd',
      );
      $news[] = $img;
      // $weObj->text("亲爱的朋友，你好！感谢你关注良友电台官方订阅号“良友知音”！\n".lywx_menu());
      $weObj->news($news);
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => 'subscribe',
       'label'           => $account->uid,
      ));
      break;
    case 'unsubscribe':
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => 'unsubscribe',
       'label'           => $account->uid,
      ));
      break;
    case 'kf_create_session':
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => '客服会话',
       'label'           => $account->uid,
      ));
      break;
    case 'VIEW'://MP menu!
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => '菜单浏览',
       'label'           => $event['key'],
      ));
      break;
    case 'CLICK'://MP menu!
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => '菜单点击',
       'label'           => $event['key'],
      ));
      break;
    case 'MASSSENDJOBFINISH'://图文发送成功
      gapushagent('event',array(
       'category'        => 'lywxother',
       'action'          => '图文发送成功',
       'label'           => $account->uid,
      ));
      break;
    default:
      watchdog('mp_lywx', '<pre>'.print_r($event['event'], 1), array(), WATCHDOG_NOTICE, 'link');
      break;
  }
}
