<?php
function bbn_audio_list(){	
	$bbn = array();
	$bbn['401'] = array(
		'code'				=>	'C0SER',
		'keyword'			=>	401,
		'day'					=>	0,
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C0SER.m4a',
		'title'				=>	'中信之声',
		'description'	=>	'打开心锁，尽情倾诉，对你的日常生活必定带来很多的帮助和启发',
	);
	$bbn['402'] = array(
		'code'				=>	'C0AS',
		'keyword'			=>	402,
		'day'					=>	7,
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6SWS2.m4a',
		'title'				=>	'主日崇拜（一）',
		'description'	=>	'洛杉矶国语浸信会在张容江牧师的带领下，1963年成立于美国西岸的洛杉矶。1976年钟世豪牧师接掌教会担任主任牧师，国语堂至今增加了两位副牧师，陈世钦牧师和吴子平牧师。感谢上帝丰盛的恩典，教会不断成长，除了设有国语堂崇拜以外，还增加了粤语堂和英语堂的崇拜。洛杉矶国语浸信会全面性，多元性地发展，以真理造就信徒。教会重视信徒的生活学习，每周有家庭小组，定期举办生活专题讲座，退修会，培灵会等来推动信徒追求灵命的成长。教会设有成人诗班，儿童合唱团，以诗歌敬拜赞美真神。洛杉矶浸信会重视信徒子女的培育，设有幼童活动，青少年团契，中文学校等活动，牧养信徒们的子女。',
	);
	$bbn['403'] = array(
		'code'				=>	'C0AS',
		'keyword'			=>	403,
		'day'					=>	7,
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6SWS4.m4a',
		'title'				=>	'主日崇拜（二）',
		'description'	=>	'美国马利兰中华圣经教会成立于一九七六年，目的是要以圣经为本，传扬耶稣基督的福音，使我骨肉之亲的中华同胞，能因信基督耶稣，得着永远的生命。刘传章牧师现任该教会的主任牧师，在该教会已牧会 20年。刘牧师传道生涯已近40年，是个资深讲员。刘牧师育有一子一女。',
	);
	$bbn['404'] = array(
		'code'				=>	'C0AS',
		'keyword'			=>	404,
		'day'					=>	7,
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6SBS.m4a',
		'title'				=>	'主日查经',
		'description'	=>	'黄子嘉牧师是福州人,1962年毕业于台湾成功大学土木工程系,后获台湾中华福音神学院道学硕士，美国三一神学院（Trinity Evangelical Divinity School，Deerfield, IL）神学硕士，及美国康考迪亚神学院（Concordia Seminary，St. Louis, MO）神学博士。曾在台湾牧会7年，在浸信宣道会神学院任教2年，后在中华福音神学院任教16年，期间担任该院之教务主任7年及院长7年。1997年9月1日起担任美国New Jersey州若歌教会（Rutgers Community Christian Church）主任牧师一职至今。',
	);
	$bbn['405'] = array(
		'code'				=>	'C0CBS',
		'keyword'			=>	405,
		'day'					=>	5,//1-5
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6AS.m4a',
		'title'				=>	'儿童圣经故事',
		'description'	=>	'新儿童故事是由圣经广播网提供，用不同的方式来讲述儿童故事。“睡梦乡”故事系列是其中的节目。',
	);
	$bbn['406'] = array(
		'code'				=>	'C6BAW',
		'keyword'			=>	406,
		'day'					=>	6,//6-7
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6AS.m4a',
		'title'				=>	'听听女人心',
		'description'	=>	'周六日播出',
	);
	$bbn['407'] = array(
		'code'				=>	'C0AS',
		'keyword'			=>	407,
		'day'					=>	0,//1-7
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6AS.m4a',
		'title'				=>	'圣经导读',
		'description'	=>	'查经性广播节目，将全本新旧约圣经，逐卷的带领听众朋友查考，适合给基督徒和慕道友',
	);
	$bbn['408'] = array(
		'code'				=>	'C0AS',
		'keyword'			=>	408,
		'day'					=>	0,//1-7
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6AS.m4a',
		'title'				=>	'圣经时光',
		'description'	=>	'每周六播出近60分钟的讲座，并在星期天重播',
	);
	$bbn['409'] = array(
		'code'				=>	'C6BH',
		'keyword'			=>	409,
		'day'					=>	7,//only 6
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6BH.m4a',
		'title'				=>	'圣经时光',
		'description'	=>	'每周六播出近60分钟的讲座，并在星期天重播',
	);	
	$bbn['410'] = array(
		'code'				=>	'C0CP',
		'keyword'			=>	410,
		'day'					=>	16,
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6BH.m4a',
		'title'				=>	'圣经讲坛',
		'description'	=>	'华人教会名牧的讲道专题系列，帮助听众灵命进深，信仰成长',
	);	
	$bbn['411'] = array(
		'code'				=>	'C0BGM',
		'keyword'			=>	411,
		'day'					=>	67,//6 7
		'url'				=>	'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C6BGM.m4a',
		'title'				=>	'天人之间',
		'description'	=>	'由寇世远牧师主讲的节目，深入浅出地运用圣经真理来帮助基督徒灵命成长，也适合慕道友收听',
	);

	return $bbn;
}
function bbn_url($keyword){
	$bbns = bbn_audio_list();
	$bbn = $bbns[$keyword];
	$url_pre = 'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/';
	$weekday = date('N')-1;
	if($bbn['day'] == 7) return $bbn['url'];// only one every week.
	if($bbn['day'] == 67) {//weekend
		$last = date('N')/2?'last Saturday':'last Sunday';
		$weekday = date('N',strtotime("$last", time()))-1;
		$code =str_replace('0', $weekday, $bbn['code']);
		return $url_pre.$code.'.m4a';
	}
	if($bbn['day'] == 16 && $weekday =='6'){//1 2 3 4 5 6
		$weekday == 5;
	}
	$code =str_replace('0', $weekday, $bbn['code']);
	return $url_pre.$code.'.m4a';
}