<?php
/**
 * Implements hook_menu().
 */
function mp_service_menu() {
  $items['user/%user/mp'] = array(
    'title' => '公众号',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_service_settings_form'),
    'access arguments' => array('use mp service'),
    'file' => 'mp_service.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['mp_service/%user'] = array(
    'page callback' => 'mp_service_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),//TODO
    'file' => 'mp_service_pages.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function mp_service_permission() {
  return array(
    'use mp service' =>  array(
      'title' => t('Wechat plus configuration'),
      'description' => t('Wechat plus configuration'),
    ),
  );
}


/**
 * init wechat object
 */
function _mp_service_init_wechat($account){
  $weObj = &drupal_static(__FUNCTION__);
  if(!isset($weObj)){
    module_load_include('php', 'mp_service', 'wechat.class');
    $options = array(
      'token' => variable_get('mp_config_token_'.$account->uid, ""),
      'encodingaeskey'=>variable_get('mp_config_appaes_'.$account->uid, ""),
      'appid' => variable_get('mp_config_appid_'.$account->uid, ""),
      'appsecret' => variable_get('mp_config_appsecret_'.$account->uid, ""),
    );
    $weObj = new Wechat($options);
  }
  return $weObj;
}

/**
 * 
 * //get keyword
 * //return resources[keyword]
 * //switch (type) news
 */
	
function mp_service_keyword_response($weObj,$keyword,$account) {
  if (strlen($keyword) > 10 && variable_get('mp_config_certified_'.$account->uid, false)) { //认证与否
    $weObj->transfer_customer_service()->reply();
  }
  $wxresources = array();  //TODO： get all (enabled)resources/node of account.
  $wxresources = module_invoke_all('wxresources', $wxresources, $account, $keyword);

	// watchdog('11', '<pre>'.print_r($wxresources,true), array(), WATCHDOG_NOTICE, 'link');
	$ori_keyword = $keyword;
	$keyword = 'key_'.$keyword;//1001 => 0 selution.
  if(isset($wxresources[$keyword]))
  switch ($wxresources[$keyword]['type']) {
    case 'music':
    	if(!isset($wxresources[$keyword]['obj']['hgmusicurl']))
    		$wxresources[$keyword]['obj']['hgmusicurl'] = $wxresources[$keyword]['obj']['musicurl'];
      $weObj->music('【'.$ori_keyword.'】'.$wxresources[$keyword]['obj']['title'], $wxresources[$keyword]['obj']['desc'], $wxresources[$keyword]['obj']['musicurl'], $wxresources[$keyword]['obj']['hgmusicurl']);
      break;
    case 'text':
      $weObj->text($wxresources[$keyword]['obj']['text']);
      break;    
    case 'news': 
      $new = array($wxresources[$keyword]['obj']);      
      $weObj->news($new);
      break;
  }
}