<?php
/**
 * Client call this funciton.
 * @param  [type] $type      [description]
 * @param  [type] $push_data [description]
 * @return [type]            [description]
 */
function gapushagent($type,$push_data){
  //if server call. then use default funciton. no sqs round.
  $pos = strpos($_SERVER['HTTP_HOST'], 'staging');
  if($pos != FALSE){
    switch ($type) {
      case 'event':
        ga_push_add_event($push_data);
        break;
      case 'pageview':
        ga_push_add_pageview($push_data);
        break;
      default:
        # code...
        break;
    }
    return;
  }
  // POST data
    // ga_push_add_event($push_data);
    $data = array('data' => drupal_json_encode($push_data), 'type' => 'ga_push_add_event');
    // Server API url
    $url = 'http://wxstaging.yongbuzhixi.com/sqs/api';
    //open connection
    $ch = curl_init();

    //set the url, number of POST vars, POST data
    curl_setopt($ch,CURLOPT_URL, $url);
    curl_setopt($ch,CURLOPT_POST, 2);
    curl_setopt($ch,CURLOPT_POSTFIELDS, http_build_query($data));

    //execute post
    $result = curl_exec($ch);

    //close connection
    curl_close($ch);
    // return 'POST data '.($result?'success!':'faild!');
    $return = 'faild';
    if($result)  $return = 'success';
    return $return;
    // header('Content-Type: application/json');
    // print drupal_json_encode($array);
    // drupal_exit();
  // $data = drupal_json_encode($data);
  // $push_data = 'type='.$type.'&data='.$data;
  // $url = 'http://wxstaging.yongbuzhixi.com/gapushagent';
  // $options = array(
  //   'method' => 'POST',
  //   'data' => $push_data,
  //   'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  // );
  // drupal_http_request($url, $options);
  // // $result =
  // // dpm($result);
}
