<?php
/**
 * Implements hook_menu().
 */
function ybread_menu() {
  $items['lingming'] = array(
    'title' => '灵命日粮',
    'page callback' => 'ybread_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
 $items['lingming/json'] = array(
    'title' => '灵命日粮',
    'page callback' => 'get_last_node',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );

  return $items;
}

/**
 * Implements get_last_node().
 */
function get_last_node($content_type = 'lingming') {
  $query = "SELECT n.nid nid, n.created created FROM {node} n  WHERE n.type = :type order by n.created desc limit 0,1";
  $result = db_query($query, array(':type' => $content_type))->fetch();
  if(isset($result->nid)){
    $nid = $result->nid;
    $node = node_load($nid);
    header('Content-Type: application/json');
    $img = array(
        'Title'=> '【灵命日粮】'.$node->title,
        'Description'=> truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 150, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1),
        'PicUrl'=> file_create_url($node->field_image['und'][0]['uri']),
        'Url'=> url('node/'.$node->nid, array('absolute' => TRUE)),
      );
    // 
    // $news[] = $img;
    print json_encode($img);
    drupal_exit();
    // return ;
  }
}
