<?php
/**
 * Implements hook_menu().
 */
function ybread_menu() {
  $items['lingming'] = array(
    'title' => '灵命日粮',
    'page callback' => 'ybread_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
 $items['lingming/json'] = array(
    'title' => '灵命日粮',
    'page callback' => 'get_last_node_json',
    'page arguments' => array(0,'灵命日粮'),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  $items['grace365'] = array(
    'title' => '恩典365',
    'page callback' => 'grace365_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
 $items['grace365/json'] = array(
    'page callback' => 'get_last_node_json',
    'page arguments' => array(0,'恩典365'),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements get_last_node().
 */
function get_last_node_json($content_type = 'lingming',$title = '灵命日粮',$return=0) {
  $query = "SELECT n.nid nid, n.created created FROM {node} n  WHERE n.type = :type order by n.created desc limit 0, 1";
  $result = db_query($query, array(':type' => $content_type));
  while($record = $result->fetchAssoc()) {
    $nid = $record['nid'];
    $node = node_load($nid);//TODO:fast query!

    if(isset($node->field_image['und'][0]['uri'])){
      $picurl = file_create_url($node->field_image['und'][0]['uri']);   
    }else{//default img!!
      $info = field_info_instance('node', 'field_image2', $content_type);
      if (!empty($info) && $info['settings']['default_image'] > 0){
        $default_img_fid  = $info['settings']['default_image'];
        $default_img_file = file_load($default_img_fid);
      }
      $picurl = file_create_url($default_img_file->uri);  
    }

    $img = array(
      'Title'=> '【'.$title.'】'.$node->title,
      'Description'=> truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 150, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1),
      'PicUrl'=> $picurl,
      'Url'=> url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE)),
    );
  }
  if($return){
    return $img;
  }
  header('Content-Type: application/json');
  print json_encode($img);
  drupal_exit();
}