<?php
/**
 * Implements hook_menu().
 */
function ybread_menu() {
  $items['lingming'] = array(
    'title' => '灵命日粮',
    'page callback' => 'ybread_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
 $items['lingming/json'] = array(
    'title' => '灵命日粮',
    'page callback' => 'get_last_node',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
  $items['grace365'] = array(
    'title' => '恩典365',
    'page callback' => 'grace365_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function ybread_node_view($node, $view_mode, $langcode) {
  if($node->type=='lingming')
    drupal_set_title('灵命日粮-'.$node->title);
}






