<?php
/**
 * hook_rescources_info
 */
function mp_content_rescources_info(){
	$rescources[] = array(
    'name' => 'mp_contents',
    'desc' =>	'云优秀【图文】',
  );
  $rescources[] = array(
    'name' => 'mp_77',
    'desc' => 'FM77【77】',
  );
  $rescources[] = array(
    'name' => 'mp_77_share',
    'desc' => 'FM77【770】',
  );
  // $rescources[] = array(
  //   'name' => 'mp_contents_lianai',
  //   'desc' => '本站图文资源byterm【炼爱】',
  // );
  return $rescources;
}
/**
 * Hook_wxresources
 */
function mp_content_wxresources($resources, $account, $keyword){
  $temp_key = substr($keyword, 0,4);
  $temp_key2 = substr($keyword, 0,2);
  $allow_keys = array('lm','灵命','lingming','tuwen','meiwen','tw','图文','美文','77','node');
  if( !(in_array($keyword, $allow_keys)||in_array($temp_key2, $allow_keys) || in_array($temp_key, $allow_keys)) ) return;
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
    //灵命日粮
    if ($keyword =='tw'||$keyword =='图文') {
      if(isset($enabled_resources['mp_contents']) && $enabled_resources['mp_contents']){
          //TODO: json +cron
          {
            $nodes = dale_get_mp_nodes('article',3,NULL,array(1,$account->uid,'1013'));
            $news = array();
            $count = 0;
            foreach ($nodes as $key => $node) {
              if(isset($node->field_image2['und'][0]['uri'])){
                $picurl = file_create_url($node->field_image2['und'][0]['uri']);
              }elseif(isset($node->field_image['und'][0]['uri'])){
                $picurl = file_create_url($node->field_image['und'][0]['uri']);
              }else{
                $info = field_info_instance('node', 'field_image2', 'article');
                if (!empty($info) && $info['settings']['default_image'] > 0){
                  $default_img_fid  = $info['settings']['default_image'];
                  $default_img_file = file_load($default_img_fid);
                }
                $picurl = file_create_url($default_img_file->uri);
              }
              if($count == 0){//第一个不用2图
                if(isset($node->field_image['und'][0]['uri'])){
                  $picurl = file_create_url($node->field_image['und'][0]['uri']);
                }else{//default img!!
                  $info = field_info_instance('node', 'field_image', 'article');
                  if (!empty($info) && $info['settings']['default_image'] > 0){
                    $default_img_fid  = $info['settings']['default_image'];
                    $default_img_file = file_load($default_img_fid);
                  }
                  $picurl = file_create_url($default_img_file->uri);
                }
              }
              $count++;
              $img = array(
                  'Title'=> $node->title,
                  'Description'=> strlen($node->body[LANGUAGE_NONE][0]['summary'])?truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['summary']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1):truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1),
                  'PicUrl'=> $picurl,
                  'Url'=> url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE)),
                );
              $news[] = $img;
            }
            array_push($news,get_last_node_json('lingming','620',1));
            array_push($news,get_last_node_json('grace365','365',1));
            array_push($news,get_last_node_json('ctoday','421',1));

          }
          $resources['key_'.$keyword]= array(
          'type'  =>  'news',
          'obj'   =>  $news,
          );
      }
    }
    //77001 77002 77003 ... 77999
    $temp_key2 = substr($keyword, 0,2);
    if ($temp_key2 =='77') {
      $offset = 0;
      if(isset($enabled_resources['mp_77']) && $enabled_resources['mp_77']){
          if(strlen($keyword)>2) {
            //get all nodes77 of one content!
            $offset = substr($keyword,2)-1;
            if($offset<0) {
              if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
                $nodes = dale_get_mp_nodes('fm77', 50, $tid = NULL, $uids = array(),NODE_NOT_PROMOTED,NODE_PUBLISHED,"DESC");
              }else{
                $nodes = dale_get_mp_nodes('fm77', 50, $tid = NULL, array($account->uid),NODE_NOT_PROMOTED,NODE_PUBLISHED,"DESC");
              }
              $i = 0;
              $total = count($nodes);
              $text = '';
              foreach ($nodes as $node) {
                $j =  $total-$i;
                $i++;
                if($j>=10&&$j<100) $j=  str_pad($j,2,"0",STR_PAD_LEFT);
                if($j>=100&&$j<1000) $j=  str_pad($j,3,"0",STR_PAD_LEFT);
                $text ="\n【77".(0+$j).'】'.$node->title.$text;
                # code...
              }
              $text = "------已有资源------".$text;
              $resources['key_'.$keyword]= array(
                'type'  =>  'text',
                'obj'   => array(
                  'text' => $text."\n回复编号给我吧！[调皮]",
                ),
              );
              return $resources;
            }

            if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
              $nids = dale_get_mp_nodes_count('fm77', 0, NULL, array(),NODE_PUBLISHED,1);
            }else{
              $nids = dale_get_mp_nodes_count('fm77', 0, NULL, array($account->uid),NODE_PUBLISHED,1);
            }
            $nids =  array_reverse($nids);
            $total = count($nids);
            if($offset<$total){
              // watchdog($offset, 'offset'.$total, array(), WATCHDOG_NOTICE, 'link');
              $node = node_load($nids[$offset]->nid);
              // watchdog($offset.' '.$node->title, $node->nid, array(), WATCHDOG_NOTICE, 'link');
              if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value']))
                $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
              if(!isset($musicurl)){
                //TODO $node->field_mp3_file
               $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
              }
              $resources['key_'.$keyword]= array(
                'type'  =>  'music',
                'obj'   => array(
                  'title' => $node->title,
                  'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                  'musicurl'  =>  $musicurl,
                  'hgmusicurl'  =>  $musicurl,
                ),
              );
              return $resources;
            }else{
              // '暂无此资源！';
              $resources['key_'.$keyword]= array(
                'type'  =>  'text',
                'obj'   => array(
                  'text' => "[调皮]没有啦！",
                ),
              );
              return $resources;
            }
          }else{//77
          //TODO 是否需要共享资源？
          if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
            $nodes = dale_get_mp_nodes('fm77',1,NULL);
          }else{
            $nodes = dale_get_mp_nodes('fm77',1,NULL,array($account->uid));
          }
          if (count($nodes))
          foreach ($nodes as $key => $node) {
            $musicurl = NULL;
            if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value']))
              $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
            if(!$musicurl){
              //TODO $node->field_mp3_file
             $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
            }
            $resources['key_'.$keyword]= array(
              'type'  =>  'music',
              'obj'   => array(
                'title' => $node->title,
                'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                'musicurl'  =>  $musicurl,
                'hgmusicurl'  =>  $musicurl,
              ),
            );
          }
          }
          //TODO 是否需要共享资源？
          if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
            $nodes = dale_get_mp_nodes('fm77',1,NULL);
          }else{
            $nodes = dale_get_mp_nodes('fm77',1,NULL,array($account->uid));
          }
          if (count($nodes))
          foreach ($nodes as $key => $node) {
            $musicurl = NULL;
            if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value']))
              $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
            if(!$musicurl){
              //TODO $node->field_mp3_file
             $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
            }
            $resources['key_'.$keyword]= array(
              'type'  =>  'music',
              'obj'   => array(
                'title' => $node->title,
                'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                'musicurl'  =>  $musicurl,
                'hgmusicurl'  =>  $musicurl,
              ),
            );
          }
      }
    }
    if($keyword =='node'){
      $nid = substr($keyword, 4);
      if(is_numeric($nid)){
        $node = node_load($nid);
        if ($node->nid && $node->type == 'article') {
          $pic = file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']);
           $img = array(
                'Title'=> $node->title,
                'Description'=> $node->body[LANGUAGE_NONE][0]['value'],
                'PicUrl'=>$pic,
                'Url'=> $node->field_link[LANGUAGE_NONE][0]['value'] ,
              );
            $news[] = $img;
            // if(in_array($keyword, array_keys($get_ybzx_resources)))
            $resources['key_'.$keyword]= array(
            'type'  =>  'news',
            'obj'   =>  $news,
            );
        }
      }
    }

	}
	return $resources;
}
/**
 * $number = 0 ＝＝ALL
 * get all nodes77 of one content!
 * $return = 1 get all nids!
 */
function dale_get_mp_nodes_count($type = 'article', $number = 0, $tid = NULL, $uids = array(),$publish = NODE_PUBLISHED,$return = NULL,$order="DESC"){
  $query = db_select('node', 'n');
  $query->condition('n.status', $publish);
  $query->condition('n.type', $type);
  // $query->condition('n.promote', $promote);
  if($uids)
    $query->condition('n.uid', $uids,'IN');
  if($number!=0)
     $query->range(0, $number);

  if($return) return $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchAll();
  $result = $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', $order)
    ->addTag('node_access')
    ->execute();

  return $result->rowCount();
}

/**
 * get recently create contents of articles!!!
 * by termID
 * must has pics (已配图)
 * @see node_get_recent
 */
function dale_get_mp_nodes($type = 'article', $number = 3, $tid = NULL, $uids = array(), $promote = NODE_NOT_PROMOTED, $publish = NODE_PUBLISHED,$order="DESC"){
  $query = db_select('node', 'n');
  $query->condition('n.status', $publish);
  $query->condition('n.type', $type);
  $query->condition('n.promote', $promote);
  if($uids)
    $query->condition('n.uid', $uids,'IN');
  if($number!=0)
     $query->range(0, $number);

  $nids = $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', $order)
    ->addTag('node_access')
    ->execute()
    ->fetchCol();
  $nodes = node_load_multiple($nids);
  return $nodes ? $nodes : array();
}

/**
 * default 图文！
  // 1.news*1
  // 2.promoted article*1
  // 4.资源列表
 */
function mp_content_wxservice_default_msg_alter($weObj, $keyword, $account){
  //set 自动图文！
  if(variable_get('wechat_multi_message_'.$account->uid, "")){
    $counts = explode(':', variable_get('wechat_multi_message_count_'.$account->uid, "1:1:1"));
    $news = array();
    //get newest
    if($counts[0]!=0)
      $nodes = dale_get_mp_nodes('article',$counts[0],NULL,array($account->uid),NODE_NOT_PROMOTED);
    $count = 0;
    if(isset($nodes)){
      foreach ($nodes as $key => $node) {
        if(!empty($node->field_redirect_link['und'][0]['value'])){
          $url = $node->field_redirect_link['und'][0]['value'];
        }else{
          $url = url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE));
        }

        if(isset($node->field_image2['und'][0]['uri'])){
          $picurl = file_create_url($node->field_image2['und'][0]['uri']);
        }elseif(isset($node->field_image['und'][0]['uri'])){
          $picurl = file_create_url($node->field_image['und'][0]['uri']);
        }else{
          $picurl = file_create_url($account->picture->uri);
        }
        $count++;
        if($count == count($nodes)){//第一个不用2图
        if(isset($node->field_image['und'][0]['uri'])){
          $picurl = file_create_url($node->field_image['und'][0]['uri']);
        }else{//default img!!
          $info = field_info_instance('node', 'field_image', 'article');
          if (!empty($info) && $info['settings']['default_image'] > 0){
            $default_img_fid  = $info['settings']['default_image'];
            $default_img_file = file_load($default_img_fid);
          }
          $picurl = file_create_url($default_img_file->uri);
        }
        }
        $desc = strlen($node->body[LANGUAGE_NONE][0]['summary'])?truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['summary']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1):truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);
        $img = array(
          'Title'=> $node->title,
          'Description'=>$desc,
          'PicUrl'=> $picurl,
          'Url'=> $url,
        );
        $news[] = $img;
      }
      $news = array_reverse($news);
    }


    //get promote!
    if($counts[1]>0)
      $nodes2 = dale_get_mp_nodes('article',$counts[1],NULL,array($account->uid),NODE_PROMOTED);
    if(isset($nodes2))
    foreach ($nodes2 as $key => $node) {
      if(!empty($node->field_redirect_link['und'][0]['value'])){
        $url = $node->field_redirect_link['und'][0]['value'];
      }else{
        $url = url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE));
      }
      $desc = strlen($node->body[LANGUAGE_NONE][0]['summary'])?truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['summary']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1):truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);
      //大于1个节点图文
      if($count && isset($node->field_image2['und'][0]['uri'])){
        $picurl = file_create_url($node->field_image2['und'][0]['uri']);
      }
      if(isset($node->field_image['und'][0]['uri']) && $counts[0]==0){
        $picurl = file_create_url($node->field_image['und'][0]['uri']);
      }
      if(!$picurl){
        $picurl = file_create_url($account->picture->uri);
      }

      $img = array(
          'Title'=> $node->title,
          'Description'=>$desc,
          'PicUrl'=> $picurl,//file_create_url($node->field_image['und'][0]['uri']),
          'Url'=> $url,
        );
      $news[] = $img;
      $count++;
    }
    //显示底部！
    if($counts[2]!=0){
      $img = array(
        'Title'=>copyright($account),
        'Description'=>'',
        'PicUrl'=>'',
        'Url'=>variable_get('mp_config_default_url_'.$account->uid, ""),
      );
      $news[] = $img;
    }
    $weObj->news($news)->reply();
  }
}

function mp_getwxcontent($link,$wx_openid,$weObj){
  $arrContextOptions=array(
      "ssl"=>array(
          "verify_peer"=>false,
          "verify_peer_name"=>false,
      ),
  );
  $ori_html = file_get_contents($link, false, stream_context_create($arrContextOptions));
  $html = str_get_html($ori_html);
  // $html = file_get_html($link);
  $ori_title = $html->find('title',0)->plaintext;

  preg_match('/var user_name = "(\S+)"/',  $ori_html , $matchs);
  if(!isset($matchs[1])){
    $weObj->text("啊喔，出错了，请再试一次.")->reply();
    return;
  }
  $user_name = $matchs[1];//gh_01f807be5d1b
  // $wechat_profile_nickname = $html->find('.profile_nickname',0)->plaintext;
  // $wechat_profile_qrcode = $html->find('#js_profile_qrcode_img',0)->src;
  $mpwechats = variable_get('mp_contents_mpwechats', array());
  if(!in_array($user_name, $mpwechats)){
    // $html = file_get_contents($html);
    preg_match('/var nickname = "(\S+)"/',  $ori_html , $matchs);
    $nickname = $matchs[1];//生活无国界
    // preg_match('/var fakeid   = "(\S+)"/',  $ori_html , $matchs);
    preg_match('/var appuin = "(\S+)"/',  $ori_html , $matchs);
    $fakeid = $matchs[1];//MTYyMjI5NjYwMA==
    $fakeid = str_replace('"||"', '', $fakeid);
    preg_match('/hd_head_img : "(\S+)0"/',  $ori_html , $matchs);
    $hd_head_img = $matchs[1];//http://wx.qlogo.cn/mmhead/Q3auHgzwzM61GZDBsZt7uZVk3iacQ5YUsWS2hTrSXs0Vul6NYU3Hh3A/0
    $wechat_profile_qrcode = 'https://mp.weixin.qq.com/mp/qrcode?scene=10000005&size=502&__biz='.$fakeid;//https://mp.weixin.qq.com/mp/qrcode?scene=10000004&size=102&__biz=MjM5MTA4MzQ0MA==
    $wechat_profile_account = $html->find('.profile_meta .profile_meta_value',0)->plaintext;//shenghuowuguojie
    $wechat_profile_intro = $html->find('.profile_meta .profile_meta_value',1)->plaintext;
    //小心，听了会上瘾！
    save_mpwechat_node($nickname,$user_name,$hd_head_img,$wechat_profile_qrcode,$wechat_profile_account,$wechat_profile_intro,$link);
    $mpwechats[] = $user_name;
    variable_set('mp_contents_mpwechats', $mpwechats);
    $weObj->text("登记公众号成功，要发布文章请再试一次！谢谢！[握手]")->reply();
    return;
  }

  $search =  array('&nbsp;');
  $replace =  array(' ');
  $ori_title = str_replace($search, $replace, $ori_title);
  $mp_contents = variable_get('mp_contents_'.date('W'), array());
  if(in_array($ori_title, $mp_contents)){
    if(isset($weObj))
      $weObj->text("本文章已发布过！谢谢！[握手]")->reply();
  }
  if($html->find('.video_iframe',0)){
    $video_url = $html->find('.video_iframe',0)->getAttribute('data-src');
    preg_match('/vid=\S+?&/',$video_url,$video_url);
    // $video_url = 'https://v.qq.com/iframe/player.html?'.str_replace('&', '', $video_url[0]);
    // dpm($video_url);//https://v.qq.com/iframe/player.html?vid=r01794fedmo
    $video_url = str_replace('&', '', $video_url[0]);
    $video_url = str_replace('vid=', '', $video_url);
    // $arr = array('&'=>'','vid='=>'');
    // $video_url = strtr($video_url, $arr);
  }
  if($html->find('mpvoice',0)){
    $voice_url = 'http://res.wx.qq.com/voice/getvoice?mediaid='.$html->find('mpvoice',0)->voice_encode_fileid;
  }

  $body = $html->find('#js_content',0)->outertext;
  $body = strip_tags($body,'<span><p><ul><li><ol><br><section>');
  $body = preg_replace('/style="(.*?)"/', '', $body);
  $body = preg_replace('/class="(.*?)"/', '', $body);
  $body = preg_replace('/label="(.*?)"/', '', $body);
  $body = preg_replace('/data-id="(.*?)"/', '', $body);
  $body = str_replace('<p>&nbsp;</p>', '', $body);
  $body = str_replace('<section>&nbsp;</section>', '', $body);
  $body = str_replace('<p><br /></p>', '', $body);
  $body = str_replace('&nbsp;', '', $body);

  preg_match('/var msg_desc = "(\S+)"/',  $ori_html , $matchs);
  $summary = $matchs[1];

  if(strpos($body, 'MUSTARD SEED')!==FALSE){
    $begin = 0;
    $end = strpos($body, 'MUSTARD SEED');;
    $body = substr($body,$begin,$end-$begin);
  }
  $field_user_name = $html->find('#post-user',0)->plaintext;


  $title = str_replace('&quot;', '"', $ori_title);
  $node = new stdClass();
  $node->type = 'article';
  if(strpos($ori_title, '恩典365')!==FALSE){
    $node->type = 'grace365';
    $node->promote = 1;
    // get title
    $search =  array('&nbsp;','〔恩典365〕','(附文字版)','/','【恩典365】');
    $replace =  array(' ','','','','',);
    $title = str_replace($search, $replace, $ori_title);
  // get $body
    $begin = strpos($body, '恩典365 365天') + strlen('恩典365 365天 ');
    if(!$begin){
      watchdog('ybread', 'no 365', array(), WATCHDOG_NOTICE, 'link');
      return 'error!';
    }
    $end = strpos($body, '恩典365微信公众');
    $body = substr($body,$begin,$end-$begin);
  }else{
    $tid = 46;
  }
  node_object_prepare($node);
  //get title
  $uid = '8'; //uid of love.
  $account = user_load_by_name($user_name);
  if($account){
    $uid = $account->uid;
  }elseif(isset($weObj)){
    $openid = $weObj->getRev()->getRevFrom();
    $user_info = $weObj->getUserInfo($openid);
    $ori_user_name = mp_strip_utf8mb4_for_text_fields($user_info['nickname'],'?');
    $user_name = $ori_user_name;
    $user_info['nickname'] = $ori_user_name;
    //if 用户不存在，则创建新用户！
    $mail = $user_info['openid'].'@wechat.bind';
    $account = user_load_by_mail($mail);
    if($account){
      $uid = $account->uid;
    }
  }
  if(strpos($title, '王明道')!==FALSE){
    $uid = '2503'; //uid of love.
  }
  $node->uid = $uid;
  $node->title = $title;
  $node->field_title[LANGUAGE_NONE][0]['value'] = $ori_title;//原文标题
  $node->field_sourcex[LANGUAGE_NONE][0]['value'] = $field_user_name;//文章来源
  $node->field_link[LANGUAGE_NONE][0]['value'] = $link;//原文链接
  $node->field_user_name[LANGUAGE_NONE][0]['value'] = $field_user_name;//原文作者
  $node->field_wx_openid[LANGUAGE_NONE][0]['value'] = $wx_openid;//收集义工ID TODO＝get_uid_from_openID

  $node->body[LANGUAGE_NONE][0]['value'] = $body;//trim($tempbody->plaintext);
  $node->body[LANGUAGE_NONE][0]['summary'] = $summary;
  if(isset($voice_url))
    $node->field_mp3url[LANGUAGE_NONE][0]['value']=$voice_url;
  if(isset($video_url)){
    $node->field_video_url[LANGUAGE_NONE][0]['value']=$video_url;
    if($node->type!=='grace365')
      $node->field_updated[LANGUAGE_NONE][0]['value']=1;
  }
  if(isset($tid))
    $node->field_term[LANGUAGE_NONE][0]['tid']=$tid;
  $node->language = LANGUAGE_NONE;
  $node->body[LANGUAGE_NONE][0]['format'] = 'full_html';
  // dpm($node);
  node_save($node);
  $mp_contents[]  = $ori_title;
  variable_set('mp_contents_'.date('W'), $mp_contents);
  $node_link = l(t('view'), 'node/' . $node->nid);
  $watchdog_args = array('@type' => $node->type, '%title' => $node->title);
  watchdog('mpcontent', '@type: added %title.', $watchdog_args, WATCHDOG_NOTICE, $node_link);

  if(isset($weObj))
    $weObj->text("<a href='http://wx.yongbuzhixi.com/node/".$node->nid."'>".$node->title."</a>已发布成功！谢谢！[握手]\n<a href='http://wx.yongbuzhixi.com/node/".$node->nid."/edit'>编辑</a>")->reply();
}

function save_mpwechat_node($nickname,$user_name,$hd_head_img,$wechat_profile_qrcode,$wechat_profile_account,$wechat_profile_intro,$link){
  $node = new stdClass();
  $node->type = 'mpwechat';
  $node->uid = 1;
  $node->title = str_replace('&nbsp;', '', $nickname);
  $node->field_redirect_link[LANGUAGE_NONE][0]['value'] = $link;//原文链接

  // $response = drupal_http_request($hd_head_img);
  // watchdog('pic_url1', $hd_head_img, array(), WATCHDOG_NOTICE, 'link');
  // if ($response->code == 200){
  //   $file = file_save_data($response->data, 'public://images/mpwechat/logo/'.$user_name.'.jpg');
  // }
  // $node->field_image[LANGUAGE_NONE][0]['fid']=$file->fid;
  // $response = drupal_http_request($wechat_profile_qrcode);
  // watchdog('pic_url2', $hd_head_img, array(), WATCHDOG_NOTICE, 'link');
  // if ($response->code == 200){
  //   $file = file_save_data($response->data, 'public://images/mpwechat/qrcode/'.$user_name.'.jpg');
  // }
  // $node->field_image2[LANGUAGE_NONE][0]['fid']=$file->fid;
  $node->field_user_name[LANGUAGE_NONE][0]['value'] = $user_name;
  $node->field_link[LANGUAGE_NONE][0]['value']=$hd_head_img;
  $node->field_link[LANGUAGE_NONE][1]['value']=$wechat_profile_qrcode;
  $node->body[LANGUAGE_NONE][0]['value'] = $wechat_profile_intro;
  $node->body[LANGUAGE_NONE][0]['format'] = 'full_html';
  $node->language = LANGUAGE_NONE;
  $node->comment = 2;
  // dpm($node);
  watchdog('mpwechat', 'account created:'.$nickname, array(), WATCHDOG_NOTICE, 'link');
  node_save($node);
}
