<?php
/**
 * hook_rescources_info
 */
function mp_content_rescources_info(){
	$rescources[] = array(
    'name' => 'mp_contents',
    'desc' =>	'云优秀【图文】',
  );
  $rescources[] = array(
    'name' => 'mp_77',
    'desc' => 'FM77【77】',
  );
  $rescources[] = array(
    'name' => 'mp_77_share',
    'desc' => 'FM77共享',
  );
  // $rescources[] = array(
  //   'name' => 'mp_contents_lianai',
  //   'desc' => '本站图文资源byterm【炼爱】',
  // );
  return $rescources;
}
/**
 * Hook_wxresources
 */
function mp_content_wxresources($resources, $account, $keyword){
  $temp_key = substr($keyword, 0,4);
  $temp_key2 = substr($keyword, 0,2);
  $allow_keys = array('lm','灵命','lingming','tuwen','meiwen','tw','图文','美文','77','node');
  if( !(in_array($keyword, $allow_keys)||in_array($temp_key2, $allow_keys) || in_array($temp_key, $allow_keys)) ) return;
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
    //灵命日粮
    if ($keyword == 'lm'||$keyword =='灵命'||$keyword =='美文'||$keyword =='tw'||$keyword =='图文') {      
      if(isset($enabled_resources['mp_contents']) && $enabled_resources['mp_contents']){      
          if($keyword == 'lm'||$keyword =='灵命'){
            $lingming = file_get_contents('http://wx.yongbuzhixi.com/lingming/json');
            $news = (array)json_decode($lingming);
          }else{
            $nodes = dale_get_mp_nodes('article',3,NULL,array(1,$account->uid,'1013'));
            $news = array();
            $count = 0;
            foreach ($nodes as $key => $node) {       
              if(isset($node->field_image2['und'][0]['uri'])){
                $picurl = file_create_url($node->field_image2['und'][0]['uri']);
              }elseif(isset($node->field_image['und'][0]['uri'])){
                $picurl = file_create_url($node->field_image['und'][0]['uri']);
              }else{
                $info = field_info_instance('node', 'field_image2', 'article');
                if (!empty($info) && $info['settings']['default_image'] > 0){
                  $default_img_fid  = $info['settings']['default_image'];
                  $default_img_file = file_load($default_img_fid);
                }
                $picurl = file_create_url($default_img_file->uri);  
              }
              if($count == 0){//第一个不用2图
                if(isset($node->field_image['und'][0]['uri'])){
                  $picurl = file_create_url($node->field_image['und'][0]['uri']);   
                }else{//default img!!
                  $info = field_info_instance('node', 'field_image', 'article');
                  if (!empty($info) && $info['settings']['default_image'] > 0){
                    $default_img_fid  = $info['settings']['default_image'];
                    $default_img_file = file_load($default_img_fid);
                  }
                  $picurl = file_create_url($default_img_file->uri);  
                }
              }
              $count++;
              $img = array(
                  'Title'=> $node->title,
                  'Description'=> strlen($node->body[LANGUAGE_NONE][0]['summary'])?truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['summary']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1):truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1),
                  'PicUrl'=> $picurl,
                  'Url'=> url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE)),
                );
              $news[] = $img;
            }
            // $news = array_reverse($news);
            $lingming = file_get_contents('http://wx.yongbuzhixi.com/lingming/json');
            array_push($news,(array)json_decode($lingming));
            $lingming = file_get_contents('http://wx.yongbuzhixi.com/grace365/json');
            array_push($news,(array)json_decode($lingming));
          }
          $resources['key_'.$keyword]= array(
          'type'  =>  'news',
          'obj'   =>  $news,
          );
      }
    }
    //77001 77002 77003 ... 77999
    $temp_key2 = substr($keyword, 0,2);
    if ($temp_key2 =='77') {
      $offset = 0;
      if(isset($enabled_resources['mp_77']) && $enabled_resources['mp_77']){
          if(strlen($keyword)>2) {
            //get all nodes77 of one content!
            $offset = substr($keyword,2)-1;
            if($offset<0) {
              $text = "------已有资源------";
              if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
                $nodes = dale_get_mp_nodes('fm77', 0, $tid = NULL, $uids = array(),NODE_NOT_PROMOTED,NODE_PUBLISHED,"DESC");
              }else{
                $nodes = dale_get_mp_nodes('fm77', 0, $tid = NULL, array($account->uid),NODE_NOT_PROMOTED,NODE_PUBLISHED,"DESC");
              }
              $i = 0;
              $total = count($nodes);
              foreach ($nodes as $node) {
                $j =  $total-$i;
                $i++;
                if($j>=10&&$j<100) $j=  str_pad($j,2,"0",STR_PAD_LEFT);
                if($j>=100&&$j<1000) $j=  str_pad($j,3,"0",STR_PAD_LEFT);
                $text .="\n【77".(0+$j).'】'.$node->title;
                # code...
              }
              $resources['key_'.$keyword]= array(
                'type'  =>  'text',
                'obj'   => array(
                  'text' => $text."\n回复编号给我吧！[调皮]",
                ),
              );
              return $resources;
            }

            if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
              $nids = dale_get_mp_nodes_count('fm77', 0, NULL, array(),NODE_PUBLISHED,1);
            }else{
              $nids = dale_get_mp_nodes_count('fm77', 0, NULL, array($account->uid),NODE_PUBLISHED,1);
            }
            $nids =  array_reverse($nids);
            $total = count($nids);
            if($offset<$total){
              // watchdog($offset, 'offset'.$total, array(), WATCHDOG_NOTICE, 'link');
              $node = node_load($nids[$offset]->nid);
              // watchdog($offset.' '.$node->title, $node->nid, array(), WATCHDOG_NOTICE, 'link');
              if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value'])) 
                $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
              if(!$musicurl){
                //TODO $node->field_mp3_file
               $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
              }
              $resources['key_'.$keyword]= array(
                'type'  =>  'music',
                'obj'   => array(
                  'title' => $node->title,
                  'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                  'musicurl'  =>  $musicurl,
                  'hgmusicurl'  =>  $musicurl,
                ),
              );
              return $resources;
            }else{
              // '暂无此资源！';
              $resources['key_'.$keyword]= array(
                'type'  =>  'text',
                'obj'   => array(
                  'text' => "[调皮]没有啦！",
                ),
              );
              return $resources;
            }
          }else{//77
          //TODO 是否需要共享资源？
          if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
            $nodes = dale_get_mp_nodes('fm77',1,NULL);  
          }else{
            $nodes = dale_get_mp_nodes('fm77',1,NULL,array($account->uid));
          }
          if (count($nodes))
          foreach ($nodes as $key => $node) {
            $musicurl = NULL;
            if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value'])) 
              $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
            if(!$musicurl){
              //TODO $node->field_mp3_file
             $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
            }
            $resources['key_'.$keyword]= array(
              'type'  =>  'music',
              'obj'   => array(
                'title' => $node->title,
                'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                'musicurl'  =>  $musicurl,
                'hgmusicurl'  =>  $musicurl,
              ),
            );            
          }
          }
          //TODO 是否需要共享资源？
          if(isset($enabled_resources['mp_77_share']) && $enabled_resources['mp_77_share']){
            $nodes = dale_get_mp_nodes('fm77',1,NULL);  
          }else{
            $nodes = dale_get_mp_nodes('fm77',1,NULL,array($account->uid));
          }
          if (count($nodes))
          foreach ($nodes as $key => $node) {
            $musicurl = NULL;
            if(isset($node->field_mp3url[LANGUAGE_NONE][0]['value'])) 
              $musicurl =  $node->field_mp3url[LANGUAGE_NONE][0]['value'];
            if(!$musicurl){
              //TODO $node->field_mp3_file
             $musicurl = file_create_url($node->field_mp3_file[LANGUAGE_NONE][0]['uri']);
            }
            $resources['key_'.$keyword]= array(
              'type'  =>  'music',
              'obj'   => array(
                'title' => $node->title,
                'desc'  =>  strtoupper($node->type) .' 公众号：'.variable_get('mp_config_appname_'.$account->uid, '永不止息'),
                'musicurl'  =>  $musicurl,
                'hgmusicurl'  =>  $musicurl,
              ),
            );            
          }
      }
    }
    if($keyword =='node'){
      $nid = substr($keyword, 4);
      if(is_numeric($nid)){
        $node = node_load($nid);
        if ($node->nid && $node->type == 'article') {
          $pic = file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']);
           $img = array(
                'Title'=> $node->title,
                'Description'=> $node->body[LANGUAGE_NONE][0]['value'],
                'PicUrl'=>$pic,
                'Url'=> $node->field_link[LANGUAGE_NONE][0]['value'] ,
              );
            $news[] = $img;
            // if(in_array($keyword, array_keys($get_ybzx_resources)))
            $resources['key_'.$keyword]= array(
            'type'  =>  'news',
            'obj'   =>  $news,
            );
        }
      }
    }

	}
	return $resources;
}
/**
 * $number = 0 ＝＝ALL
 * get all nodes77 of one content!
 * $return = 1 get all nids!
 */
function dale_get_mp_nodes_count($type = 'article', $number = 0, $tid = NULL, $uids = array(),$publish = NODE_PUBLISHED,$return = NULL,$order="DESC"){
  $query = db_select('node', 'n');
  $query->condition('n.status', $publish);
  $query->condition('n.type', $type);
  // $query->condition('n.promote', $promote);
  if($uids)
    $query->condition('n.uid', $uids,'IN');
  if($number!=0)
     $query->range(0, $number);
  
  if($return) return $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchAll();
  $result = $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', $order)
    ->addTag('node_access')
    ->execute();
  
  return $result->rowCount();
}

/**
 * get recently create contents of articles!!!
 * by termID
 * must has pics (已配图)
 * @see node_get_recent
 */
function dale_get_mp_nodes($type = 'article', $number = 3, $tid = NULL, $uids = array(), $promote = NODE_NOT_PROMOTED, $publish = NODE_PUBLISHED,$order="DESC"){
  $query = db_select('node', 'n');
  $query->condition('n.status', $publish);
  $query->condition('n.type', $type);
  $query->condition('n.promote', $promote);
  if($uids)
    $query->condition('n.uid', $uids,'IN');
  if($number!=0)
     $query->range(0, $number);
  
  $nids = $query
    ->fields('n', array('nid'))
    ->orderBy('n.created', $order)
    ->addTag('node_access')
    ->execute()
    ->fetchCol();
  $nodes = node_load_multiple($nids);
  return $nodes ? $nodes : array();
}

/**
 * default 图文！
  // 1.news*1
  // 2.promoted article*1
  // 4.资源列表
 */
function mp_content_wxservice_default_msg_alter($weObj, $keyword, $account){
  //set 自动图文！
  if(variable_get('wechat_multi_message_'.$account->uid, "")){
    $counts = explode(':', variable_get('wechat_multi_message_count_'.$account->uid, "1:1:1"));
    $news = array();
    //get newest
    $nodes = dale_get_mp_nodes('article',$counts[0],NULL,array($account->uid),NODE_NOT_PROMOTED);
    $count = 0;
    if($nodes)
    foreach ($nodes as $key => $node) { 
      if(!empty($node->field_redirect_link['und'][0]['value'])){
        $url = $node->field_redirect_link['und'][0]['value'];
      }else{
        $url = url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE));
      }      
      if(isset($node->field_image2['und'][0]['uri'])){
        $picurl = file_create_url($node->field_image2['und'][0]['uri']);
      }elseif(isset($node->field_image['und'][0]['uri'])){
        $picurl = file_create_url($node->field_image['und'][0]['uri']);
      }
      $count++;
      if($count == count($nodes)){//第一个不用2图
        if(isset($node->field_image['und'][0]['uri'])){
          $picurl = file_create_url($node->field_image['und'][0]['uri']);   
        }else{//default img!!
          $info = field_info_instance('node', 'field_image', 'article');
          if (!empty($info) && $info['settings']['default_image'] > 0){
            $default_img_fid  = $info['settings']['default_image'];
            $default_img_file = file_load($default_img_fid);
          }
          $picurl = file_create_url($default_img_file->uri);  
        }
      }
      $img = array(
          'Title'=> $node->title,
          'Description'=>strlen($node->body[LANGUAGE_NONE][0]['summary'])?truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['summary']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1):truncate_utf8(strip_tags($node->body[LANGUAGE_NONE][0]['value']), 54, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1),
          'PicUrl'=> $picurl,
          'Url'=> $url,
        );
      $news[] = $img;
    } 
    $news = array_reverse($news);

    //get promote!
    if($counts[1]>0)
      $nodes2 = dale_get_mp_nodes('article',$counts[1],NULL,array($account->uid),NODE_PROMOTED);
    if(isset($nodes2))
    foreach ($nodes2 as $key => $node) {     
      if(!empty($node->field_redirect_link['und'][0]['value'])){
        $url = $node->field_redirect_link['und'][0]['value'];
      }else{
        $url = url('node/'.$node->nid, array('absolute' => TRUE,'alias'=>TRUE));
      }
      $img = array(
          'Title'=> $node->title,
          'Description'=> $node->title,
          'PicUrl'=> file_create_url($node->field_image['und'][0]['uri']),
          'Url'=> $url,
        );
      $news[] = $img;
    }
    //显示底部！
    if($counts[2]!=0){
      $img = array(
        'Title'=>strip_tags(copyright($account)),
        'Description'=>'',
        'PicUrl'=>'',
        'Url'=>variable_get('mp_config_default_url_'.$account->uid, ""),
      );
      $news[] = $img;
    }
    $weObj->news($news)->reply();
  }
}