<?php
/**
 * hook_rescources_info
 */
function mp_ybzx_rescources_info(){
	$rescources[] = array(
    'name' => 'ybzx',
    'desc' =>	'永不止息共享资源【1001】',
  );
  return $rescources;
}
/**
 * Hook_wxresources
 */
function mp_ybzx_wxresources($resources, $account, $keyword){
	//TODO： get_all_articles!!!
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
	// watchdog('enabled_resources', '<pre>'.print_r($enabled_resources,true), array(), WATCHDOG_NOTICE, 'link');
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
  	if(isset($enabled_resources['ybzx']) && $enabled_resources['ybzx']){  		
			  require_once('ybzx_resources.php');
		  	//10010
		  	$check_keyword = substr($keyword, 0, 4);
		  	//1001-1030 婚姻辅导
				$get_ybzx_resources = get_ybzx_resources_hyfd();
		  	if(in_array($check_keyword, array_keys($get_ybzx_resources))){
		  		//1001-1030
					if (strlen($keyword) == 5) {
				  	$news = get_ybzx_dstw();
						$index = substr($keyword, 3, 1) - 1;
						$resources['key_'.$keyword]= array(
							'type'	=>	'news',
							'obj'		=>  array($news[$index]),
						);
					}else{//10010-10060
						$resources['key_'.$keyword]= array(
							'type'	=>	'music',
							'obj'		=>  $get_ybzx_resources[$keyword],
						);
					}

		  	}
  	}
  	
	}
	return $resources;
}


/**
 * Hook_wxservice_event_alter
 */
function mp_ybzx_wxservice_event_alter($weObj){

}
