<?php
/**
 * Implements hook_preprocess_page().
 */
function wxjs_preprocess_page(&$variables) {
  if(arg(0)=='admin') return;
  drupal_add_js('http://res.wx.qq.com/open/js/jweixin-1.0.0.js', 'external');
  require_once "jssdk.php";
  $appid = variable_get('mp_config_appid_8', "");
  $appsecret = variable_get('mp_config_appsecret_8', "");
  $jssdk = new JSSDK($appid, $appsecret);
  $signPackage =  $jssdk->GetSignPackage();
  if(!isset($variables['node'])){
    $shareData = array(
      'title'=> variable_get('site_name', '永不止息'),
      'desc'=> variable_get('site_slogan', '主内公众云提供技术支持'),
      'link'=> "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
      'imgUrl'=> theme_get_setting('logo'),
    );
    drupal_add_js(array('wxjs' => array('shareData'=>$shareData)), 'setting');
  }
  drupal_add_js(array('wxjs' => array('signPackage' => $signPackage)), 'setting');
  drupal_add_js(drupal_get_path('module', 'wxjs').'/wx.config.js');
  drupal_add_js(drupal_get_path('module', 'wxjs').'/demo.js');
}

/**
 * Implements hook_node_view().
 */
function wxjs_node_view($node, $view_mode, $langcode) {
  if($view_mode=='full'){
    //2图没有用1图，1图没有用用户图 最后2图默认值！
    $picurl = '';
    // dvm(strpos($node->field_image2['und'][0]['uri'],'default_images'));
    if(isset($node->field_image2['und'][0])&&strpos($node->field_image2['und'][0]['uri'],'default_images')==FALSE){
      $picurl = file_create_url($node->field_image2['und'][0]['uri']);
    }
    if(isset($node->field_image['und'])&&$node->field_image['und'][0]&&strpos($node->field_image['und'][0]['uri'],'default_images')==FALSE){
      $picurl = file_create_url($node->field_image['und'][0]['uri']);
    }elseif(variable_get('user_pictures', 0)){
      if ($node->picture){
        $imgpath = file_load($node->picture)->uri;
        $picurl = file_create_url($imgpath);
      }
    }
    if(!$picurl){
      $info = field_info_instance('node', 'field_image2', 'article');
      if (!empty($info) && $info['settings']['default_image'] > 0){
        $default_img_fid  = $info['settings']['default_image'];
        $default_img_file = file_load($default_img_fid);
      }
      $picurl = file_create_url($default_img_file->uri);
    }
    // $picurl = theme_get_setting('logo')
    $desc = variable_get('site_slogan', '主内公众云提供技术支持');
    if(isset($node->body[LANGUAGE_NONE])){
      $desc = truncate_utf8(strip_tags($node->body[LANGUAGE_NONE]['0']['value']), 54,  FALSE, TRUE, 1);
      if($node->body[LANGUAGE_NONE]['0']['summary'])
         $desc = truncate_utf8(strip_tags($node->body[LANGUAGE_NONE]['0']['summary']), 54,  FALSE, TRUE, 1);
    }
    $shareData = array(
      'title'=> $node->title,
      'desc'=> $desc,
      'link'=> "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
      'imgUrl'=> $picurl,
    );
    drupal_add_js(array('wxjs' => array('shareData'=>$shareData)), 'setting');
  }
}
