<?php
/**
 * hook_rescources_info
 */
function mp_fm_rescources_info(){
  // $nodes = dale_get_mp_nodes('audio_resource', 100);
  // foreach ($nodes as $key => $node) {    
  //   $rescources[] = array(
  //     'name' => '700' . $node->nid,
  //     'desc' => $node->title.'【700'. $node->nid .'】',
  //   );
  // }
  $rescources[] = array(
      'name' => '700',
      'desc' => '网络电台资源【700】',
    );
  return $rescources;
}
/**
 * Hook_wxresources
 */
function mp_fm_wxresources($resources, $account, $keyword){
  // 70033
	$enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  $resources = &drupal_static(__FUNCTION__);
  if(!isset($resources)){
    if(in_array($keyword, array('xl','sl','xwz'))){
      require_once('xmly.inc');
      $resources['key_'.$keyword]= array(
          'type'  =>  'music',
          'obj'   => xmly_get_radio($keyword),
        );
      return $resources;
    }
    if($keyword =='700'&&isset($enabled_resources[$keyword]) && $enabled_resources[$keyword]){
      $nodes = dale_get_mp_nodes('audio_resource', 100);
      $return_menu = "【700】--网络电台资源--";
      foreach ($nodes as $key => $node) {   
         $return_menu .="\n【700". $node->nid ."】".$node->title;
      }
      $resources['key_'.$keyword]= array(
          'type'  =>  'text',
          'obj'   => array(
            'text'  => $return_menu,
          )
      );
      return $resources;
    }
    $temp_key = substr($keyword, 0, 3);
    if($temp_key != '700') return;

  	if(isset($enabled_resources[$keyword]) && $enabled_resources[$keyword]){
      $nid = substr($keyword, 3);
      $node = node_load($nid);

      if($node->field_audio_type[LANGUAGE_NONE][0]['value'] == 'xmly'){
        $html = file_get_contents($node->field_link[LANGUAGE_NONE][0]['value']);//'http://www.ximalaya.com/22873240/album/348894'
        preg_match('/sound_ids=".+/', $html,$matches);
        $html = $matches[0];
        $html = str_replace('sound_ids="', '', $html );
        $html = str_replace('">', '', $html );
        $sound_ids = explode(',', $html);
        $sound_ids = array_reverse($sound_ids); 
        
        if ($keyword == '70037') {//今夜心未眠zhi港口之声
          $index = count($sound_ids)-1;
        }elseif ($keyword == '70033') {//I关怀zhi健康节目
          $index = (date('z')-11) % count($sound_ids);
        }else{
          $index = (date('z')) % count($sound_ids); 
        }

        # code...
        $offset = 0;
        $donext = date('s')%2;
        if ($donext) {
          $index = (date('z')-$offset) % count($sound_ids);
        }
        $sound_id = trim($sound_ids[$index]);
        $json = file_get_contents('http://www.ximalaya.com/tracks/'.$sound_id.'.json');
        $json = json_decode($json);
        $resources['key_'.$keyword]= array(
          'type'  =>  'music',
          'obj'   => array(
            'title' => $json->title,
            'desc'  =>  $json->intro,
            'musicurl'  =>  $json->play_path_32,
            'hgmusicurl'  =>  $json->play_path_64,
          ),
        );
      }
      //70034
      if($node->field_audio_type[LANGUAGE_NONE][0]['value'] == 'lizhi'){
        // $html = file_get_contents($node->field_link[LANGUAGE_NONE][0]['value']);        
        //http://www.lizhi.fm/api/radio_audios?band=43136&s=0&l=365
        $html = json_decode($node->body[LANGUAGE_NONE][0]['value']);
        $sound_ids = array_reverse($html); 
        $index = (date('z')-17) % count($sound_ids);
        if (date('i') > 30) {
          $index++;
        }
        $json = $sound_ids[$index];        
        $desc = '公众号:'.variable_get('mp_config_appname_'.$account->uid, "永不止息").' 更多节目请回复【xmly】';
        watchdog($index, $keyword, array(), WATCHDOG_NOTICE, 'link');
        $resources['key_'.$keyword]= array(
          'type'  =>  'music',
          'obj'   => array(
            'title' => $json->name,
            'desc'  =>  $desc,
            'musicurl'  =>  $json->url,
            'hgmusicurl'  =>  $json->url,
          ),
        );
      }
    }

  }
	return $resources;
}
