<?php
/**
 * hook_rescources_info
 */
function mp500_rescources_info(){
  $rescources[] = array(
    'name' => '500',
    'desc' => '【500】优质资源',
  );
  return $rescources;
}

/**
 * hook_wxrescources
 * TODO:  cache_clear_all('mp_liangyou', 'cache', TRUE); once a day!
 */
function mp500_wxresources($resources, $account, $keyword, $weObj){
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['500']) && $enabled_resources['500'])){
    return $resources;
  }
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_liangyou_wxresources_'.$account->uid.$keyword)) {
      $my_data = $cache->data;
    }else {
      $my_data = _mp500_wxresources($resources, $account, $keyword, $weObj);
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  // return $resources;//NO NEED RETURN! $my_data IS THE FUNCTION RETURN VALUES!
}


/**
 * hook_wxrescources
 * TODO:  cache_clear_all('mp_liangyou', 'cache', TRUE); once a day!
 */
function _mp500_wxresources($resources, $account, $keyword, $weObj){
    //http://audio.yongbuzhixi.com/resources/365/2014/20140109.mp3
    $cdnlink = 'http://wxresources.b0.upaiyun.com';
    $check_word = substr($keyword, 0,3);
    if($check_word==500){
      $resources['key_'.$keyword]= array(
        'type'  =>  'text',
        'cache' => 0,
        'gadata'   =>  array(
           'category'        => '500',
           'action'          => 'menu get',
           'label'           => 'wxservice_'.$account->uid,
        ),
        'obj'   => array(
          'text' => "【501】炼爱-真爱挑战40天
          【502】圣经英语-马可福音
          【503】王明道文庫－窄門
          【504】真爱好男女
          【505】亲爱的公主
          【506】为儿女祷告40天",
        ),
      );
      return $resources;
    }
    $index = (int)substr($keyword, 3);
    $index = $index?$index:0;
    if($check_word > 500 || $check_word <= 599 ) {
      $res500 = array(
        501=>array(
          'title'=>'炼爱-真爱挑战40天',
          'count'=>'40',
        ),
        502=>array(
          'title'=>'圣经英语-马可福音',
          'count'=>'310',
          'json'  =>1,
        ),
        503=>array(
          'title'=>'王明道文庫－窄門',
          'count'=>'37',
        ),
        504=>array(
          'title'=>'真爱好男女',
          'count'=>'37',
          'desc' => array(
            '1.人生的意义何在',
            '2.如何建立爱的关系',
            '3.七情六欲是祸是福',
            '4.性关系等于亲密关系吗？',
            '5.爱情风格-介绍爱情风格+浪漫之爱（1）',
            '6.爱情风格-浪漫之爱（2）',
            '7.爱情风格-游戏之爱',
            '8.爱情风格-友伴之爱',
            '9.爱情风格-务实型',
            '10.爱情风格-狂恋依附型',
            '11.爱情风格-奉献之爱',
            '12.爱之语（1）-精心的礼物',
            '13.爱之语（2）-肯定的言语',
            '14.爱之语（3）-精心的时刻',
            '15.爱之语（4）-服务的行动',
            '16.爱之语（5）-身体的接触',
            '17.守贞与承诺',
            '18.拒绝婚前性行为的实际方法',
            '19.恋爱中的三大迷思',
            '20.几种没有结果的情感关系（1）',
            '21.几种没有结果的情感关系（2）',
            '22.致命的性格缺陷（1）',
            '23.致命的性格缺陷（2）',
            '24.恋爱中的定时炸弹',
            '25.择偶注意特质（1）愿意追求自我成长、敞开情感',
            '26.择偶注意特质（2）诚信正直、成熟度与责任感',
            '27.择偶注意特质（3）健康的自尊、正面积极的生活态度',
            '28.择偶注意特质（4）触电的化学反应',
            '29.真爱不灭定律（1）性与真爱的关系',
            '30.真爱不灭定律（2）持守纯洁，好处多多',
            '31.真爱不灭定律（3）纯洁使我们拥有圣洁的生命',
            '32.真爱不灭定律（4）纯洁使我们的关系更亲密',
            '33.我可以谈恋爱了吗？',
            '34.我们合适吗？（1）你的价值观',
            '35.我们合适吗？（2）经营关系的能力',
            '36.爱情盟约-关于承诺这件事（1）',
            '37.爱情盟约-关于承诺这件事（2）',
            ),
        ),
        505=>array(
          'title'=>'亲爱的公主',
          'count'=>'28',
          'desc' =>array(
            '1.你是智慧与美的代言人',
            '2.不要问魔镜你有多美',
            '3.公主吸引王子，公厕吸引苍蝇',
            '4.美可以改变，美需要转化',
            '5.恋爱四季-暧昧期（1）',
            '6.恋爱四季-暧昧期（2）',
            '7.恋爱四季-暧昧期（3）',
            '8.恋爱四季-热恋期（1）',
            '9.恋爱四季-热恋期（2）',
            '10.恋爱四季-热恋期（3）',
            '11.恋爱四季-热恋期（4）',
            '12.恋爱四季-冲突期（1）',
            '13.恋爱四季-冲突期（2）',
            '14.恋爱四季-冲突期（3）',
            '15.恋爱四季-情侣生活中的琐事（1）',
            '16.恋爱四季-情侣生活中的琐事（2）',
            '17.恋爱四季-情侣生活中的琐事（3）',
            '18.幸福十诫（1）',
            '19.幸福十诫（2）',
            '20.幸福十诫（3）',
            '21.让家人接纳男朋友是你的责任',
            '22.关于结婚基金',
            '23.关于婚礼规画',
            '24.拍摄美美的婚纱照',
            '25.帅爸爸谈真爱（1）',
            '26.帅爸爸谈真爱（2）',
            '27.帅爸爸谈真爱（3）',
            '28.帅爸爸谈真爱（4）',
          ),
        ),
        506=>array(
          'title'=>'智慧有情人CD',
          'count'=>'11',
        ),
        507=>array(
          'title'=>'每日亲近神-路加福音',
          'count'=>'40',
        ),
        508=>array(
          'title'=>'拯救CD',
          'count'=>'10',
        ),
        509=>array(
          'title'=>'为儿女祷告40天',
          'count'=>'40',
        ),
        510=>array(
          'title'=>'为儿女祷告40天',
          'count'=>'40',
        ),
        511=>array(
          'title'=>'为儿女属灵品格祷告',
          'count'=>'56',
        ),
        512=>array(
          'title'=>'有声书:天路历程',
          'count'=>'26',
        ),
        513=>array(
          'title'=>'有声书:游子吟',
          'count'=>'55',
        ),
        514=>array(
          'title'=>'有声书:密室',
          'count'=>'45',
        ),
        515=>array(
          'title'=>'有声书:自由在哪里',
          'count'=>'29',
        ),
        516=>array(
          'title'=>'有声书:里外更新',
          'count'=>'14',
        ),
        517=>array(
          'title'=>'每日亲近神-马太福音',
          'count'=>'98',
        ),
        518=>array(
          'title'=>'每日亲近神-马可福音',
          'count'=>'35',
        ),
        519=>array(
          'title'=>'每日亲近神-约翰福音',
          'count'=>'4',
        ),
      );
      if(in_array($check_word,array_keys($res500))){
        if($index==0)
          $index = date('z')%$res500[$check_word]['count'];
        $title = $res500[$check_word]['title'];
        $str_pad = strlen($res500[$check_word]['count']);
        $path = '/500/'.$check_word.'/'.str_pad($index,$str_pad,"0",STR_PAD_LEFT).'.mp3';
        $url = $cdnlink.$path;//.upyun_get_token($path);
        $desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新";
        $resources['key_'.$keyword]= array(
          'type'  =>  'music',
          'cache' => 43200,
          'path'  =>  $path,
          'gadata'   =>  array(
             'category'        => '500',
             'action'          => $title,
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'title' => $title.$index.'/'.$res500[$check_word]['count'].'♫',
            'desc'  =>  $desc,
            'musicurl'  =>  $url,
            'hgmusicurl'  =>  $url,
          ),
        );

        if(isset($res500[$check_word]['desc'])){
          $custommessage = $res500[$check_word]['desc'][$index];
        }
        if($custommessage){
          $resources['key_'.$keyword]['custommessage'] = '【'.$keyword.'】'.$title."\n".$custommessage;
        }
      }
      return $resources;
    }
}
