<?php
/**
 * hook_rescources_info
 */
function mp500_rescources_info(){
  $rescources[] = array(
    'name' => '500',
    'desc' => '【500】会员资源',
  );
  return $rescources;
}

/**
 * hook_wxrescources
 * TODO:  cache_clear_all('mp_liangyou', 'cache', TRUE); once a day!
 */
function mp500_wxresources($resources, $account, $keyword, $weObj){
  $enabled_resources = variable_get('wechat_resources_'.$account->uid, array());
  if(!(isset($enabled_resources['500']) && $enabled_resources['500'])){
    return $resources;
  }
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_liangyou_wxresources_'.$account->uid.$keyword)) {
      $my_data = $cache->data;
    }else {
      $my_data = _mp500_wxresources($resources, $account, $keyword, $weObj);
      //cache = 0;永久缓存 cache = 43200;缓存一天／2
      if(isset($my_data['key_'.$keyword]['cache'])){
        if($my_data['key_'.$keyword]['cache']==0){
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache');
        }else{
          cache_set('mp_liangyou_wxresources_'.$account->uid.$keyword, $my_data, 'cache', time() + $my_data['key_'.$keyword]['cache']);
        }
      }
    }
  }
  // return $resources;//NO NEED RETURN! $my_data IS THE FUNCTION RETURN VALUES!
}


/**
 * hook_wxrescources
 * TODO:  cache_clear_all('mp_liangyou', 'cache', TRUE); once a day!
 */
function _mp500_wxresources($resources, $account, $keyword, $weObj){
    require_once('mp500.inc');
    //http://audio.yongbuzhixi.com/resources/365/2014/20140109.mp3
    $cdnlink = 'http://wxresources.b0.upaiyun.com';
    $check_word = substr($keyword, 0,3);
    if($check_word==500){
      $resources['key_'.$keyword]= array(
        'type'  =>  'text',
        'cache' => 0,
        'gadata'   =>  array(
           'category'        => '500',
           'action'          => 'menu get',
           'label'           => 'wxservice_'.$account->uid,
        ),
        'obj'   => array(
            'text'  => _get_mp_500_menu(),
        ),
      );
      return $resources;
    }
    $index = (int)substr($keyword, 3);
    $index = $index?$index:0;
    if($check_word > 500 || $check_word <= 599 ) {
      $res500 = _get_mp_500_res();
      if(in_array($check_word,array_keys($res500))){
        if($index==0)
          $index = date('z')%$res500[$check_word]['count'];
        $title = $res500[$check_word]['title'];
        $str_pad = strlen($res500[$check_word]['count']);
        $path = '/500/'.$check_word.'/'.str_pad($index,$str_pad,"0",STR_PAD_LEFT).'.mp3';
        $url = $cdnlink.$path;//.upyun_get_token($path);
        $desc = "点击►收听 公众号:".variable_get('mp_config_appname_'.$account->uid, "永不止息")." 每日更新";
        $resources['key_'.$keyword]= array(
          'type'  =>  'music',
          'cache' => 43200,
          'path'  =>  $path,
          'gadata'   =>  array(
             'category'        => '500',
             'action'          => $title,
             'label'           => 'wxservice_'.$account->uid,
          ),
          'obj'   => array(
            'title' => $title.$index.'/'.$res500[$check_word]['count'].'♫',
            'desc'  =>  $desc,
            'musicurl'  =>  $url,
            'hgmusicurl'  =>  $url,
          ),
        );

        if(isset($res500[$check_word]['desc'])){
          $custommessage = $res500[$check_word]['desc'][$index];
        }
        if(isset($res500[$check_word]['json'])){
          // json array('href=mp3link' 'title' 'desc' 'booklink')
          $json = drupal_json_decode(file_get_contents(drupal_get_path('module', 'mp500').'/'.$check_word.'.json'));
          $custommessage = '';
          if(isset($json[$index]['title']))
            $custommessage .=$json[$index]['title']."\n";
          if(isset($json[$index]['desc']))
            $custommessage .=$json[$index]['desc']."\n";
          if(isset($json[$index]['booklink']))
            $custommessage .='<a href="'.$json[$index]['booklink'].'">讲义讲章</a>'."\n";
        }
        if($custommessage){
          $resources['key_'.$keyword]['custommessage'] = '【'.$keyword.'】'.$title."\n".$custommessage;
        }
      }
      return $resources;
    }
}
